### ISSUE TITLE
Invalid transaction schema when following https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html

### ISSUE THREAD

**Issue by josephwinston** [bigchaindb/bigchaindb#1009]
I'm attempting to follow the instructions on installing bigchaindb with docker found [on docs.bigchaindb.com](https://docs.bigchaindb.com/projects/server/en/latest/appendices/run-with-docker.html)

```$ docker images``` shows that bigchaindb is latest:

``` bash
 bigchaindb/bigchaindb   latest              2f2f71ef00b6        3 weeks ago         496 MB
```

I've installed bigchaindb's [python driver using these instructions](https://docs.bigchaindb.com/projects/py-driver/en/latest/quickstart.html)

Running the [code](https://gist.github.com/josephwinston/5ae12386bb02629bf2c46ca121637e37) taken from <https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html> or that matter from <https://github.com/bigchaindb/bigchaindb-driver/blob/master/docs/usage.rst>, results in the following error:

``` python
fulfilled_creation_tx= {'id': '4153a92e8263041d0097b849c7884ac3369b879f76ef1c5dc3032b7edb4cb634', 'version': 1, 'transaction': {'metadata': {'data': {'planet': 'earth'}, 'id': '560b7e74-ee83-46b1-8118-8042d69fb88c'}, 'fulfillments': [{'input': None, 'fulfillment': 'cf:4:Z3IN_ry8QmYy4CyXBmrqI23-KfJ8rcFg47iG448QwSkZmprdEO0dLY1N4mqsGnN7LvJvrInO6VwGvFhb1n1i6vxeIkkHkfpwwvuFg2U10w7O7QacX2gXg0ZfF0kZoc8F', 'owners_before': ['7xos5TxQmNwyEtGQxHmkDQE9VQdT8jyiuSc8jCNT7WWL'], 'fid': 0}], 'asset': {'updatable': False, 'data': {'bicycle': {'serial_number': 'abcd1234', 'manufacturer': 'bkfab'}}, 'id': 'b4159fb2-be7e-4195-855d-172e7c9b0302', 'refillable': False, 'divisible': False}, 'operation': 'CREATE', 'conditions': [{'cid': 0, 'condition': {'uri': 'cc:4:20:Z3IN_ry8QmYy4CyXBmrqI23-KfJ8rcFg47iG448QwSk:96', 'details': {'type_id': 4, 'public_key': '7xos5TxQmNwyEtGQxHmkDQE9VQdT8jyiuSc8jCNT7WWL', 'bitmask': 32, 'type': 'fulfillment', 'signature': None}}, 'amount': 1, 'owners_after': ['7xos5TxQmNwyEtGQxHmkDQE9VQdT8jyiuSc8jCNT7WWL']}]}}
txid="4153a92e8263041d0097b849c7884ac3369b879f76ef1c5dc3032b7edb4cb634"
Traceback (most recent call last):
  File "/tmp/foo.py", line 36, in <module>
    sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
  File "/Users/josephwinston/anaconda/envs/python3/lib/python3.5/site-packages/bigchaindb_driver/driver.py", line 187, in send
    method='POST', path=self.path, json=transaction)
  File "/Users/josephwinston/anaconda/envs/python3/lib/python3.5/site-packages/bigchaindb_driver/transport.py", line 46, in forward_request
    response = connection.request(method=method, path=path, json=json)
  File "/Users/josephwinston/anaconda/envs/python3/lib/python3.5/site-packages/bigchaindb_driver/connection.py", line 45, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.TransportError: (400, '{\n  "message": "Invalid transaction schema: \'fulfillments\' is a required property", \n  "status": 400\n}\n', {'status': 400, 'message': "Invalid transaction schema: 'fulfillments' is a required property"})
```

The same error appears when I install the python driver from master found at <https://github.com/bigchaindb/bigchaindb-driver> 

Any suggestions on what I'm doing wrong or where I should start chasing down the issue?

**Comment by josephwinston** [comment]
According to a comment in <https://gitter.im/bigchaindb/bigchaindb> by Tim Daubenschütz @TimDaub on December 6, the issues is that I am running latest, which won't work with the driver.
