### ISSUE TITLE
Mongo driver complains about "replSet" when connecting

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1034]
I use the following command to start mongo:

`docker run -d --name bdb_mongo -p 27017:27017 -p 28017:28017 mongo sh -c 'exec mongod'`

And run the command:

`BIGCHAINDB_DATABASE_BACKEND=mongodb pytest -s -x`

Gives the error:

```
tests/conftest.py:149: in _setup_database
    schema.init_database(conn)
bigchaindb/backend/schema.py:86: in init_database
    create_database(connection, dbname)
.env/lib/python3.5/functools.py:743: in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
bigchaindb/backend/mongodb/schema.py:30: in create_database
    initialize_replica_set(conn)
bigchaindb/backend/mongodb/schema.py:96: in initialize_replica_set
    replica_set_name = _get_replica_set_name(conn)
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.
```

If I run instead:

`docker run -d --name bdb_mongo -p 27017:27017 -p 28017:28017 mongo sh -c 'exec mongod --replSet rs0'`

I get: pymongo.errors.NotMasterError: not master (It's trying to drop the old test database)

If I run:

`docker run -d --name bdb_mongo -p 27017:27017 -p 28017:28017 mongo sh -c 'exec mongod --replSet=rs0 --master`

It seems to spin forever in pytest:

```
Traceback (most recent call last):
  File "/home/scott/code/bigchaindb/bigchaindb/.env/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/config.py", line 57, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/main.py", line 127, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/main.py", line 107, in wrap_session
    config.hook.pytest_keyboard_interrupt(excinfo=excinfo)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/terminal.py", line 377, in pytest_keyboard_interrupt
    self._keyboardinterrupt_memo = excinfo.getrepr(funcargs=True)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/code.py", line 425, in getrepr
    return fmt.repr_excinfo(self)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/code.py", line 629, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/code.py", line 609, in repr_traceback
    reprentry = self.repr_traceback_entry(entry, einfo)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/code.py", line 556, in repr_traceback_entry
    source = self._getentrysource(entry)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/code.py", line 481, in _getentrysource
    source = entry.getsource(self.astcache)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/code.py", line 206, in getsource
    astnode=astnode)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/source.py", line 347, in getstatementrange_ast
    start, end = get_statement_startend2(lineno, astnode)
  File "/home/scott/code/bigchaindb/bigchaindb/.env/lib/python3.5/site-packages/_pytest/_code/source.py", line 319, in get_statement_startend2
    for x in ast.walk(node):
  File "/usr/lib/python3.5/ast.py", line 218, in walk
    yield node
```

For now I commented `initialize_replica_set(conn)` in backend/mongodb/schema.py, and it works.

**Comment by r-marques** [comment]
`exec mongod --replSet=rs0`

**Comment by libscott** [comment]
I'm not really sure what was going on, but it started working eventually. In the meantime I re-created my 'bigchaindb' repository, the following way to avoid deleting my branches:

```
cd ..
mv bigchaindb bigchaindb_old
git clone bigchaindb_old bigchaindb
rm -f bigchaindb/.git
rsync -ax bigchaindb_old/.git bigchaindb
```
