### ISSUE TITLE
[http api] AssetIdMismatch error not propagating to user

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#1180]
When an `AssetIdMismatch` exception occurs, a `500 Internal Server Error` gets returned rather than a `400` with the proper message.

The exception traceback:

```bash

server_1     | [2017-02-09 13:02:27,227] ERROR in app: Exception on /api/v1/transactions/ [POST]
server_1     | Traceback (most recent call last):
server_1     |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
server_1     |     rv = self.dispatch_request()
server_1     |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
server_1     |     return self.view_functions[rule.endpoint](**req.view_args)
server_1     |   File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
server_1     |     resp = resource(*args, **kwargs)
server_1     |   File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
server_1     |     return self.dispatch_request(*args, **kwargs)
server_1     |   File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
server_1     |     resp = meth(*args, **kwargs)
server_1     |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/web/views/transactions.py", line 95, in post
server_1     |     bigchain.validate_transaction(tx_obj)
server_1     |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 152, in validate_transaction
server_1     |     return self.consensus.validate_transaction(self, transaction)
server_1     |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/consensus.py", line 21, in validate_transaction
server_1     |     return transaction.validate(bigchain)
server_1     |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/models.py", line 99, in validate
server_1     |     raise AssetIdMismatch(('The asset id of the input does not'
server_1     | bigchaindb.common.exceptions.AssetIdMismatch: The asset id of the input does not match the asset id of the transaction
```

**Comment by r-marques** [comment]
@sbellem can we closed this?
I tested it and I got a `400` with the correct error message:
```text
In [41]: bdb.transactions.send(transfer_tx_signed)
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-41-fe794dcf0a79> in <module>()
----> 1 bdb.transactions.send(transfer_tx_signed)

/home/rodmar/.virtualenvs/bigchaindb/lib/python3.5/site-packages/bigchaindb_driver/driver.py in send(self, transaction, headers)
    303         """
    304         return self.transport.forward_request(
--> 305             method='POST', path=self.path, json=transaction, headers=headers)
    306 
    307     def retrieve(self, txid, headers=None):

/home/rodmar/.virtualenvs/bigchaindb/lib/python3.5/site-packages/bigchaindb_driver/transport.py in forward_request(self, method, path, json, params, headers)
     56             params=params,
     57             json=json,
---> 58             headers=headers,
     59         )
     60         return response.data

/home/rodmar/.virtualenvs/bigchaindb/lib/python3.5/site-packages/bigchaindb_driver/connection.py in request(self, method, path, json, params, headers, **kwargs)
     55         if not (200 <= response.status_code < 300):
     56             exc_cls = HTTP_EXCEPTIONS.get(response.status_code, TransportError)
---> 57             raise exc_cls(response.status_code, text, json)
     58         data = json if json is not None else text
     59         return HttpResponse(response.status_code, response.headers, data)

BadRequest: (400, '{\n  "message": "Invalid transaction (AssetIdMismatch): The asset id of the input does not match the asset id of the transaction", \n  "status": 400\n}\n', {'message': 'Invalid transaction (AssetIdMismatch): The asset id of the input does not match the asset id of the transaction', 'status': 400})
```

**Comment by sbellem** [comment]
Ah, ok!
