### ISSUE TITLE
Use MongoDB to run:bigchaindb start

### ISSUE THREAD

**Issue by vincent0330** [bigchaindb/bigchaindb#1246]
1,"bigchaindb -y configure mongodb"
2,start:
But the error :
 bigchaindb start
INFO:bigchaindb.commands.bigchain:BigchainDB Version 0.9.1
INFO:bigchaindb.config_utils:Configuration loaded from `/home/jingqingyun/.bigchaindb`
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 144, in initialize_replica_set
    conn.admin.command('replSetInitiate', config)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: already initialized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB==0.9.1', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 401, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 96, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 201, in run_start
    _run_init()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 142, in _run_init
    schema.init_database(connection=b.connection)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/schema.py", line 99, in init_database
    create_database(connection, dbname)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/schema.py", line 19, in create_database
    if dbname in conn.conn.database_names():
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 56, in conn
    self._connect()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 105, in _connect
    initialize_replica_set(self.host, self.port, self.connection_timeout)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 146, in initialize_replica_set
    if exc_info.details['codeName'] == 'AlreadyInitialized':
KeyError: 'codeName'

**Comment by TimDaub** [comment]
@vincent0330 I had the same error once when using a not supported version of MongoDB.
Make sure you have MongoDB version >= 3.4 installed.

Please let me know if this helped, so that we can close this ticket.

**Comment by vincent0330** [comment]
@TimDaub Thanks, My MongoDB version :db version v3.2.12,
And I upgrate MondoDB version=v3.4.2, bigchaindb start sucessfully.
Again,Thank you very much!
