### ISSUE TITLE
the error on this line: if tx['assignee'] == self.bigchain.me 

### ISSUE THREAD

**Issue by vincent0330** [bigchaindb/bigchaindb#1284]
When I start bigchaindb ,the error is:

bigchaindb start
INFO:bigchaindb.commands.bigchain:BigchainDB Version 0.9.3
INFO:bigchaindb.config_utils:Configuration loaded from `/home/ubuntu/.bigchaindb`
INFO:bigchaindb.commands.bigchain:Starting BigchainDB main process with public key A4eyf7E1gXr4snGm49aNRi4aJTfnrZQGDQcc8WMpNQq1
INFO:bigchaindb.processes:Initializing BigchainDB...
INFO:bigchaindb.processes:Starting block
INFO:bigchaindb.processes:Starting voter
INFO:bigchaindb.processes:Starting stale transaction monitor
INFO:bigchaindb.processes:Starting election
INFO:bigchaindb.processes:
****************************************************************************
*                                                                          *
*   Initialization complete. BigchainDB Server is ready and waiting.       *
*   You can send HTTP requests via the HTTP API documented in the          *
*   BigchainDB Server docs at:                                             *
*    https://bigchaindb.com/http-api                                       *
*                                                                          *
*   Listening to client connections on: localhost:9984                     *
*                                                                          *
****************************************************************************

[2017-03-14 23:01:39 -0700] [3625] [INFO] Starting gunicorn 19.7.0
[2017-03-14 23:01:39 -0700] [3625] [INFO] Listening at: http://127.0.0.1:9984 (3625)
[2017-03-14 23:01:39 -0700] [3625] [INFO] Using worker: threads
[2017-03-14 23:01:39 -0700] [3638] [INFO] Booting worker with pid: 3638
[2017-03-14 23:01:39 -0700] [3639] [INFO] Booting worker with pid: 3639
[2017-03-14 23:01:39 -0700] [3640] [INFO] Booting worker with pid: 3640
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.4/dist-packages/multipipes/pipeline.py", line 74, in run_forever
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/multipipes/pipeline.py", line 106, in run
    result = self.target(*args)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/pipelines/block.py", line 46, in filter_tx
    if tx['assignee'] == self.bigchain.me:
**TypeError: 'NoneType' object is not subscriptable**

And my email is ”wjs_net@163.com",can you give me a email?
Thanks.

**Comment by vincent0330** [comment]
It is OK.
I pull the code,and  run the "process.py->start()" instead of "bigchaindb start" on a bigchaindb server.  It's ok.
