### ISSUE TITLE
Double spent in chain; gets thrown on get_spent receival

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1343]
This one is for @diminator: "when playing around with the kyber tx_explorer -> that happens"

```
bdb-server_1                | [2017-03-27 17:43:48,029] ERROR in app: Exception on /api/v1/outputs [GET]
bdb-server_1                | Traceback (most recent call last):
bdb-server_1                |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
bdb-server_1                |     rv = self.dispatch_request()
bdb-server_1                |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
bdb-server_1                |     return self.view_functions[rule.endpoint](**req.view_args)
bdb-server_1                |   File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
bdb-server_1                |     resp = resource(*args, **kwargs)
bdb-server_1                |   File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
bdb-server_1                |     return self.dispatch_request(*args, **kwargs)
bdb-server_1                |   File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
bdb-server_1                |     resp = meth(*args, **kwargs)
bdb-server_1                |   File "/usr/src/app/bigchaindb/web/views/outputs.py", line 26, in get
bdb-server_1                |     include_spent)
bdb-server_1                |   File "/usr/src/app/bigchaindb/core.py", line 420, in get_outputs_filtered
bdb-server_1                |     outputs = [o for o in outputs
bdb-server_1                |   File "/usr/src/app/bigchaindb/core.py", line 421, in <listcomp>
bdb-server_1                |     if not self.get_spent(o.txid, o.output)]
bdb-server_1                |   File "/usr/src/app/bigchaindb/core.py", line 352, in get_spent
bdb-server_1                |     ' with the chain'.format(txid))
bdb-server_1                | bigchaindb.exceptions.CriticalDoubleSpend: `6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140` was spent more than once. There is a problem with the chain
```

Looks like it gets thrown in [`get_spent`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L350)

**Comment by diminator** [comment]
Some data
```
http://localhost:49984/api/v1/outputs?public_key=AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin&unspent=true
```

RethinktDB
```
[{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620887","transactions":[{"asset":{"id":"3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"},"id":"efd3f7464e649defc7f13e42eafdeea9621d9a4a5ac45c3468e309f5ee683c15","inputs":[{"fulfillment":"cf:4:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmMP7Qv69ghDKTIyQt70NejgSGJUCPqrhaDcbBKpBx6Sd1mZRhyIl26oURSOaUQkHDFnLLjMvwR38uTot9d2qbAE","fulfills":{"output":0,"txid":"6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140"},"owners_before":["AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"]}],"metadata":{"message":"fd"},"operation":"TRANSFER","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmM:96"},"public_keys":["AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"]}],"version":"0.9"},{"asset":{"id":"3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"},"id":"135bf52f20810e9c61e1f7808eb13cd7faa8c4e5c4a0e8eb97c61877a27fbfeb","inputs":[{"fulfillment":"cf:4:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmMHY3sM02RwlfIRFC71n-PnHZMyg0ZDsW6XC3QmWhTa4j9CLuzAZkmgy6wBKCmA7exW2HfKrLoH_gWSva5cO-0O","fulfills":{"output":0,"txid":"6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140"},"owners_before":["AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"]}],"metadata":{"message":"fds"},"operation":"TRANSFER","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmM:96"},"public_keys":["AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"bf8eac239223d09c9a1126c3f69749bb9ae1c43e465252e614a0a99baeeb2a98","signature":"yV8gy6fCoAGcUfjDF8YgVvVJiR1eUWdu4cgmFr6eUh8uhe2hGaacAcwmGCtbaLjhHL2Pmg62Fj27crEEYdKmsn7"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620461","transactions":[{"asset":{"id":"3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"},"id":"6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140","inputs":[{"fulfillment":"cf:4:Nv2PPvWa8H7IKemuuBxqt_ZZiC5xQzLICTYqd9eioTdi-OJQYfuWjD7xBs7oNTfLakBJnE5zNduNbzp651qDBpbvg3nd6gZLgEAJoDwjELgzWLW_tJuk3WJ3Oo6Vl2cA","fulfills":{"output":0,"txid":"6ad0a817aa0c2926572d00b5000276393c9ec098ca3795e2a58b18535f401a1a"},"owners_before":["4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG"]}],"metadata":{"message":"a new transaction to @bruce"},"operation":"TRANSFER","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmM:96"},"public_keys":["AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"af54f4a4b5483e1cee27b0670de2d9023ee5ae1c944a6c0ba398006b3369b234","signature":"5jN8163C7YjQKBaG4dxaDxEQhtthqNvk2mwuX2AUiDc83VBUygqJuhttdiWnXhfmS4UAS4ZEQRyeLZzDWvqEowMh"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620173","transactions":[{"asset":{"data":{"frequency":2,"timestamp":"1490620171475"}},"id":"30ded103981f2a85ed6c80d2e8af9b9e53c3784c8c06581ed28a42f6683497cf","inputs":[{"fulfillment":"cf:4:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGiH15Trs7gdKV09k3dEVfsVdlNL6lyrgHYE7xrvAoWRfNWx_fv8cF3o0GX46QF5pyWAjDEi4bO3VPjgAyzIop8P","fulfills":null,"owners_before":["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}],"metadata":null,"operation":"CREATE","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGg:96"},"public_keys":["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"40aa5fc77279cf51f31e77f8dd679ff07707e1c348a33bdfd35d912ade42cbe5","signature":"3JEWR8fw8vkZwwqiJnXCN1TeQnTJfs74WiMZvY6bdKNHnfBr4unkMf2t6VKbNXNeHnCAH54Tafbt9sGYLuLcF8C"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620921","transactions":[{"asset":{"data":{"definition":"test"}},"id":"1c539a8f168966d8a2d063e9f4162758a8cfceee5c8daa569d3e9c30b68c9ed3","inputs":[{"fulfillment":"cf:4:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOf82iCDrB0UoZhL6gqjqaPol_7ISOU7XV5ldhme-xAFiiqk5W-k-bFZEM6o0TTBeCuJhfYcVF-HrDmj9S6oXYgG","fulfills":null,"owners_before":["79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"]}],"metadata":null,"operation":"CREATE","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOc:96"},"public_keys":["79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"702909a5fbfcb08dfd617201f97f8dddae8158e1a0435cf4d23531cf99c27c5f","signature":"y4HSd7jbzYvxjDsXZUAB6HcpFJ23FZo23PqkmRZebAVHeozBuiM5rkr4QHj3YMPugH2UWT3GndpQSH9W9WYmUtx"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490618322","transactions":[{"asset":{"data":null},"id":"513c90fe462bfa61ad54f31b1080831b4edcd4aa994e6a07ac439ea0ef2798a0","inputs":[{"fulfillment":"cf:4:5k4Kk05495kBTCCaa0UCa1n0KHP55st17og8wXzC2KlHzVsLKimybkfX3sg-ENyQpd34qN0wRerdYE36EtiN_c-bwAXleFx5ksBOJQyCtO9pCSWfBQrqaYgcb7maDs4E","fulfills":null,"owners_before":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]}],"metadata":{"message":"Hello World from the BigchainDB"},"operation":"GENESIS","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:5k4Kk05495kBTCCaa0UCa1n0KHP55st17og8wXzC2Kk:96"},"public_keys":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]}],"version":"0.10"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"6679eda035aa457dfa2ad4fda07dfd36b3977966980e79ecb11c51c1008082ef","signature":"3ZqYtSy9UuM42fZnxYUmhe6g9YxqwCnTkBoXeRduE6ZpBNRUvMMLNh8BifndEe9VZwH2cbAvVXkp3LqrA6wJ6KUF"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620084","transactions":[{"asset":{"id":"3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"},"id":"6ad0a817aa0c2926572d00b5000276393c9ec098ca3795e2a58b18535f401a1a","inputs":[{"fulfillment":"cf:4:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGiJYkx9UaihwdLCLbtdzfIhL3CNrBo95lGwNWNzcqwb7qO1rvFw2NlHYYq-kwNCOW8H9mbBBiYFLAANpYhnXAAO","fulfills":{"output":0,"txid":"3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"},"owners_before":["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}],"metadata":{"message":"send to @dimi"},"operation":"TRANSFER","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:Nv2PPvWa8H7IKemuuBxqt_ZZiC5xQzLICTYqd9eioTc:96"},"public_keys":["4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"9e74b55d7efd48c63654347531ebac9c57dfd72d5f434ea373d5ea8ca1ed4ed7","signature":"wZ6hG91YfxaZQGPvGP2fgUcsJ6jmkRDw8awxpjZTkoUiGpyeNsWSEKp4GSQWU99TzVEsuvEu1k1TLTgSeVXxSDM"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620006","transactions":[{"asset":{"data":{"definition":"Hi Lemonade"}},"id":"3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73","inputs":[{"fulfillment":"cf:4:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGjkNEOAMGZ_QIhzFgx69A-s6WbHrVMrnrqtSVyWFiQqdd9ndv5SsmvjQLEtsZBiiroxIMfBV8-gAym9ZTdzIIgO","fulfills":null,"owners_before":["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}],"metadata":null,"operation":"CREATE","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGg:96"},"public_keys":["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"c1055a4b0fdaf9cf4cd768cff2424afd2bdc8a7d77fded78d2389ebc43d06516","signature":"25Jw7xZGXkKsEzSgpyWrMiiFVto76poYsvdyrhrf8orjp1NhCnqnb7eh8WkPcGQjXQ5Pa5BhEmVGKqW58VoG34Tt"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620932","transactions":[{"asset":{"id":"1c539a8f168966d8a2d063e9f4162758a8cfceee5c8daa569d3e9c30b68c9ed3"},"id":"9727d0669ab8328baa433bff475690a5c7015d7ae7158726b97cdd3777a806f7","inputs":[{"fulfillment":"cf:4:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOe3S-4fgrf70bHefF6lf2OA861DQW_BpXnj3471BsTnMBbjf7GYdy6s0GezYEhGFhCHQDgh2bjk79eHhTMsEKgE","fulfills":{"output":0,"txid":"2b7c3ad9078c87e591e6d8e071cc4b64f37fbcdc59c032a084c99e81de639f93"},"owners_before":["79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"]}],"metadata":{"message":"fdfsdfdsf"},"operation":"TRANSFER","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOc:96"},"public_keys":["79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"fd07ad4ce3826d5653fbda67f15ce1dd127829bb8d0d03f36a4b5cad9c4c8012","signature":"58fHJwWoKSJknKmpqZhQFKeecCxDxJJoXZM7fHyBcvW9GCdrziPbhAGSvG1XCMgu3duiC83DFTHJjK23h4yS9Hvo"},{"block":{"node_pubkey":"GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4","timestamp":"1490620925","transactions":[{"asset":{"id":"1c539a8f168966d8a2d063e9f4162758a8cfceee5c8daa569d3e9c30b68c9ed3"},"id":"2b7c3ad9078c87e591e6d8e071cc4b64f37fbcdc59c032a084c99e81de639f93","inputs":[{"fulfillment":"cf:4:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOcnVT9_aoEcJM1OomXFCthHPhEP-A9FUxiikF8jmutChyOOfGHdZcte4nHPH_5VY0fOrTykgpuOzJA53h1ovUUF","fulfills":{"output":0,"txid":"1c539a8f168966d8a2d063e9f4162758a8cfceee5c8daa569d3e9c30b68c9ed3"},"owners_before":["79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"]}],"metadata":{"message":"hi"},"operation":"TRANSFER","outputs":[{"amount":1,"condition":{"details":{"bitmask":32,"public_key":"79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG","signature":null,"type":"fulfillment","type_id":4},"uri":"cc:4:20:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOc:96"},"public_keys":["79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"]}],"version":"0.9"}],"voters":["GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4"]},"id":"d1a1fdda8497799dcc37d95bebbc7e8773979c174b6c5974fe74b645ac0ec522","signature":"5aEuBydrUbXR2QfFrEwRa6hYjfGq9X4ovK2pNvpR2qSchkPW5yL48UmtWmW6ErMXVuWvZuQy9ShaXov3a8mUEgPY"}]
```

**Comment by diminator** [comment]
Querying the asset works:

```
http://localhost:49984/api/v1/transactions?asset_id=3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73
```

```
[{"outputs": [{"amount": 1, "condition": {"details": {"bitmask": 32, "type": "fulfillment", "type_id": 4, "signature": null, "public_key": "4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"}, "uri": "cc:4:20:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGg:96"}, "public_keys": ["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}], "metadata": null, "version": "0.9", "inputs": [{"fulfillment": "cf:4:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGjkNEOAMGZ_QIhzFgx69A-s6WbHrVMrnrqtSVyWFiQqdd9ndv5SsmvjQLEtsZBiiroxIMfBV8-gAym9ZTdzIIgO", "fulfills": null, "owners_before": ["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}], "id": "3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73", "asset": {"data": {"definition": "Hi Lemonade"}}, "operation": "CREATE"}, {"outputs": [{"amount": 1, "condition": {"details": {"bitmask": 32, "type": "fulfillment", "type_id": 4, "signature": null, "public_key": "AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"}, "uri": "cc:4:20:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmM:96"}, "public_keys": ["AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"]}], "metadata": {"message": "a new transaction to @bruce"}, "version": "0.9", "inputs": [{"fulfillment": "cf:4:Nv2PPvWa8H7IKemuuBxqt_ZZiC5xQzLICTYqd9eioTdi-OJQYfuWjD7xBs7oNTfLakBJnE5zNduNbzp651qDBpbvg3nd6gZLgEAJoDwjELgzWLW_tJuk3WJ3Oo6Vl2cA", "fulfills": {"txid": "6ad0a817aa0c2926572d00b5000276393c9ec098ca3795e2a58b18535f401a1a", "output": 0}, "owners_before": ["4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG"]}], "id": "6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140", "asset": {"id": "3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"}, "operation": "TRANSFER"}, {"outputs": [{"amount": 1, "condition": {"details": {"bitmask": 32, "type": "fulfillment", "type_id": 4, "signature": null, "public_key": "4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG"}, "uri": "cc:4:20:Nv2PPvWa8H7IKemuuBxqt_ZZiC5xQzLICTYqd9eioTc:96"}, "public_keys": ["4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG"]}], "metadata": {"message": "send to @dimi"}, "version": "0.9", "inputs": [{"fulfillment": "cf:4:MhDNxo4dfAJGbX9QVfi7Mh0ghfgA4H1UqGyHip7NHGiJYkx9UaihwdLCLbtdzfIhL3CNrBo95lGwNWNzcqwb7qO1rvFw2NlHYYq-kwNCOW8H9mbBBiYFLAANpYhnXAAO", "fulfills": {"txid": "3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73", "output": 0}, "owners_before": ["4NSFHRzjjQNJ6kpCkXfeUciGfCme6H1htVNLAgymJ7bu"]}], "id": "6ad0a817aa0c2926572d00b5000276393c9ec098ca3795e2a58b18535f401a1a", "asset": {"id": "3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"}, "operation": "TRANSFER"}]
```

Which includes the transaction that raises on outputs: `6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140`

Also, the GET on that transaction works:
```
http://localhost:49984/api/v1/transactions/6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140
```
```
{
"outputs": [
{
"amount": 1,
"condition": {
"details": {
"bitmask": 32,
"type": "fulfillment",
"type_id": 4,
"signature": null,
"public_key": "AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"
},
"uri": "cc:4:20:kOHgXLKCEdaS7oy71KDKTZJ-vaW8vT2sQumtv8edrmM:96"
},
"public_keys": [
"AkZUXyGrEygFF6R8vQveE2Wswkn4rSudEBuUSaV7Wiin"
]
}
],
"metadata": {
"message": "a new transaction to @bruce"
},
"version": "0.9",
"inputs": [
{
"fulfillment": "cf:4:Nv2PPvWa8H7IKemuuBxqt_ZZiC5xQzLICTYqd9eioTdi-OJQYfuWjD7xBs7oNTfLakBJnE5zNduNbzp651qDBpbvg3nd6gZLgEAJoDwjELgzWLW_tJuk3WJ3Oo6Vl2cA",
"fulfills": {
"txid": "6ad0a817aa0c2926572d00b5000276393c9ec098ca3795e2a58b18535f401a1a",
"output": 0
},
"owners_before": [
"4hfGNaQAZkwBk4maYxeAYUcuBDjkb9euQTGCi1d8QdhG"
]
}
],
"id": "6be9c0595fa4f01c59109b7cb12c9098f3bf3f1e37c49af7bc85db8b99a33140",
"asset": {
"id": "3205d467ac0ee6c129aff52124a033c0a97f670cb48a5d46a73c15712c857b73"
},
"operation": "TRANSFER"
}
```

**Comment by r-marques** [comment]
I was able to reproduce this bug.
To reproduce the bug we need to create a block with a duplicated transaction:
```python
from time import sleep

from bigchaindb import Bigchain
from bigchaindb.models import Transaction

b = Bigchain()

# create and write an asset so we have an output to spend
tx_create = Transaction.create([b.me], [([b.me], 1)]).sign([b.me_private])
b.write_transaction(tx_create)
# wait for inclusion in bigchain and voting
sleep(1)

# create a block with a duplicated transfer transaction
tx_transfer = Transaction.transfer(tx_create.to_inputs(), [([b.me], 1)],
                                   asset_id=tx_create.id).sign([b.me_private])
block = b.create_block([tx_transfer, tx_transfer])
# profit !!
b.write_block(block)
```

To check:
- are we allowing the creating of blocks with duplicated transactions in `pipelines.block.BlockPipeline.create`?
- are we incorrectly validating blocks with duplicated transactions in `pipelines.vote.Vote.validate_block`?
- is there a problem with `core.Bigchain.get_spent`
