### ISSUE TITLE
error with 'replset' on 'bigchaindb start' command

### ISSUE THREAD

**Issue by saurabh1002** [bigchaindb/bigchaindb#1477]
saurabh@saurabh-Lenovo-ideapad-500-15ISK:~$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/saurabh/.bigchaindb`
[2017-05-16 20:56:30] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 0.10.1 (MainProcess - pid: 8693)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 147, in _check_replica_set
    repl_opts = options['parsed']['replication']
KeyError: 'replication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==0.10.1', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 348, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 204, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 49, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 76, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 199, in run_start
    _run_init()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 138, in _run_init
    schema.init_database(connection=b.connection)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/schema.py", line 99, in init_database
    create_database(connection, dbname)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/schema.py", line 19, in create_database
    if dbname in conn.conn.database_names():
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/connection.py", line 111, in conn
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/connection.py", line 142, in connect
    self._conn = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 78, in _connect
    self.dbname, self.ssl, self.login, self.password)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 114, in initialize_replica_set
    _check_replica_set(conn)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 150, in _check_replica_set
    raise ConfigurationError('mongod was not started with'
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.

**Comment by ttmc** [comment]
@saurabh1002 Before doing `bigchaindb start`, did you start MongoDB using a command-line command such as:
```bash
mongod --replSet=bigchain-rs
```
That's the command suggested in the [BigchainDB Server Quickstart page](https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html). The `replSet` option gives a name to the MongoDB replica set. BigchainDB assumes a replica set name of `bigchain-rs` by default. You can find [all the `mongod` command-line options in the MongoDB docs](https://docs.mongodb.com/manual/reference/program/mongod/).

**Comment by ttmc** [comment]
@saurabh1002 I'm going to close this issue for now, but feel free to comment on it or open a new issue if you're still having problems. Include the string `@ttmc` to make sure that I see it. - Troy
