### ISSUE TITLE
Multiple voting error

### ISSUE THREAD

**Issue by MindFK** [bigchaindb/bigchaindb#1499]
Hello, i use ubuntu xenial 16.04 and bigchaindb server 0.95 this is the content of my config file 
INFO:bigchaindb.config_utils:Configuration loaded from `/root/.bigchaindb`
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "rethinkdb",
        "host": "10.215.66.70",
        "name": "bigchain",
        "port": 28015
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "Df5AQK6GRYe9CfjC7ujgWdUX7GUMf9sgo3mMtPgp38Cs"
    },
    "keyring": [],
    "server": {
        "bind": "10.215.66.70:9984",
        "threads": null,
        "workers": null
    }
}
and database such rethinkdb, i use correcly for one month but when i restart the service i have this problem
and this is the full error

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/web/views/outputs.py", line 26, in get
    include_spent)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 432, in get_outputs_filtered
    outputs = self.get_outputs(owner)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 393, in get_outputs
    validity = self.get_blocks_status_containing_tx(tx['id'])
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 301, in get_blocks_status_containing_tx
    ) for block in blocks
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 301, in <dictcomp>
    ) for block in blocks
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 629, in block_election_status
    .format(block_id=block_id, n_votes=str(voter_counts[node]), node_id=node))
bigchaindb.common.exceptions.MultipleVotesError: Block 762b50a6b438469bfc481b8e65d025ec5a349272fc214ef692699aa8cece456c has multiple votes (2) from voting node D9EsBd5XRMc8b4zv7TaWJzADRdAtGhkyAF3RYddQ6jNt

**Comment by libscott** [comment]
Hi @MindFK,

We made alot of changes to this code for 0.10. We aren't supporting this version of BigchainDB anymore, best thing is to run the current patch release ie 0.10.2 and use MongoDB as a database, that way you will get all fixes as fast as possible.

Best

**Comment by ttmc** [comment]
BigchainDB 2.0 doesn't do voting any more (because Tendermint does) so this issue is gone.
