### ISSUE TITLE
Invalid transaction schema

### ISSUE THREAD

**Issue by lwyeluo** [bigchaindb/bigchaindb#1579]
Hi all, I am running the example code:

```
import bigchaindb_driver
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
from time import sleep
from sys import exit
import sys

alice, bob = generate_keypair(), generate_keypair()

bdb = BigchainDB('http://127.0.0.1:9984')

bicycle_asset = {
    'data': {
        'bicycle': {
            'serial_number': 'abcd1234',
            'manufacturer': 'bkfab'
        },
    },
}

bicycle_asset_metadata = {
    'planet': 'earth'
}

prepared_creation_tx = bdb.transactions.prepare(
    operation='CREATE',
    signers=alice.public_key,
    asset=bicycle_asset,
    metadata=bicycle_asset_metadata
)

fulfilled_creation_tx = bdb.transactions.fulfill(
    prepared_creation_tx,
    private_keys=alice.private_key
)

sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
```

and I have got an error:

```
Traceback (most recent call last):
  File "/root/PycharmProjects/bigchaindb/api/bigchainAPI.py", line 39, in <module>
    sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb_driver/driver.py", line 311, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.BadRequest: (400, '{\n  "message": "Invalid transaction schema: \'1\' is not of type \'integer\'", \n  "status": 400\n}\n', {'status': 400, 'message': "Invalid transaction schema: '1' is not of type 'integer'"})
```

Please help me, thanks.

**Comment by r-marques** [comment]
Hi @lwyeluo 

What version of BigchainDB are you using?
This example should work with `bighchaindb==0.10.2`.

We introduced breaking changes in master and now in the process of doing a new release with updated server, drivers and documentation

**Comment by lwyeluo** [comment]
Thanks for your reply. My bigchainDB's version is `BigchainDB (0.11.0.dev0)`.

This error has been disappeared after I dropped the database in Mongo and restarted the bigchaindb. I do not know why it is. But it seems to be solved.

**Comment by NasimShourav** [comment]
@lwyeluo 
How did you restart bigchainbd if you dropped Mongo. When I tried to do the same I got  **File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/connection.py", line 160, in connect
    raise ConnectionError() from exc
bigchaindb.backend.exceptions.ConnectionError** error. 

I am also getting the same error you faced. Do you know how to solve this?
