### ISSUE TITLE
BigchainDB sometimes freezing, requiring restart?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1688]
Yesterday @xfaldik reported a problem where, "After several refused transactions (Unvalidated) bigchain freeze and is necessary to restart bigchaindb service, has anyone same problem?"

@ferOnti reported having a similar issue.

See https://gitter.im/bigchaindb/bigchaindb?at=5970c2354bcd78af56cc0081

![screenshot from 2017-07-21 10-28-53](https://user-images.githubusercontent.com/1210951/28455727-4db9167c-6e00-11e7-866b-d9944d88b9ad.png)

@xfaldik and @ferOnti (or anyone else), can you help us reproduce this issue?

* What hardware (or VM) are you running on (RAM, number of cores, etc.)?
* What operating system are you running BigchainDB Server on?
* Are you using Docker?
* What version of BigchainDB Server?
* What's are your BigchainDB Server config settings? For example, are you using MongoDB or RethinkDB? You can get the values of all the settings by using the command:

```bash
$ bigchaindb show-config
```

**Comment by ferOnti** [comment]
Hi, I take the time to review the logs, and seems that my specific issue is related to mongodb replication, 

below are my findings :

I have two servers with bigchaindb version 1.0.0, each one has a mongodb server

## bigchaindb --version
bigchaindb 1.0.0

## bigchaindb show-config

INFO:bigchaindb.config_utils:Configuration loaded from `/root/.bigchaindb`
```
{
    "backlog_reassign_delay": 80,
    "database": {
        "backend": "mongodb",
        "ca_cert": null,
        "certfile": null,
        "connection_timeout": 5000,
        "crlfile": null,
        "host": "localhost",
        "keyfile": null,
        "keyfile_passphrase": null,
        "login": null,
        "max_tries": 3,
        "name": "bigchain",
        "password": null,
        "port": 27017,
        "replicaset": "bigchain-rs",
        "ssl": false
    },
    "graphite": {
        "host": "localhost"
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "291FETFux2fzfWpYcsjy7ueZj6c4v8Yir5NJJu5MFcqC"
    },
    "keyring": [
        "En9DkSdG8C7xiWuYGhAtuNrQYrUWyxfeG3ja3E6crw6D"
    ],
    "log": {
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
        "error_file": "/root/bigchaindb-errors.log",
        "file": "/root/bigchaindb.log",
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "granular_levels": {},
        "level_console": "INFO",
        "level_logfile": "INFO"
    },
    "server": {
        "bind": "0.0.0.0:9984",
        "loglevel": "INFO",
        "workers": null
    },
    "wsserver": {
        "host": "0.0.0.0",
        "port": 9985,
        "scheme": "ws"
    }
}

```

## First Sever - bigchaindb log

this is the log, when the first server stop responding, this server is set as PRIMARY mongodb:

**[2017-07-17 20:00:08] [ERROR]** (bigchaindb.backend.mongodb.changefeed) Lost connection while tailing oplog, retrying (Process-13 - pid: 16869)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 450, in receive_message
    self.sock, operation, request_id, self.max_message_size)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 137, in receive_message
    header = _receive_data_on_socket(sock, 16)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 164, in _receive_data_on_socket
    chunk = sock.recv(length)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/changefeed.py", line 103, in run_changefeed
    record = cursor.next()
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1056, in _refresh
    self.__max_await_time_ms))
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/server.py", line 136, in send_message_with_response
    response_data = sock_info.receive_message(1, request_id)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 452, in receive_message
    self._raise_connection_failure(error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 550, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 211, in _raise_connection_failure
    raise AutoReconnect(msg)
pymongo.errors.AutoReconnect: 13.82.50.105:27017: [Errno 104] Connection reset by peer
**[2017-07-17 20:12:10] [ERROR]** (bigchaindb.backend.mongodb.changefeed) Lost connection while tailing oplog, retrying (Process-18 - pid: 16887)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 450, in receive_message
    self.sock, operation, request_id, self.max_message_size)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 137, in receive_message
    header = _receive_data_on_socket(sock, 16)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 164, in _receive_data_on_socket
    chunk = sock.recv(length)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/changefeed.py", line 103, in run_changefeed
    record = cursor.next()
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1056, in _refresh
    self.__max_await_time_ms))
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 905, in _send_message_with_response
    exhaust)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 916, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/server.py", line 136, in send_message_with_response
    response_data = sock_info.receive_message(1, request_id)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 452, in receive_message
    self._raise_connection_failure(error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 550, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 211, in _raise_connection_failure
    raise AutoReconnect(msg)
pymongo.errors.AutoReconnect: 13.82.50.105:27017: [Errno 110] Connection timed out



## Second Sever - bigchaindb log

**[2017-07-17 19:58:48] [ERROR]** (bigchaindb.backend.mongodb.changefeed) Lost connection while tailing oplog, retrying (Process-19 - pid: 24174)
Traceback (most recent call last):
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/bigchaindb/backend/mongodb/changefeed.py", line 103, in run_changefeed
    record = cursor.next()
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/pymongo/cursor.py", line 873, in __send_message
    **kwargs)
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/pymongo/mongo_client.py", line 888, in _send_message_with_response
    server = topology.select_server(selector)
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/root/miniconda2/envs/python3/lib/python3.6/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()"

## Second Server - mongodb log
2017-07-18T17:40:29.249+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 45.55.151.98:27017
2017-07-18T17:40:29.265+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 45.55.151.98:27017, took 16ms (3 connections now open to 45.55.151.98:27017)
2017-07-18T17:41:29.259+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host 45.55.151.98:27017 because the pool meets constraints; 2 connections to that host remain open
2017-07-18T17:46:29.259+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 45.55.151.98:27017
2017-07-18T17:46:29.276+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 45.55.151.98:27017, took 17ms (3 connections now open to 45.55.151.98:27017)
2017-07-18T17:47:29.267+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host 45.55.151.98:27017 because the pool meets constraints; 2 connections to that host remain open

## First Server - mongodb.log

2017-07-17T19:58:48.299+0000 I REPL     [ReplicationExecutor] Member 13.82.50.105:27017 is now in state SECONDARY
2017-07-17T19:58:48.826+0000 I REPL     [rsBackgroundSync] sync source candidate: 13.82.50.105:27017
2017-07-17T19:58:48.826+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to 13.82.50.105:27017
2017-07-17T19:58:48.843+0000 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to 13.82.50.105:27017, took 17ms (2 connections now open to 13.82.50.105:27017)
2017-07-17T19:58:48.850+0000 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-07-17T19:58:48.850+0000 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-07-17T19:58:48.859+0000 I REPL     [ReplicationExecutor] VoteRequester(term 7 dry run) received a no vote from 13.82.50.105:27017 with reason "candidate's data is staler than mine"; response message: { term: 7, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-07-17T19:58:48.859+0000 I REPL     [ReplicationExecutor] not running for primary, we received insufficient votes
2017-07-17T19:58:48.871+0000 I REPL     [replication-884] Choosing new sync source because our current sync source, 13.82.50.105:27017, has an OpTime ({ ts: Timestamp 1500321400000|1, t: 7 }) which is not ahead of ours ({ ts: Timestamp 1500321400000|1, t: 7 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-07-17T19:58:48.871+0000 I REPL     [replication-884] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: 13.82.50.105:27017, OpTime { ts: Timestamp 1500321400000|1, t: 7 }, its sync source index:-1
2017-07-17T19:58:48.871+0000 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source 13.82.50.105:27017 (config version: 5; last applied optime: { ts: Timestamp 1500321400000|1, t: 7 }; sync source index: -1; primary index: -1) is no longer valid
2017-07-17T19:58:48.871+0000 I REPL     [rsBackgroundSync] could not find member to sync from

**Comment by krish7919** [comment]
@ferOnti : Thanks for the detailed logs.
At first glance, it seems that MongoDB cannot elect a primary.
Can you try with a 3 node federation, meaning 3 MongoDB instances in a replica set, which would result in a majority vote and get us an elected PRIMARY?

```
2017-07-17T19:58:48.850+0000 I REPL [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-07-17T19:58:48.850+0000 I REPL [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-07-17T19:58:48.859+0000 I REPL [ReplicationExecutor] VoteRequester(term 7 dry run) received a no vote from 13.82.50.105:27017 with reason "candidate's data is staler than mine"; response message: { term: 7, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-07-17T19:58:48.859+0000 I REPL [ReplicationExecutor] not running for primary, we received insufficient votes
```

Also, since the pymongo driver connects to the primary, a lack of primary forces a disconnection:
`pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()"`

**Comment by ttmc** [comment]
I think the best way to resolve this issue would be to have prominent documentation, in several places, to make it clear that _a multi-node setup must have three or more nodes_ (with links to explain why; see above).

**Comment by xfaldik** [comment]
Hi, I think that my problem is quite different.
My configuration is singe node: VM Ubuntu (3800MB RAM, 1 CORE), MongoDB.

# bigchaindb --version
bigchaindb 010.2

# bigchaindb show-config
`{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "connection_timeout": 5000,
        "host": "localhost",
        "login": null,
        "max_tries": 3,
        "name": "bigchain",
        "password": null,
        "port": 27017,
        "replicaset": "bigchain-rs",
        "ssl": false
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "5o3orhdu5dgwN1FjVYVpUUiMd2ThTLjGxFpPvqEizR1S"
    },
    "keyring": [],
    "log": {
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
        "error_file": "/home/z003sb6a/bigchaindb-errors.log",
        "file": "/home/z003sb6a/bigchaindb.log",
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "granular_levels": {},
        "level_console": "INFO",
        "level_logfile": "INFO"
    },
    "server": {
        "bind": "localhost:9984",
        "loglevel": "INFO",
        "threads": null,
        "workers": null
    },
    "wsserver": {
        "host": "localhost",
        "port": 9985
    }
}
`
# The problem

After the Bigchaindb service invalidate for example 10 transactions (it raises exception that transaction was refused), the Bigchaindb service freeze on the last invalidate transaction:

`[2017-07-24 10:46:08,947] ERROR in app: Exception on /api/v1/transactions/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/web/views/transactions.py", line 80, in post
    bigchain.validate_transaction(tx_obj)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/core.py", line 157, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/consensus.py", line 18, in validate_transaction
    raise ValueError("INVALID TX")
ValueError: INVALID TX
[2017-07-24 10:55:57] [INFO] (gunicorn.error) Handling signal: winch (webapi     - pid: 3975)
`

**Comment by ttmc** [comment]
Note: I moved the comment from @xfaldik to a new issue: #1695

**Comment by ttmc** [comment]
BigchainDB Server could also fail with an error message if the user tries to connect to a two-node MongoDB cluster, explaining why that won't work.

We should also consider what BigchainDB Server should say to users connecting to a MongoDB cluster with an even number of nodes. A warning? An error?

What should a BigchainDB cluster do if it has an odd number of nodes, but then one crashes?
