### ISSUE TITLE
User-Reported Problem Running Single Node with MongoDB

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1695]
The following problem was reported by @xfaldik

<hr>

Hi, I think that my problem is quite different.
My configuration is singe node: VM Ubuntu (3800MB RAM, 1 CORE), MongoDB.

# bigchaindb --version
bigchaindb 0.10.2

# bigchaindb show-config

```json
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "connection_timeout": 5000,
        "host": "localhost",
        "login": null,
        "max_tries": 3,
        "name": "bigchain",
        "password": null,
        "port": 27017,
        "replicaset": "bigchain-rs",
        "ssl": false
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "5o3orhdu5dgwN1FjVYVpUUiMd2ThTLjGxFpPvqEizR1S"
    },
    "keyring": [],
    "log": {
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
        "error_file": "/home/z003sb6a/bigchaindb-errors.log",
        "file": "/home/z003sb6a/bigchaindb.log",
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "granular_levels": {},
        "level_console": "INFO",
        "level_logfile": "INFO"
    },
    "server": {
        "bind": "localhost:9984",
        "loglevel": "INFO",
        "threads": null,
        "workers": null
    },
    "wsserver": {
        "host": "localhost",
        "port": 9985
    }
}
```

# The problem

After the Bigchaindb service invalidate for example 10 transactions (it raises exception that transaction was refused), the Bigchaindb service freeze on the last invalidate transaction:

```bash
[2017-07-24 10:46:08,947] ERROR in app: Exception on /api/v1/transactions/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/web/views/transactions.py", line 80, in post
    bigchain.validate_transaction(tx_obj)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/core.py", line 157, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/consensus.py", line 18, in validate_transaction
    raise ValueError("INVALID TX")
ValueError: INVALID TX
[2017-07-24 10:55:57] [INFO] (gunicorn.error) Handling signal: winch (webapi     - pid: 3975)
```

**Comment by ttmc** [comment]
@xfaldik It seems like you sent an invalid transaction to BigchainDB Server 0.10.2.

I suspect you're generating a transaction using one of the latest drivers (which generates a transaction compatible with BigchainDB Server 1.0.x), but you're posting it to BigchainDB Server 0.10.2. The transaction model changed between 0.10.2 and 1.0.0 so transactions that are valid for 1.0.x aren't valid for 0.10.2.

Can you show us the transaction (JSON) that you posted?

**Comment by xfaldik** [comment]
Hi, thanks for the reply. I would like to clarify the problem. In my case it is normal that my consensus rules refuse for example 10 transactions - it could happened in my scenario. What is strange is that the Bigchaindb service freeze after 10th refused transaction. I will send you JSON transaction in a few minutes.

**Comment by ttmc** [comment]
This issue arose with a now-unsupported version of BigchainDB (v0.10.2), so I'm closing it.
