### ISSUE TITLE
Transaction should allow the '.' character

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1702]
@TimDaub's request with the node driver failed with response code 500, and a look at BigchainDB logs revealed the following stacktrace:

```
[2017-07-27 12:34:36,869] ERROR in app: Exception on /api/v1/transactions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/web/views/transactions.py", line 88, in post
    bigchain.write_transaction(tx_obj)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/core.py", line 106, in write_transaction
    return backend.query.write_transaction(self.connection, signed_transaction)
  File "/usr/local/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/backend/mongodb/query.py", line 24, in write_transaction
    .insert_one(signed_transaction))
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/backend/mongodb/connection.py", line 62, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/utils.py", line 175, in run
    last = last(*item[0], **item[1])
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 657, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 562, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 543, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 424, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 552, in _raise_connection_failure
    raise error
  File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 94, in command
    None, codec_options, check_keys)
bson.errors.InvalidDocument: key 'Track no.' must not contain '.'
```

**Comment by TimDaub** [comment]
FYI, the asset data I submitted looked like this (there were other k-vs as well):

```json
{
  "Track no.": 1
}
```

**Comment by krish7919** [comment]
@TimDaub Seems to be a MongoDB constraint: https://docs.mongodb.com/manual/reference/limits/#naming-restrictions

**Comment by sbellem** [comment]
@TimDaub @r-marques @vrde @ttmc any idea/suggestions on how to handle this?

**Comment by ttmc** [comment]
One obvious solution is to add more constraints to the definition of what it means for a BigchainDB transaction to be valid. This is similar to the "language" key issue #1670

**Comment by sbellem** [comment]
> One obvious solution is to add more constraints to the definition of what it means for a BigchainDB transaction to be valid.

yes, I was thinking the same

**Comment by kansi** [comment]
@ttmc @sbellem I think we can solve this and #1670  by adding `patternProperties` to the to `data` object ?
```yaml
      data:
        description: |
          User provided metadata associated with the asset. May also be ``null``.
        anyOf:
        - type: object
          additionalProperties: true
          patternProperties:
            language:
              type: string
              enum:
                - english
                - french
                - german
            "^[^\\$][^.]":
              type : {}
        - type: 'null'
```

**Comment by ttmc** [comment]
@kansi I guess that would restrict `asset.data.language` to one of the enumerated allowed values, in the schema validation stage. That seems okay.

I don't understand the bit with `"^[^\\$][^.]":` and `type : {}`. Does that disallow a $ or . in field names, at the schema-validation stage? What about disallowing null characters? What is the `type: {}` line for?

**Comment by kansi** [comment]
@ttmc You are right `"^[^\\$][^.]"` disallows `$` as the first character of the key and also restricts `.` in the whole key name. The regex is written to complay with the [field naming restrictions](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names) but we can surely include more characters. Please let me know the same or point me to bdb docs? Also, type `{}` is to [allow any type](https://spacetelescope.github.io/understanding-json-schema/basics.html#hello-world) in the value.

**Comment by ttmc** [comment]
@kansi I would add a comment to the YAML file to explain what that means in-context.

Let's resolve issues #1670 and this one (#1702) in two separate PRs. We try to keep PRs focused (but sometimes fail).

Note how null characters are not allowed in field names.

**Comment by kansi** [comment]
@ttmc  Sure, I will resolve them in seperate pull requests.

**Comment by kansi** [comment]
@ttmc Based on the discussion in #1670 I have created a pull request for this issue which fixes  this problem at an API level (for v1.x)
