### ISSUE TITLE
Bug: `500` on asset search

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#1716]
`'http://localhost:49984/api/v1/assets?search=myassetvalue'`

sometimes gives me

```
[2017-08-08 15:49:22,910] ERROR in app: Exception on /api/v1/assets [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/app/bigchaindb/web/views/assets.py", line 45, in get
    return list(assets)
  File "/usr/src/app/bigchaindb/core.py", line 647, in text_search
    for asset in assets:
  File "/usr/src/app/bigchaindb/backend/mongodb/query.py", line 366, in <genexpr>
    return (_remove_text_score(asset) for asset in cursor)
  File "/usr/local/lib/python3.5/site-packages/pymongo/cursor.py", line 1114, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.5/site-packages/pymongo/cursor.py", line 1036, in _refresh
    self.__collation))
  File "/usr/local/lib/python3.5/site-packages/pymongo/cursor.py", line 928, in __send_message
    helpers._check_command_response(doc['data'][0])
  File "/usr/local/lib/python3.5/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: text index required for $text query
```

**Comment by diminator** [comment]
reinitializing the DB solves it...
Maybe this needs a safeguard?

**Comment by kansi** [comment]
@diminator towards the end of the error message it says `text index required for $text query` which would mean that there was an issue during db setup while creating indexes? But if the db is initialized properly this issue would never come up?

**Comment by r-marques** [comment]
Agree with @kansi. @diminator is this still an issue or can we close this?

**Comment by r-marques** [comment]
Closing this. Will re open if needed.
