### ISSUE TITLE
Can not run bigchaindb after installation

### ISSUE THREAD

**Issue by Gelembjuk** [bigchaindb/bigchaindb#1756]
I have installed the bigchaindb on my Ubuntu 16.04
using the guide https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html

During installation all seems worked fin, i didn't see any error messages 

But when i run

`$ bigchaindb start` 

I see some error

INFO:bigchaindb.config_utils:Configuration loaded from `/home/roman/.bigchaindb`
[2017-09-22 20:54:01] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.0.1 (MainProcess - pid: 13174)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 235, in _check_replica_set
    repl_opts = options['parsed']['replication']
KeyError: 'replication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==1.0.1', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 348, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 204, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 49, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 76, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 199, in run_start
    _run_init()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 138, in _run_init
    schema.init_database(connection=b.connection)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/schema.py", line 99, in init_database
    create_database(connection, dbname)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/schema.py", line 19, in create_database
    if dbname in conn.conn.database_names():
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/connection.py", line 122, in conn
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/connection.py", line 153, in connect
    self._conn = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 101, in _connect
    self.crlfile)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 198, in initialize_replica_set
    _check_replica_set(conn)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 238, in _check_replica_set
    raise ConfigurationError('mongod was not started with'
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.

And it seems the server is not started

curl http://localhost:9984
curl: (7) Failed to connect to localhost port 9984: Connection refused

What did i do wrong?

**Comment by muawiakh** [comment]
Can you share the command you used to initialize MongoDB? Also can you paste the `.bigchaindb` configuration file?

By the looks of it, the MongoDB instance was not initialized with a `--replSet` flag. But I just want to make sure, everything is in place.

**Comment by ttmc** [comment]
@Gelembjuk The latest version of the Quickstart page clarifies many steps. It got published as the "latest' when we released BigchaindB version 1.1 yesterday. Maybe try going through it again.

https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html

**Comment by Gelembjuk** [comment]
Thanks. It works now.
I restarted mongodb with the flag --replSet 
I will continue my experiments
