### ISSUE TITLE
benchmark.yml missing

### ISSUE THREAD

**Issue by zopyx** [bigchaindb/bigchaindb#1778]
create_thoughtput.py refers to benchmark.yml which is not available in the repository.

**Comment by ttmc** [comment]
It looks like `benchmark.yml` got renamed as `docker-compose.benchmark.yml` in this commit:

https://github.com/bigchaindb/bigchaindb/commit/4e2423c3deda20a6809533111df2030a263f78ee

@sbellem To fix this issue, would it be enough to rename `benchmark.yml` to `docker-compose.benchmark.yml` in the file `create_thoughtput.py`?

https://github.com/bigchaindb/bigchaindb/blob/master/scripts/benchmarks/create_thoughtput.py

**Comment by sbellem** [comment]
That seems to be sufficient, yes. Best thing is to try.

**Comment by ttmc** [comment]
I just gave it a try. I changed the five instances of `benchmark.yml` to `docker-compose.benchmark.yml` in `create_throughput.py` and then ran it as per the instructions in https://github.com/bigchaindb/bigchaindb/blob/master/scripts/benchmarks/README.md

* Python 3.5.2
* docker-compose version 1.13.0
* docker version 17.09.0-ce

```text
$ python scripts/benchmarks/create_thoughtput.py
bigchaindb_mdb_1 is up-to-date
bigchaindb_bdb_1 is up-to-date
bigchaindb_graphite_1 is up-to-date
Graphite web interface at: http://localhost:32775/
```

Then it appeared to hang. When I visited http://localhost:32775/ in my browser, there was a Graphite dashboard, but the graph said "No Data". When I did a CTRL+C, I got this:
```text
^CWaiting for server to start... Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2e4cd37748>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9984): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e4cd37748>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/benchmarks/create_thoughtput.py", line 46, in wait_for_up
    requests.get('http://localhost:9984/')
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9984): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e4cd37748>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/benchmarks/create_thoughtput.py", line 131, in <module>
    load()
  File "scripts/benchmarks/create_thoughtput.py", line 67, in load
    wait_for_up()
  File "scripts/benchmarks/create_thoughtput.py", line 49, in wait_for_up
    time.sleep(0.1)
KeyboardInterrupt
Traceback (most recent call last):
  File "scripts/benchmarks/create_thoughtput.py", line 133, in <module>
    main()
  File "scripts/benchmarks/create_thoughtput.py", line 20, in main
    cmd('docker-compose -f docker-compose.yml -f docker-compose.benchmark.yml exec bdb python %s load' % sys.argv[0])
  File "scripts/benchmarks/create_thoughtput.py", line 126, in cmd
    assert not proc.wait()
AssertionError
```

**Comment by ttmc** [comment]
We got rid of all that old benchmarking code etc. when creating the BigchainDB 2.x series, so this issue is defunct.

Note: We are doing new benchmarking tests right now, and will share the code + results once we have them ready.
