### ISSUE TITLE
Error found while sending over a transaction to a BigchainDB node

### ISSUE THREAD

**Issue by rivthebest** [bigchaindb/bigchaindb#1836]
* BigchainDB version: 1.0.1
* Operating System: MacOS High Sierra version 10.13.1
* Deployment Type: `[Docker|Host|IPDB|Other]`
  * If you are using IPDB, please specify your network type `[test, prod]`
  and the `bdb_url(BigchainDB URL)` you are using.
  * For every other type of deployment, please specify the documentation/instructions
  you are following. 
The document is followed as: https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html
It is for the localhost deployment.
* BigchainDB driver: `[yes|no]` Yes
  * If using a driver please specify, driver type `[python|js|java]`: Python driver named: bigchaindb_driver
  and version.

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I was trying to send over a transaction to a BigchainDB node by issuing the following steps mentioned in the document

Document: https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html

All the steps prior to execution of the mentioned steps in the above have been followed exactly as is

Step executed: 
```text
>>> sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
```

### Error Found

```text
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1716, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1449, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=9984): Max retries exceeded with url: /api/v1/transactions/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bigchaindb_driver/driver.py", line 319, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bigchaindb_driver/connection.py", line 48, in request
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=9984): Max retries exceeded with url: /api/v1/transactions/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
>>> 
```

#### What I Did

Python version used: 3.5
libffi installed version 3.2.1
OpenSSL: 
OpenSSL 1.0.2m  2 Nov 2017
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"

mongodb version 3.4
BigchainDB version 1.0.1

### For MongoDB

```text
mongod --dbpath ~/Documents/Database/MONGODB/mongodb-osx-x86_64-3.4.10/datastore/bigchaindb_data/ --replSet=bigchain-rs
2017-11-12T18:27:56.212+0530 I CONTROL  [initandlisten] MongoDB starting : pid=9517 port=27017 dbpath=/Users/rivthebest/Documents/Database/MONGODB/mongodb-osx-x86_64-3.4.10/datastore/bigchaindb_data/ 64-bit host=Ritabratas-MacBook.local
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] db version v3.4.10
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] allocator: system
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] modules: none
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] build environment:
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten]     distarch: x86_64
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten]     target_arch: x86_64
2017-11-12T18:27:56.213+0530 I CONTROL  [initandlisten] options: { replication: { replSet: "bigchain-rs" }, storage: { dbPath: "/Users/rivthebest/Documents/Database/MONGODB/mongodb-osx-x86_64-3.4.10/datastore/bigchaindb_data/" } }
2017-11-12T18:27:56.217+0530 I -        [initandlisten] Detected data files in /Users/rivthebest/Documents/Database/MONGODB/mongodb-osx-x86_64-3.4.10/datastore/bigchaindb_data/ created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-11-12T18:27:56.217+0530 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3584M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-11-12T18:27:58.898+0530 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-11-12T18:27:58.898+0530 I STORAGE  [initandlisten] The size storer reports that the oplog contains 7185 records totaling to 692470 bytes
2017-11-12T18:27:58.898+0530 I STORAGE  [initandlisten] Sampling from the oplog between Nov 10 13:05:50:1 and Nov 12 11:43:46:1 to determine where to place markers for truncation
2017-11-12T18:27:58.898+0530 I STORAGE  [initandlisten] Taking 0 samples and assuming that each section of oplog contains approximately 189905 records totaling to 18302507 bytes
2017-11-12T18:27:58.933+0530 I CONTROL  [initandlisten] 
2017-11-12T18:27:58.933+0530 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-12T18:27:58.933+0530 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-12T18:27:58.933+0530 I CONTROL  [initandlisten] 
2017-11-12T18:27:58.933+0530 I CONTROL  [initandlisten] 
2017-11-12T18:27:58.933+0530 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
2017-11-12T18:27:58.950+0530 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/Users/rivthebest/Documents/Database/MONGODB/mongodb-osx-x86_64-3.4.10/datastore/bigchaindb_data/diagnostic.data'
2017-11-12T18:27:58.954+0530 I NETWORK  [thread1] waiting for connections on port 27017
2017-11-12T18:27:58.956+0530 I REPL     [replExecDBWorker-0] New replica set config in use: { _id: "bigchain-rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a0556d5f16b288fbe2ff90f') } }
2017-11-12T18:27:58.956+0530 I REPL     [replExecDBWorker-0] This node is localhost:27017 in the config
2017-11-12T18:27:58.956+0530 I REPL     [replExecDBWorker-0] transition to STARTUP2
2017-11-12T18:27:58.956+0530 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-11-12T18:27:58.957+0530 I REPL     [replExecDBWorker-0] Starting replication fetcher thread
2017-11-12T18:27:58.957+0530 I REPL     [replExecDBWorker-0] Starting replication applier thread
2017-11-12T18:27:58.957+0530 I REPL     [replExecDBWorker-0] Starting replication reporter thread
2017-11-12T18:27:58.957+0530 I REPL     [rsSync] transition to RECOVERING
2017-11-12T18:27:58.960+0530 I REPL     [rsSync] transition to SECONDARY
2017-11-12T18:27:58.960+0530 I REPL     [rsSync] conducting a dry run election to see if we could be elected
2017-11-12T18:27:58.960+0530 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-11-12T18:27:59.008+0530 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 2
2017-11-12T18:27:59.008+0530 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-11-12T18:27:59.008+0530 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-11-12T18:27:59.008+0530 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-11-12T18:28:00.968+0530 I REPL     [rsSync] transition to primary complete; database writes are now permitted
```

### For BigchainDB

```bash
Ritabratas-MacBook:BULK_IMPORT rivthebest$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/Users/rivthebest/.bigchaindb`
[2017-11-12 18:29:10] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.0.1 (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process with public key GaoUzUsa2MTTecrPEVe3VRCuRYcd7oWHjCXg1UM7wUkB (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) Initializing BigchainDB... (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) Starting block (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) Starting voter (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-10 - pid: 9522)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-10 - pid: 9522)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-19 - pid: 9531)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) Starting stale transaction monitor (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) Starting election (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-24 - pid: 9542)
[2017-11-12 18:29:10] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-24 - pid: 9542)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) WebSocket server started (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (bigchaindb.processes) 
****************************************************************************
*                                                                          *
*   Initialization complete. BigchainDB Server is ready and waiting.       *
*   You can send HTTP requests via the HTTP API documented in the          *
*   BigchainDB Server docs at:                                             *
*    https://bigchaindb.com/http-api                                       *
*                                                                          *
*   Listening to client connections on: localhost:9984                     *
*                                                                          *
****************************************************************************
 (MainProcess - pid: 9518)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Starting gunicorn 19.7.1 (webapi     - pid: 9545)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Listening at: http://127.0.0.1:9984 (9545) (webapi     - pid: 9545)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Using worker: sync (webapi     - pid: 9545)
======== Running on http://localhost:9985 ========
(Press CTRL+C to quit)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Booting worker with pid: 9547 (webapi     - pid: 9547)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Booting worker with pid: 9548 (webapi     - pid: 9548)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Booting worker with pid: 9549 (webapi     - pid: 9549)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Booting worker with pid: 9550 (webapi     - pid: 9550)
[2017-11-12 18:29:10] [INFO] (gunicorn.error) Booting worker with pid: 9551 (webapi     - pid: 9551)
[2017-11-12 18:29:11] [INFO] (gunicorn.error) Booting worker with pid: 9552 (webapi     - pid: 9552)
[2017-11-12 18:29:11] [INFO] (gunicorn.error) Booting worker with pid: 9553 (webapi     - pid: 9553)
[2017-11-12 18:29:11] [INFO] (gunicorn.error) Booting worker with pid: 9554 (webapi     - pid: 9554)
[2017-11-12 18:29:11] [INFO] (gunicorn.error) Booting worker with pid: 9555 (webapi     - pid: 9555)
[2017-11-12 18:29:15] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-20 - pid: 9540)
```

Please let me know is there anything essential part I am missing to execute the mentioned step. Probably it could be an old issue but I am quite new to BigchainDB environment. Please advise me.

**Comment by ttmc** [comment]
I'm not _sure_ what went wrong, but a couple of things came to mind as I looked through your report:

- We don't test BigchainDB Server (i.e. `bigchaindb`) on Mac OS X (or macOS) and it's known to have problems running on Macs. Maybe try it our in a virtual machine running Ubuntu 14.04. (Docker is another option, but Docker on Mac has its own annoying quirks...)
- I see that you were running BigchainDB version 1.0.1. The latest version of BigchainDB Server is 1.2 (and before that it was 1.1). You can update it using `pip install --upgrade bigchaindb`

**Comment by rivthebest** [comment]
Thanks Troy.... I had updated the version of BigchainDB to 1.2 and repeated the steps mentioned earlier and could be able to see the transaction posted. thanks a lot. I am also suspecting I might have done something wrong earlier in the bdb_root_url where I might have given https instead of http. Anyway the problem resolved. One last thing..... I had configured mongodb with BigchainDB and if I would like to see the collection in the MongoDB after posting it through BigchainDB so is it possible to view that. Here is the current scenario happening for me....

The valid transaction I had posted using BigchainDB is:

>>> from bigchaindb_driver.crypto import generate_keypair
>>> alice, bob = generate_keypair(), generate_keypair()
>>> 
>>> prepared_creation_tx = bdb.transactions.prepare(
...             operation='CREATE',
...             signers=alice.public_key,
...             asset=bicycle,
...             metadata=metadata,
...     )
>>> 
>>> prepared_creation_tx
{'id': 'fd76ef2b1ce79eb65e4b307eaaf3151d9ed1cfd71eb2ed871321366956d27f82', 'inputs': [{'fulfills': None, 'fulfillment': {'type': 'ed25519-sha-256', 'public_key': 'HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS'}, 'owners_before': ['HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS']}], 'outputs': [{'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS'}, 'uri': 'ni:///sha-256;7wR_qGs435-inEw7OVZ9k_qcN4wz8Fjciru-BCdH_8s?fpt=ed25519-sha-256&cost=131072'}, 'amount': '1', 'public_keys': ['HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS']}], 'version': '1.0', 'operation': 'CREATE', 'asset': {'data': {'bicycle': {'manufacturer': 'bkfab', 'serial_number': 'abcd1234'}}}, 'metadata': {'planet': 'earth'}}
>>> 
>>> fulfilled_creation_tx = bdb.transactions.fulfill(
...             prepared_creation_tx, private_keys=alice.private_key)
>>> 
>>> fulfilled_creation_tx 
{'id': 'fd76ef2b1ce79eb65e4b307eaaf3151d9ed1cfd71eb2ed871321366956d27f82', 'inputs': [{'fulfills': None, 'fulfillment': 'pGSAIPXUBGwJ_IhYB_wgCq70r2T8HqPZh_7axT-Yn5TuS1ATgUBG6SKxwKrFo7ta34SSr9gM1T6ar7HhnLA2yPf-W3-6usARW-8mw9msYo6pNhfauDxgRROVbfbYg37GttEqAgIA', 'owners_before': ['HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS']}], 'outputs': [{'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS'}, 'uri': 'ni:///sha-256;7wR_qGs435-inEw7OVZ9k_qcN4wz8Fjciru-BCdH_8s?fpt=ed25519-sha-256&cost=131072'}, 'amount': '1', 'public_keys': ['HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS']}], 'version': '1.0', 'operation': 'CREATE', 'asset': {'data': {'bicycle': {'manufacturer': 'bkfab', 'serial_number': 'abcd1234'}}}, 'metadata': {'planet': 'earth'}}
>>> 
>>> sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
>>> 
>>> 
>>> sent_creation_tx == fulfilled_creation_tx
True
>>> bdb.transactions.status(txid)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'txid' is not defined
>>> 
>>> 
>>> txid = fulfilled_creation_tx['id']
>>> txid
'fd76ef2b1ce79eb65e4b307eaaf3151d9ed1cfd71eb2ed871321366956d27f82'
>>> 
>>> 
>>> bdb.transactions.status(txid)
{'status': 'valid'}

Try to view the same through MongoDB

$ mongo
MongoDB shell version v3.4.10
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.10
Server has startup warnings: 
2017-11-15T22:46:40.923+0530 I CONTROL  [initandlisten] 
2017-11-15T22:46:40.923+0530 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-15T22:46:40.923+0530 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-15T22:46:40.923+0530 I CONTROL  [initandlisten] 
2017-11-15T22:46:40.923+0530 I CONTROL  [initandlisten] 
2017-11-15T22:46:40.923+0530 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
bigchain-rs:PRIMARY> show dbs
admin     0.000GB
bigchain  0.000GB
local     0.001GB
bigchain-rs:PRIMARY> use local
switched to db local
bigchain-rs:PRIMARY> show collections
me
oplog.rs
replset.election
replset.minvalid
startup_log
system.replset
bigchain-rs:PRIMARY> db.me.find()
{ "_id" : ObjectId("5a055664f16b288fbe2ff90a"), "host" : "Ritabratas-MacBook.local" }
bigchain-rs:PRIMARY> db.system.replset.find()
{ "_id" : "bigchain-rs", "version" : 1, "protocolVersion" : NumberLong(1), "members" : [ { "_id" : 0, "host" : "localhost:27017", "arbiterOnly" : false, "buildIndexes" : true, "hidden" : false, "priority" : 1, "tags" : {  }, "slaveDelay" : NumberLong(0), "votes" : 1 } ], "settings" : { "chainingAllowed" : true, "heartbeatIntervalMillis" : 2000, "heartbeatTimeoutSecs" : 10, "electionTimeoutMillis" : 10000, "catchUpTimeoutMillis" : 60000, "getLastErrorModes" : {  }, "getLastErrorDefaults" : { "w" : 1, "wtimeout" : 0 }, "replicaSetId" : ObjectId("5a0556d5f16b288fbe2ff90f") } }
bigchain-rs:PRIMARY> 
bigchain-rs:PRIMARY> 
bigchain-rs:PRIMARY> db.replset.election.find()
{ "_id" : ObjectId("5a0556d7f16b288fbe2ff916"), "term" : NumberLong(3), "candidateIndex" : NumberLong(0) }
bigchain-rs:PRIMARY> db.replset.minvalid.find()
{ "_id" : ObjectId("5a0556d7f16b288fbe2ff911"), "ts" : Timestamp(0, 0), "t" : NumberLong(-1), "oplogDeleteFromPoint" : Timestamp(0, 0) }
bigchain-rs:PRIMARY>

**Comment by rivthebest** [comment]
Troy I had found the db. the value is present under the db bigchain. Here is the result found in the respective collections. Thanks a lot to you for tolerating me. I am bit excited with this new item.

bigchain-rs:PRIMARY> use bigchain
switched to db bigchain
bigchain-rs:PRIMARY> show collections
assets
backlog
bigchain
votes
bigchain-rs:PRIMARY> db.assets.find()
{ "_id" : ObjectId("5a0556dc6319870f230989bb"), "data" : null, "id" : "570af50367a1f4cd241486c76fd4e045c89ec2b2130327adb98189c3e6d5fbd8" }
{ "_id" : ObjectId("5a0c7ad56319874578717ff4"), "id" : "fd76ef2b1ce79eb65e4b307eaaf3151d9ed1cfd71eb2ed871321366956d27f82", "data" : { "bicycle" : { "manufacturer" : "bkfab", "serial_number" : "abcd1234" } } }

bigchain-rs:PRIMARY> db.bigchain.find()
{ "_id" : ObjectId("5a0c7ad56319874578717ff5"), "signature" : "AoBnZkVoXY9NsNeMnZSgdSgbmj8scL8VSgjJW5WNZhP2cP6dBZdvLr19qugup5SmR8RBkGaAVKQqk5eBcPaARxv", "id" : "4873160a8ddb61fc888ee92110c8f11faede134a626ad00763d227cf2b18ba18", "block" : { "timestamp" : "1510767317", "transactions" : [ { "version" : "1.0", "metadata" : { "planet" : "earth" }, "outputs" : [ { "amount" : "1", "condition" : { "details" : { "type" : "ed25519-sha-256", "public_key" : "HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS" }, "uri" : "ni:///sha-256;7wR_qGs435-inEw7OVZ9k_qcN4wz8Fjciru-BCdH_8s?fpt=ed25519-sha-256&cost=131072" }, "public_keys" : [ "HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS" ] } ], "inputs" : [ { "owners_before" : [ "HYcPv8LoH4NhL1tsGP7gkBiuocRjx2xoHPzfpTmnUpgS" ], "fulfills" : null, "fulfillment" : "pGSAIPXUBGwJ_IhYB_wgCq70r2T8HqPZh_7axT-Yn5TuS1ATgUBG6SKxwKrFo7ta34SSr9gM1T6ar7HhnLA2yPf-W3-6usARW-8mw9msYo6pNhfauDxgRROVbfbYg37GttEqAgIA" } ], "id" : "fd76ef2b1ce79eb65e4b307eaaf3151d9ed1cfd71eb2ed871321366956d27f82", "operation" : "CREATE" } ], "node_pubkey" : "WRYpGf92XMV82t2bRmuyCWZML2yjPWkpdpmmotenJ8f", "voters" : [ "WRYpGf92XMV82t2bRmuyCWZML2yjPWkpdpmmotenJ8f" ] } }
bigchain-rs:PRIMARY> 
bigchain-rs:PRIMARY> db.votes.find()
{ "_id" : ObjectId("5a0c7ad56319874582717ff8"), "signature" : "2BosQLqjr6S4VrTAoY5bWyHPNCgR5sWeV8wrYx2DvKrCekWBCEYtA3rH6FG7APyW2Fkh9PTbrCFr3YFeMZNVtmJn", "vote" : { "previous_block" : "377e7239375971134e2413d359f7f5ee4c84bd57cbf0baa9c57addde1469b49a", "invalid_reason" : null, "is_block_valid" : true, "voting_for_block" : "4873160a8ddb61fc888ee92110c8f11faede134a626ad00763d227cf2b18ba18", "timestamp" : "1510767318" }, "node_pubkey" : "WRYpGf92XMV82t2bRmuyCWZML2yjPWkpdpmmotenJ8f" }

**Comment by saikumar-neelam** [comment]
hi there i was getting this error although i had followed the documentation specified in 
http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html 

{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Error on broadcastTxCommit: EOF"
  }
}

**Comment by ttmc** [comment]
@saikumar-neelam This is an old and closed issue. Please create a new issue with more details; the information you provided so far is not enough for me to know what went wrong.

Note: The Simple Deployment Template was updated a bit, so you might want to check the "master" branch of those docs:

http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/index.html

**Comment by rupam150** [comment]
@rivthebest  i am also facing a error when i tried to execute that particular code [sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)]
 I was having a error like this -

---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-53-6495e0171e3f> in <module>
----> 1 sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx)
/opt/anaconda3/envs/blockchain/lib/python3.8/site-packages/bigchaindb_driver/driver.py in send_commit(self, transaction, headers)
    368 
    369         """
--> 370         return self.transport.forward_request(
    371             method='POST',
    372             path=self.path,
/opt/anaconda3/envs/blockchain/lib/python3.8/site-packages/bigchaindb_driver/transport.py in forward_request(self, method, path, json, params, headers)
     73             start = time()
     74             try:
---> 75                 response = connection.request(
     76                     method=method,
     77                     path=path,
/opt/anaconda3/envs/blockchain/lib/python3.8/site-packages/bigchaindb_driver/connection.py in request(self, method, path, json, params, headers, timeout, backoff_cap, **kwargs)
     74 
     75         if timeout is not None and timeout < backoff_timedelta:
---> 76             raise TimeoutError
     77 
     78         if backoff_timedelta > 0:
TimeoutError: 

i have the 2.2 version of bigchaindb 
please inform if i am doing anything wrong??
