### ISSUE TITLE
[HELP] Unable to start bigchaindb on UBUNTU

### ISSUE THREAD

**Issue by raaghavvd** [bigchaindb/bigchaindb#1837]
* BigchainDB version: Latest
* Operating System: ubuntu 16.4
* Deployment Type: `[Docker|Host|IPDB|Other]` Cluster 
  * If you are using IPDB, please specify your network type `[test, prod]`
  and the `bdb_url(BigchainDB URL)` you are using.
  * For every other type of deployment, please specify the documentation/instructions
  you are following.
* BigchainDB driver: `[yes|no]` yes
  * If using a driver please specify, driver type `[python|js|java]`
  and version. python

### Description

I have started mongodb using a replSet command, but bigchaindb doesnt start because it seems to suggest mongodb wasn't started with replSet

### Steps to Reproduce

```bash
alka@mixorg:~$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/alka/.bigchaindb`
[2017-11-13 09:23:50] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.2.0.dev (MainProcess - pid: 5117)
[2017-11-13 09:23:50] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process with public key 64PfNxKSnnKsP3uEzfTsx1QxTBbaBMEkmC8uv2C2fuRD (MainProcess - pid: 5117)
[2017-11-13 09:23:50] [INFO] (bigchaindb.processes) Initializing BigchainDB... (MainProcess - pid: 5117)
[2017-11-13 09:23:50] [INFO] (bigchaindb.processes) Starting block (MainProcess - pid: 5117)
Process Process-10:
[2017-11-13 09:23:50] [INFO] (bigchaindb.processes) Starting voter (MainProcess - pid: 5117)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 235, in _check_replica_set
    repl_opts = options['parsed']['replication']
KeyError: 'replication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==1.2.0.dev0', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/bigchaindb.py", line 355, in main
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 235, in _check_replica_set
    repl_opts = options['parsed']['replication']
KeyError: 'replication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/utils.py", line 206, in start
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/changefeed.py", line 35, in run_forever
    .next()['ts'])
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 62, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 122, in conn
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 153, in connect
    self._conn = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 101, in _connect
    self.crlfile)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 198, in initialize_replica_set
    _check_replica_set(conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 238, in _check_replica_set
    raise ConfigurationError('mongod was not started with'
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/utils.py", line 51, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/utils.py", line 78, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/bigchaindb.py", line 209, in run_start
    processes.start()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/processes.py", line 57, in start
    vote.start()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/pipelines/vote.py", line 183, in start
    pipeline = create_pipeline()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/pipelines/vote.py", line 160, in create_pipeline
    voter = Vote()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/pipelines/vote.py", line 39, in __init__
    self.last_voted_id = Bigchain().get_last_voted_block().id
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/core.py", line 596, in get_last_voted_block
    self.me)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/query.py", line 312, in get_last_voted_block_id
    sort=[('vote.timestamp', -1)]))
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 62, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 122, in conn
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 153, in connect
    self._conn = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 101, in _connect
    self.crlfile)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 198, in initialize_replica_set
    _check_replica_set(conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 238, in _check_replica_set
    raise ConfigurationError('mongod was not started with'
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.
```

Mongodb terminal

```bash
alka@mixorg:~$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/alka/.bigchaindb`
[2017-11-13 09:23:50] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.2.0.dev (MainProcess - pid: 5117)
[2017-11-13 09:23:50] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process with public key 64PfNxKSnnKsP3uEzfTsx1QxTBbaBMEkmC8uv2C2fuRD (MainProcess - pid: 5117)
[2017-11-13 09:23:50] [INFO] (bigchaindb.processes) Initializing BigchainDB... (MainProcess - pid: 5117)
[2017-11-13 09:23:50] [INFO] (bigchaindb.processes) Starting block (MainProcess - pid: 5117)
Process Process-10:
[2017-11-13 09:23:50] [INFO] (bigchaindb.processes) Starting voter (MainProcess - pid: 5117)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 235, in _check_replica_set
    repl_opts = options['parsed']['replication']
KeyError: 'replication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==1.2.0.dev0', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/bigchaindb.py", line 355, in main
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 235, in _check_replica_set
    repl_opts = options['parsed']['replication']
KeyError: 'replication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/utils.py", line 206, in start
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/changefeed.py", line 35, in run_forever
    .next()['ts'])
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 62, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 122, in conn
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 153, in connect
    self._conn = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 101, in _connect
    self.crlfile)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 198, in initialize_replica_set
    _check_replica_set(conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 238, in _check_replica_set
    raise ConfigurationError('mongod was not started with'
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/utils.py", line 51, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/utils.py", line 78, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/commands/bigchaindb.py", line 209, in run_start
    processes.start()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/processes.py", line 57, in start
    vote.start()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/pipelines/vote.py", line 183, in start
    pipeline = create_pipeline()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/pipelines/vote.py", line 160, in create_pipeline
    voter = Vote()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/pipelines/vote.py", line 39, in __init__
    self.last_voted_id = Bigchain().get_last_voted_block().id
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/core.py", line 596, in get_last_voted_block
    self.me)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/query.py", line 312, in get_last_voted_block_id
    sort=[('vote.timestamp', -1)]))
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 62, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 122, in conn
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/connection.py", line 153, in connect
    self._conn = self._connect()
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 101, in _connect
    self.crlfile)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 198, in initialize_replica_set
    _check_replica_set(conn)
  File "/usr/local/lib/python3.5/dist-packages/BigchainDB-1.2.0.dev0-py3.5.egg/bigchaindb/backend/mongodb/connection.py", line 238, in _check_replica_set
    raise ConfigurationError('mongod was not started with'
bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.
```

```bash
alka@mixorg:~$ sudo mongod --replSet bigchain-rs --port 27027
sudo: unable to resolve host mixorg
[sudo] password for alka: 
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] MongoDB starting : pid=5488 port=27027 dbpath=/data/db 64-bit host=mixorg
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] db version v3.4.9
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] git version: 876ebee8c7dd0e2d992f36a848ff4dc50ee6603e
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] allocator: tcmalloc
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] modules: none
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] build environment:
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten]     distarch: x86_64
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten]     target_arch: x86_64
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] options: { net: { port: 27027 }, replication: { replSet: "bigchain-rs" } }
2017-11-13T09:28:23.673+0530 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] 
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1396M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-11-13T09:28:24.305+0530 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-11-13T09:28:24.305+0530 I STORAGE  [initandlisten] The size storer reports that the oplog contains 1817 records totaling to 177140 bytes
2017-11-13T09:28:24.305+0530 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.382+0530 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-11-13T09:28:24.383+0530 I NETWORK  [thread1] waiting for connections on port 27027
2017-11-13T09:28:24.383+0530 W REPL     [replExecDBWorker-0] Locally stored replica set configuration does not have a valid entry for the current node; waiting for reconfig or remote heartbeat; Got "NodeNotFound: No host described in new configuration 1 for replica set bigchain-rs maps to this node" while validating { _id: "bigchain-rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('59e5a85e7ff0e2721751f08c') } }
2017-11-13T09:28:24.383+0530 I REPL     [replExecDBWorker-0] New replica set config in use: { _id: "bigchain-rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('59e5a85e7ff0e2721751f08c') } }
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] This node is not a member of the config
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] transition to REMOVED
2017-11-13T09:28:24.384+0530 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication fetcher thread
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication applier thread
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication reporter thread
```

### What I Did
Followed steps to set up a cluster according to docs. 

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback/error message here.
```

**Comment by ttmc** [comment]
Hi,

1. We need more information. In particular, we need to know what you did _before_ you did `bigchaindb start`. Saying "I followed the instructions" is not enough. Please show us what you did. Walk us through.
2. We will be merging some new instructions and automation tools for deploying a cluster. Those are in pull request https://github.com/bigchaindb/bigchaindb/pull/1790

**Comment by raaghavvd** [comment]
Sorry.
First things first , I installed mongodb community edition on the system.
it is working as expected and have been able to execute to some queries too!
Then, I upgraded my pip and ran sudo apt-get install python3-pip
pip3 install --upgrade pip setuptools
pip3 install bigchaindb
git clone git@github.com:bigchaindb/bigchaindb.git
cd bigchaindb
python setup.py install
bigchaindb -y configure mongodb

I edited the config files as described by you folks.

Next, as this was going to be my first node, I ran the bigchaindb start command.

it hit me up with an error that mongodb needs to be working
So , I ran sudo service mongodb start in a different terminal..
then I ran ' bigchaindb start' it yielded the same error.

So, I went to the quickstart page,

created data/db  while being the super user on the system, 

ran $ sudo chmod -R 700 /data/db

and 
$ sudo mongod --replSet=bigchain-rs
 The above command gave the error that the port was already in use.
(seems to be the issue everytime)

so, I executed mongod --replSet bigchain-rs --port 27027 

which yielded,

alka@mixorg:~$ sudo mongod --replSet bigchain-rs --port 27027
sudo: unable to resolve host mixorg
[sudo] password for alka: 
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] MongoDB starting : pid=5488 port=27027 dbpath=/data/db 64-bit host=mixorg
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] db version v3.4.9
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] git version: 876ebee8c7dd0e2d992f36a848ff4dc50ee6603e
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] allocator: tcmalloc
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] modules: none
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] build environment:
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten]     distarch: x86_64
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten]     target_arch: x86_64
2017-11-13T09:28:23.652+0530 I CONTROL  [initandlisten] options: { net: { port: 27027 }, replication: { replSet: "bigchain-rs" } }
2017-11-13T09:28:23.673+0530 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] 
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-11-13T09:28:23.673+0530 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1396M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-11-13T09:28:24.305+0530 I STORAGE  [initandlisten] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-11-13T09:28:24.305+0530 I STORAGE  [initandlisten] The size storer reports that the oplog contains 1817 records totaling to 177140 bytes
2017-11-13T09:28:24.305+0530 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-11-13T09:28:24.373+0530 I CONTROL  [initandlisten] 
2017-11-13T09:28:24.382+0530 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-11-13T09:28:24.383+0530 I NETWORK  [thread1] waiting for connections on port 27027
2017-11-13T09:28:24.383+0530 W REPL     [replExecDBWorker-0] Locally stored replica set configuration does not have a valid entry for the current node; waiting for reconfig or remote heartbeat; Got "NodeNotFound: No host described in new configuration 1 for replica set bigchain-rs maps to this node" while validating { _id: "bigchain-rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('59e5a85e7ff0e2721751f08c') } }
2017-11-13T09:28:24.383+0530 I REPL     [replExecDBWorker-0] New replica set config in use: { _id: "bigchain-rs", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('59e5a85e7ff0e2721751f08c') } }
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] This node is not a member of the config
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] transition to REMOVED
2017-11-13T09:28:24.384+0530 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication fetcher thread
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication applier thread
2017-11-13T09:28:24.384+0530 I REPL     [replExecDBWorker-0] Starting replication reporter thread



then, I ran 'bigchaindb start'

which led to the terminal responding, bigchaindb.common.exceptions.ConfigurationError: mongod was not started with the replSet option.

**Comment by ttmc** [comment]
I think you need to shut down all MongoDB processes and services and try again. See:

https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/

and

https://stackoverflow.com/questions/11774887/how-to-stop-mongo-db-in-one-command

**Comment by raaghavvd** [comment]
It's working now w/o changing ports. Thanks Troy ! :) 
When can I expect the updated documentation on deploying a cluster?

**Comment by ttmc** [comment]
> When can I expect the updated documentation on deploying a cluster?

Soon. Just follow pull request https://github.com/bigchaindb/bigchaindb/pull/1790

Once it's merged, you'll be able to find the updated docs in:

https://docs.bigchaindb.com/projects/server/en/master/appendices/run-with-vagrant.html

and

https://docs.bigchaindb.com/projects/server/en/master/appendices/run-with-ansible.html

**Comment by nguyenthuymo** [comment]
Hello, I still cannot run the $ bigchaindb start with the same error above. I did try stop mongodb but still error. I did start mongodb with flag --replSet but still error. Can you please help me some idea? I'm runing Ubuntu 17.10 on VMWare. Is it a problem?

**Comment by raaghavvd** [comment]
Hi, @nguyenthuymo 
I created a video which contains the step by step installation of bigchaindb. 
https://www.youtube.com/watch?v=tB8Nbu_l_NA

Sorry for the late reply, hope this helps you :)
