### ISSUE TITLE
Asset Transfer issue . [Help] 

### ISSUE THREAD

**Issue by raaghavvd** [bigchaindb/bigchaindb#1869]
* BigchainDB version: Latest
* Operating System: OSX
* Deployment Type: `[Docker|Host|IPDB|Other]` google Cloud
  * If you are using IPDB, please specify your network type `[test, prod]`
  and the `bdb_url(BigchainDB URL)` you are using.
  * For every other type of deployment, please specify the documentation/instructions
  you are following. Have deployed the big chain node on google cloud
* BigchainDB driver: `[yes|no]` Python Driver
  * If using a driver please specify, driver type `[python|js|java]`
  and version.

### Description

I'm trying to transfer the bicycle asset from  bob to another person

### Steps to Reproduce
If you have the precise steps to reproduce, please specify. If you can reproduce
ocassionally, please provide additional information; e.g. screenshots, commands, logs, etc.

### What I Did
```python
from bigchaindb_driver import BigchainDB  # This imports the BigchainDB which has been running on the system
from bigchaindb_driver.crypto import generate_keypair  # This imports the generate_keypair module which is required for creating private and public kets
import time
bdb_root_url= 'http://35.186.154.101:9984'
#bdb_root_url = 'http://localhost:9984'

bdb = BigchainDB(bdb_root_url)  # This denotes the fact that we are not using authentication tokens
alice = generate_keypair()
bob = generate_keypair()
matt = generate_keypair()


def poll(transaction_id):
        for attempt in range(10):
            if bdb.transactions.status(transaction_id).get('status') == 'valid':
                break
            time.sleep(0.5)

'''
Here the asset being transferred is a bicycle which belongs to Alice
The variable below contains a data property which contains the information about the bicycle
'''

bicycle = {
    'data': {
        'bicycle': {
            'serial_number': 'XX2334C',
            'manufacturer': 'bkfab',
        },

    },
}
metadata = {'Country': 'France'}  # Any dictionary can be used as Metadata
prepared_creation_tx = bdb.transactions.prepare(operation='CREATE', signers=alice.public_key, asset=bicycle,
                                                metadata=metadata)  # This creates a digital asset
fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx,
                                                 private_keys=alice.private_key)
sent_creation_tx = bdb.transactions.send(
    fulfilled_creation_tx)  # the authorized transaction is now sent over to the BigchainDB
txid = fulfilled_creation_tx['id']  # contains the transaction id
poll(txid)
creation_tx = fulfilled_creation_tx  # Alice retrieves the transaction
print("Alice retrieves", creation_tx)

'''
Preparing a transaction
To get inforamtion about the id of the asset we are transferrring
'''
asset_id = creation_tx['id']
print(asset_id)
transfer_asset = {
    'id': asset_id,
}

'''
Transfer transaction
'''
output_index = 0
output = creation_tx['outputs'][output_index]
transfer_input = {
    'fulfillment': output['condition']['details'],
    'fulfills': {
        'output_index': output_index,
        'transaction_id': creation_tx['id'],
    },
    'owners_before': output['public_keys'],
}
prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=bob.public_key,
)
# Fulfillment of transfer
fulfilled_transfer_tx = bdb.transactions.fulfill(
    prepared_transfer_tx,
    private_keys=alice.private_key,
)
# Send it across the Node
sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
poll(sent_transfer_tx['id'])
print("Fulfilled transfer looks like", fulfilled_transfer_tx)
print("Is the bob the owner?", sent_transfer_tx['outputs'][0]['public_keys'][0] == bob.public_key)
print("Was Alice the previous owner? ", fulfilled_transfer_tx['inputs'][0]['owners_before'][0] == alice.public_key)
transfer_tx = fulfilled_transfer_tx

'''
Transfer transaction again
'''
asset_id = transfer_tx['asset']['id']
transfer_asset = {
    'id': asset_id,
}
print("Helllooo")
print(transfer_tx['asset']['id'])

output = creation_tx['outputs'][output_index]
transfer_input = {
    'fulfillment': output['condition']['details'],
    'fulfills': {
        'output_index': output_index,
        'transaction_id': transfer_tx['id'],
    },
    'owners_before': [bob.public_key]
}
prepared_transfer_tx_again = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=matt.public_key,
)
# Fulfillment of transfer
fulfilled_transfer_tx_again = bdb.transactions.fulfill(
    prepared_transfer_tx_again,
    private_keys=bob.private_key,
)
# Send it across the Node
sent_transfer_tx_again = bdb.transactions.send(fulfilled_transfer_tx_again)
poll(sent_transfer_tx_again['id'])
print("Fulfilled transfer looks like")
print(fulfilled_transfer_tx_again)

print("Is Matt the owner?", sent_transfer_tx_again['outputs'][0]['public_keys'][0] == matt.public_key)
print("Was Bob the previous owner? ", fulfilled_transfer_tx_again['inputs'][0]['owners_before'][0] == bob.public_key)
```

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback/error message here.

```text

Alice retrieves {'inputs': [{'owners_before': ['FHPauTx5fppmZPnGQbisNBhD4khNP1Qfh8KT4xfXSqQG'], 'fulfills': None, 'fulfillment': 'pGSAINQ2ckSX
8IFr8c87scBi39hcGwQvf-dROCsD0O_k1cjNgUBwuKyMVHLRcQEKdsx6g4iHJkrhhWh8ymDhk6TQJ83yWLk3Q-rSPtj8IctlAEiwswMhiXT1IuVmvmujJeof3NwN'}], 'outputs': [{
'public_keys': ['FHPauTx5fppmZPnGQbisNBhD4khNP1Qfh8KT4xfXSqQG'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'FHPauTx5f
ppmZPnGQbisNBhD4khNP1Qfh8KT4xfXSqQG'}, 'uri': 'ni:///sha-256;nlz9fzQPP4b88gUIigL0vhTj1g1XCzo6MBU67b0w12E?fpt=ed25519-sha-256&cost=131072'}, 'a
mount': '1'}], 'operation': 'CREATE', 'metadata': {'Country': 'France'}, 'asset': {'data': {'bicycle': {'serial_number': 'XX2334C', 'manufactu
rer': 'bkfab'}}}, 'version': '1.0', 'id': '24137a4d9dbeca48448fa5e200f783eb84c55318afe9f7033c0691890004ce63'}
24137a4d9dbeca48448fa5e200f783eb84c55318afe9f7033c0691890004ce63
Fulfilled transfer looks like {'inputs': [{'owners_before': ['FHPauTx5fppmZPnGQbisNBhD4khNP1Qfh8KT4xfXSqQG'], 'fulfills': {'transaction_id': '
24137a4d9dbeca48448fa5e200f783eb84c55318afe9f7033c0691890004ce63', 'output_index': 0}, 'fulfillment': 'pGSAINQ2ckSX8IFr8c87scBi39hcGwQvf-dROCs
D0O_k1cjNgUAns7E-UNMlw-MRZ_zkZF0nzZMZi7Axr51Ptm614ASwxpOkrZhKMU2v5qHamBfwkxfOFCV2X_ESeeM6nHQzW8sF'}], 'outputs': [{'public_keys': ['4SLbEyyk4u
Xnr6JDiYLXuPzqysbEqV85G6JLsyF6Ymrs'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': '4SLbEyyk4uXnr6JDiYLXuPzqysbEqV85G6JL
syF6Ymrs'}, 'uri': 'ni:///sha-256;pNQKjRR-agmRXOkUf6WX_sRX_tmKEFIpCia-YCmYl-c?fpt=ed25519-sha-256&cost=131072'}, 'amount': '1'}], 'operation':
 'TRANSFER', 'metadata': None, 'asset': {'id': '24137a4d9dbeca48448fa5e200f783eb84c55318afe9f7033c0691890004ce63'}, 'version': '1.0', 'id': '1
8b3e74f2f38bc5beb3abde4df3b8a486261eed729f834bd6b2613bd36a90700'}
Is the bob the owner? True

Was Alice the previous owner?  True
Helllooo
24137a4d9dbeca48448fa5e200f783eb84c55318afe9f7033c0691890004ce63
Traceback (most recent call last):
  File "Bgdb.py", line 120, in <module>
    poll(sent_transfer_tx_again['id'])
  File "Bgdb.py", line 15, in poll
    if bdb.transactions.status(transaction_id).get('status') == 'valid':
  File "/anaconda/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 353, in status
    headers=headers)
  File "/anaconda/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/anaconda/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.NotFoundError: (404, '{\n  "message": "Not found", \n  "status": 404\n}\n', {'message': 'Not found', 'status': 40
4})
```

**Comment by ttmc** [comment]
The first problem I noticed was in the section titled "Transfer transaction again". I'm guessing you want to create a second TRANSFER transaction which transfers the output on the first TRANSFER transaction.

CREATE --> TRANSFER 1 ---> TRANSFER 2 

`creation_tx` --> `transfer_tx` --> ???

As you build the new transfer transaction (TRANSFER 2), you want to be transferring the output on TRANSFER 1 (`transfer_tx`). Why then, did you do:

```python
output = creation_tx['outputs'][output_index]
```

Suggestion:  Change `creation_tx` to `transfer_tx` and see what happens.

**Comment by raaghavvd** [comment]
@ttmc
I opened a similar issue a while back , which was solved by @diminator. I am running the code provided by him.
  https://github.com/bigchaindb/bigchaindb/issues/1786

**Comment by raaghavvd** [comment]
I checked your suggestion, it yields the same error
Raaghavvs-MacBook-Air:Blockchain bulletcoder$ python Bgdb.py
Alice retrieves {'inputs': [{'owners_before': ['8YGvPt81XvY3mABSgU61md81YveawY9igTPzwYcPoVLZ'], 'fulfills': None, 'fulfillment': 'pGSAIHAE0KZ0
OXPMPNeLco40H09tDESUkKv4QxKjNqu86JmOgUD6MtmIHhGH5IAfgxwdEgFgq3XYxYs3TVRGiZraAhsBNw56t4y-NyxnR3QpQXrygK9Blpr_Gr2wU4YXXppGdUgH'}], 'outputs': [{
'public_keys': ['8YGvPt81XvY3mABSgU61md81YveawY9igTPzwYcPoVLZ'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': '8YGvPt81X
vY3mABSgU61md81YveawY9igTPzwYcPoVLZ'}, 'uri': 'ni:///sha-256;u-GwvDBfg3sVA_x4XWzcarG1z5jXPwLT6L6bJdGtCPs?fpt=ed25519-sha-256&cost=131072'}, 'a
mount': '1'}], 'operation': 'CREATE', 'metadata': {'Country': 'France'}, 'asset': {'data': {'bicycle': {'serial_number': 'XX2334C', 'manufactu
rer': 'bkfab'}}}, 'version': '1.0', 'id': 'e4bcca7a7c9cb8a0af8ecf80ef73bddd89ca18259801f5854d564a0c12f0c350'}
e4bcca7a7c9cb8a0af8ecf80ef73bddd89ca18259801f5854d564a0c12f0c350
Traceback (most recent call last):
  File "Bgdb.py", line 81, in <module>
    sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
  File "/anaconda/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 319, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/anaconda/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,

  File "/anaconda/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.BadRequest: (400, '{\n  "message": "Invalid transaction (TransactionNotInValidBlock): input `e4bcca7a7c9cb8a0af8e
cf80ef73bddd89ca18259801f5854d564a0c12f0c350` does not exist in a valid block", \n  "status": 400\n}\n', {'message': 'Invalid transaction (Tra
nsactionNotInValidBlock): input `e4bcca7a7c9cb8a0af8ecf80ef73bddd89ca18259801f5854d564a0c12f0c350` does not exist in a valid block', 'status':
 400})
Raaghavvs-MacBook-Air:Blockchain bulletcoder$

**Comment by ttmc** [comment]
Please drag and drop your file `Bgdb.py` onto this page (as a file). GitHub should embed it as a file that I can then download to my computer. I'll take a look through it and see what I can see.

**Comment by raaghavvd** [comment]
Thanks for your help, Troy :)
[Bgdb.py.zip](https://github.com/bigchaindb/bigchaindb/files/1490367/Bgdb.py.zip)

**Comment by ttmc** [comment]
To test your script (`Bgdb.py`), I set up a clean MongoDB + BigchainDB running on my local machine (on localhost). I edited the opening of the script to make `bdb_root_url = 'http://localhost:9984'`

Then I ran it (in a virtualenv where "python" is Python 3.6.3). Here is what happened:
```bash
$ python Bgdb.py 
Alice retrieves {'inputs': [{'owners_before': ['D2MPxkSJNKCQmex1kQ3B7Utp4eKFw6GgDYB7nAEPynn1'], 'fulfills': None, 'fulfillment': 'pGSAILKk4rg0JVZqQvExe_VOEG36tToCdvYEcDbjMnF3PlGGgUB_vuiZ5nacXO51iQDAu3vRcqX1Z0TVxxZCA49MjaxsvrlmlZzwWlmhr4pX7Q6onW7GCfVGF5_5DXNohzvn478M'}], 'outputs': [{'public_keys': ['D2MPxkSJNKCQmex1kQ3B7Utp4eKFw6GgDYB7nAEPynn1'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'D2MPxkSJNKCQmex1kQ3B7Utp4eKFw6GgDYB7nAEPynn1'}, 'uri': 'ni:///sha-256;thX3MuR9Dd10Hk-LHQgm6j9aZZdMmgJl2Y2oz8Myp7E?fpt=ed25519-sha-256&cost=131072'}, 'amount': '1'}], 'operation': 'CREATE', 'metadata': {'Country': 'France'}, 'asset': {'data': {'bicycle': {'serial_number': 'XX2334C', 'manufacturer': 'bkfab'}}}, 'version': '1.0', 'id': '610e9a0ce248009de53ad1718048cce2566835a4f909b6f71955fc8b2c7d1a0b'}
610e9a0ce248009de53ad1718048cce2566835a4f909b6f71955fc8b2c7d1a0b
Fulfilled transfer looks like {'inputs': [{'owners_before': ['D2MPxkSJNKCQmex1kQ3B7Utp4eKFw6GgDYB7nAEPynn1'], 'fulfills': {'transaction_id': '610e9a0ce248009de53ad1718048cce2566835a4f909b6f71955fc8b2c7d1a0b', 'output_index': 0}, 'fulfillment': 'pGSAILKk4rg0JVZqQvExe_VOEG36tToCdvYEcDbjMnF3PlGGgUCGjwimKfPNB7I2Src_JNtgbcHhFSc1YGTAwELVZS7JkMwlJt1JSbKBqivNxcrtUlu99j73DYEWkb78O9mNFj0P'}], 'outputs': [{'public_keys': ['7u54hh2wtM2LJHo6xba5Lf8LP3HeeXNszCDqz5nncWak'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': '7u54hh2wtM2LJHo6xba5Lf8LP3HeeXNszCDqz5nncWak'}, 'uri': 'ni:///sha-256;GYztpE7zKWx2HM0tZiLwGtLW8S2JCbAgLBxb95ywL1A?fpt=ed25519-sha-256&cost=131072'}, 'amount': '1'}], 'operation': 'TRANSFER', 'metadata': None, 'asset': {'id': '610e9a0ce248009de53ad1718048cce2566835a4f909b6f71955fc8b2c7d1a0b'}, 'version': '1.0', 'id': '332c80172cbfc4198e39523e637a557cb0b85a4fb0d239a2f28d7856565c8a6f'}
Is the bob the owner? True
Was Alice the previous owner?  True
Helllooo
610e9a0ce248009de53ad1718048cce2566835a4f909b6f71955fc8b2c7d1a0b
Fulfilled transfer looks like
{'inputs': [{'owners_before': ['7u54hh2wtM2LJHo6xba5Lf8LP3HeeXNszCDqz5nncWak'], 'fulfills': {'transaction_id': '332c80172cbfc4198e39523e637a557cb0b85a4fb0d239a2f28d7856565c8a6f', 'output_index': 0}, 'fulfillment': 'pGSAIGZ86ynA4Con9PGWFmzeVmPnBJq2zjLwZ6fHT-OrmzyhgUB2NZ1RPz9EUis7nEQjJD-4H85rpZ6QQcsM18nluacJc6ZP2KH4ou5BO9OjwHfKZ2NHC6HzOK8BRHzRU2dZdI0L'}], 'outputs': [{'public_keys': ['HALZt5dyFkb5JMHfR6Aq6VyRMoMWezN5M5WTcAC9DqZT'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'HALZt5dyFkb5JMHfR6Aq6VyRMoMWezN5M5WTcAC9DqZT'}, 'uri': 'ni:///sha-256;l8R_-QQw5C9TrVZqWiOlkqZtzi9PT2cIxzIeqFms2GI?fpt=ed25519-sha-256&cost=131072'}, 'amount': '1'}], 'operation': 'TRANSFER', 'metadata': None, 'asset': {'id': '610e9a0ce248009de53ad1718048cce2566835a4f909b6f71955fc8b2c7d1a0b'}, 'version': '1.0', 'id': '93ac803a8acf11b5ef41f9b68fee041cac44a7c2905a5adfaec71088985b5cbd'}
Is Matt the owner? True
Was Bob the previous owner?  True
```

It all looks okay to me. Maybe you just need to try with a clean fresh backend database (MongoDB or RethinkDB)?

**Comment by raaghavvd** [comment]
It works on my localhost as well, I recently installed a fresh version of both bigchain and Mongodb on the cloud. You want me to do it again?

**Comment by ttmc** [comment]
You don't have to reinstall the MongoDB database. You can just "drop" it using `bigchaindb drop` (on the machine currently running MongoDB). It that's not enough, then maybe:
```bash
$ sudo mongod --shutdown
$ sudo rm -rf /data/db
$ sudo mkdir -p /data/db
$ sudo chmod -R 700 /data/db
$ sudo mongod --replSet=bigchain-rs
```

**Comment by raaghavvd** [comment]
still the same issue Troy, I can't seem to transfer the asset to bob or Matt now :/

**Comment by ttmc** [comment]
@raaghavvd This is an old issue and BigchainDB is very different from what it was when this issue was opened. Therefore I'm going to close this issue. If you have any issues with the current version of BigchainDB, please feel free to open a new issue.
