### ISSUE TITLE
"bigchaindb start" sometimes gets bigchaindb.common.exceptions.InvalidHash and hangs

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1884]
- BigchainDB version: 1.3.0 (released version), and the current master branch of bigchaindb/bigchaindb.
- Backend DB: MongoDB
- OS: Ubuntu 16.04 remote and Ubuntu 17.10 local (and maybe others)

This issue was first reported by @charlespetchsy on Gitter; see https://gitter.im/bigchaindb/bigchaindb?at=5a14566c232e79134db5100a

I was able to reproduce it on my local machine (running Ubuntu 17.10), with both the current master branch and the v1.3 release branch (which was just released).

### Sample Output

```bash
(bdb) troy@troy-thinkpad:~/temp-bdb$ rm ~/.bigchaindb 
(bdb) troy@troy-thinkpad:~/temp-bdb$ bigchaindb --version
bigchaindb 1.3.0
(bdb) troy@troy-thinkpad:~/temp-bdb$ bigchaindb -y configure mongodb
Generating keypair
Generating default configuration for backend mongodb
Configuration written to /home/troy/.bigchaindb
Ready to go!
(bdb) troy@troy-thinkpad:~/temp-bdb$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/troy/.bigchaindb`
[2017-11-21 20:41:19] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.3.0 (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process with public key 81fUUBTmDJbqsaM7NZGExUcBswqKQ6z1nYPpzLtQXgX1 (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.processes) Initializing BigchainDB... (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.processes) Starting block (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-10 - pid: 27077)
[2017-11-21 20:41:19] [INFO] (bigchaindb.processes) Starting voter (MainProcess - pid: 27063)
[2017-11-21 20:41:19] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-10 - pid: 27077)
[2017-11-21 20:41:19] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 27063)
Traceback (most recent call last):
  File "/home/troy/temp-bdb/bdb/bin/bigchaindb", line 11, in <module>
    sys.exit(main())
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/commands/bigchaindb.py", line 356, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/commands/utils.py", line 206, in start
    return func(args)
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/commands/utils.py", line 51, in configure
    command(args)
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/commands/utils.py", line 78, in start_logging
    command(args)
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/commands/bigchaindb.py", line 209, in run_start
    processes.start()
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/processes.py", line 57, in start
    vote.start()
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/pipelines/vote.py", line 183, in start
    pipeline = create_pipeline()
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/pipelines/vote.py", line 160, in create_pipeline
    voter = Vote()
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/pipelines/vote.py", line 39, in __init__
    self.last_voted_id = Bigchain().get_last_voted_block().id
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/core.py", line 608, in get_last_voted_block
    return Block.from_dict(self.get_block(last_block_id))
  File "/home/troy/temp-bdb/bdb/lib/python3.6/site-packages/bigchaindb/models.py", line 303, in from_dict
    raise InvalidHash()
bigchaindb.common.exceptions.InvalidHash

```

At this point it hangs (i.e. I don't get a prompt). I can un-hang it with CTRL + C

**Comment by ttmc** [comment]
I found that I was able to get BigchainDB Server to run normally by shutting down MongoDB (`sudo mongod --shutdown`) then completely wiping out the `/data/db` directory (i.e. `sudo rm -rf /data/db`) and then recreating the `/data/db` directory with the correct permissions as per the instructions in https://docs.bigchaindb.com/projects/server/en/master/quickstart.html ).

I suppose a more graceful way to wipe the database would be to use `bigchaindb drop` but I forgot about that (and so I didn't try it).

I was thinking about why this might be happening and now I think I know:  when we merged pull request #1812 (metadata full text search) on Monday (November 20), that added a new table to the database for storing metadata (and indexing it for full text search). Metadata is now removed from the transactions in a block before storing the block in the bigchain table. If you had data in your MongoDB database from before the merge, and then you tried to run BigchainDB again after the merge, then _problems arose_. Wiping the MongoDB database stops the problems.
