### ISSUE TITLE
Latest BigchainDB docker image broken: `ImportError: cannot import name 'unquote'`

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#2001]
* BigchainDB version: master/latest
* Operating System: N/A
* Deployment Type: `Docker`

### Description

The Docker image built from latest master is broken and fails with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB==1.3.0', 'console_scripts', 'bigchaindb')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/bigchaindb/commands/bigchaindb.py", line 18, in <module>
    from bigchaindb import backend, processes
  File "/usr/lib/python3.4/site-packages/bigchaindb/processes.py", line 8, in <module>
    from bigchaindb.web import server, websocket_server
  File "/usr/lib/python3.4/site-packages/bigchaindb/web/server.py", line 15, in <module>
    from bigchaindb.web.routes import add_routes
  File "/usr/lib/python3.4/site-packages/bigchaindb/web/routes.py", line 3, in <module>
    from bigchaindb.web.views import (
  File "/usr/lib/python3.4/site-packages/bigchaindb/web/views/info.py", line 9, in <module>
    from bigchaindb.web.websocket_server import EVENTS_ENDPOINT
  File "/usr/lib/python3.4/site-packages/bigchaindb/web/websocket_server.py", line 21, in <module>
    from aiohttp import web
  File "/usr/lib/python3.4/site-packages/aiohttp/web.py", line 15, in <module>
    from . import (hdrs, web_exceptions, web_fileresponse, web_middlewares,
  File "/usr/lib/python3.4/site-packages/aiohttp/web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "/usr/lib/python3.4/site-packages/aiohttp/web_urldispatcher.py", line 21, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'
```

This is because the python module [yarl](https://github.com/aio-libs/yarl) does not expose `unquote` anymore in their latest release `1.0.0`, and `aiohttp` expects that to be present in `web_urldispatcher.py`.

### Steps to Reproduce
 ```
$ git clone https://github.com/bigchaindb/bigchaindb.git
$ cd bigchaindb/
$ docker build -t bigchaindb/bigchaindb:test .
$ docker run -i --rm --tty --volume $HOME/bigchaindb_docker:/data --env BIGCHAINDB_DATABASE_HOST=172.17.0.1 bigchaindb/bigchaindb:test -y configure mongodb
```

### Solution
Use [setuptools](https://packaging.python.org/key_projects/#setuptools) `setup.py` to limit the `yarl` version i.e. `yarl<=0.18.0`.

**Comment by numyio** [comment]
To fix this issue I just installed a later version of 'yarl' 

`sudo pip3 install yarl==0.9.1`

**Comment by muawiakh** [comment]
Yes, pushed a fix for it as well. @numyio
