### ISSUE TITLE
Cannot start BigchainDB in a 3 node cluster installation

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#2013]
* BigchainDB version: 1.3.0
* Operating System: Linux 10-1-0-6 4.4.0-109-generic
* Deployment Type: `Host`

* Cluster of 3 nodes

### Description
BigchainDB was working before with 3 nodes. In the logs of BigchainDB I could see that a lot of transactions were posted, then I tried to insert some others, but I did not received any response from BigchainDB likely because the node collapsed due to a huge amount of transactions coming in.
Then I restarted the node, but I could not start it again. I get the following error:

### Steps to Reproduce
Install BigchainDB, share keypairing among the 3 different nodes, and try to start BigchainDB.

### What I Did

```
sudo bigchaindb start


INFO:bigchaindb.config_utils:Configuration loaded from `/home/manuel/.bigchaindb`
[2018-01-29 04:14:49] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.3.0 (MainProcess - pid: 2160)
[2018-01-29 04:14:49] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 2160)
[2018-01-29 04:14:49] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 2160)
[2018-01-29 04:14:49] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process with public key CSAsm8wxcdHoqCNVKxAdMLLiTRp1s3iK6mb2pmAK9rEs (MainProcess - pid: 2160)
[2018-01-29 04:14:49] [INFO] (bigchaindb.processes) Initializing BigchainDB... (MainProcess - pid: 2160)
[2018-01-29 04:14:49] [INFO] (bigchaindb.processes) Starting block (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.processes) Starting voter (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-8  - pid: 2178)
[2018-01-29 04:14:50] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (Process-8  - pid: 2178)
[2018-01-29 04:14:50] [INFO] (bigchaindb.common.transaction) transaction::validate_id txn_id
de4ee6e4fab4c666aacc313bf968e6e29cc0c389cce27d71132411dc1f09a89c
 (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.common.transaction) transaction::validate_id txn_id
5996e0bdb5f36fa359d8423c7ffbbd5fbceba3a35986eb5a3a927f189761ebda
 (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.common.transaction) transaction::validate_id txn_id
df75f3c1a864db5561b68fc5358b0dc6fee096dfab7d1343f1026ea4a03801a8
 (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.common.transaction) transaction::validate_id txn_id
de4ee6e4fab4c666aacc313bf968e6e29cc0c389cce27d71132411dc1f09a89c
 (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.common.transaction) transaction::validate_id txn_id
5996e0bdb5f36fa359d8423c7ffbbd5fbceba3a35986eb5a3a927f189761ebda
 (MainProcess - pid: 2160)
[2018-01-29 04:14:50] [INFO] (bigchaindb.common.transaction) transaction::validate_id txn_id
df75f3c1a864db5561b68fc5358b0dc6fee096dfab7d1343f1026ea4a03801a8
 (MainProcess - pid: 2160)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==1.3.0', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 356, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 206, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 51, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 78, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 209, in run_start
    processes.start()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/processes.py", line 57, in start
    vote.start()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/vote.py", line 184, in start
    pipeline.setup(indata=get_changefeed())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/vote.py", line 176, in get_changefeed
    feed = backend.query.get_new_blocks_feed(b.connection, last_block_id)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/query.py", line 362, in get_new_blocks_feed
    last_ts = conn.run(query)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/connection.py", line 62, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/utils.py", line 175, in run
    last = last(*item[0], **item[1])
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1140, in next
    raise StopIteration
StopIteration

```

**Comment by sidexchange** [comment]
Note that the issue started to occur when a large number of assets were created by a script with about a 10 minute time interval. The payload of each asset ranged from 500kb to 3 MB for each asset record.
After that time additional asset creation scripts (with any size payload) did not complete (no error was generated)

**Comment by vrde** [comment]
@sidexchange mentioned:
> The payload of each asset ranged from 500kb to 3 MB for each asset record.

It might be related to the 16MB limit that MongoDB has on the size of a document. We pack up to 1000 transactions in a block, and a block is a single document in the database. For the IPDB we limited the size of a transaction to 16KB, so in case of 1000 transaction we would not hit the database limit for the document size. The limit was enforced by `nginx` itself, so it's not encoded in  BigchainDB itself.

If this is the case, then we should file a bug.

**Comment by sidexchange** [comment]
@vrde 
since then we have tried a reload (after reinitializing the Bigchaindb cluster). The transaction size now is near 100KB with a test run of ~ 400 transactions. Now we have a different symptom. No errors when loading the records, but the asset ids cannot be retrieved (404 - not found) after the load completes. Could this still be related to the 16 MB MongoDB limit , or could there be other contributing factors?

**Comment by vrde** [comment]
Usually transactions are put in a block every second, or every 1000 transactions, whatever comes first. Depending on your setup, pushing 400 transactions to a single node might take few seconds, so you should not reach the 16MB MongoDB limit.

> [...] but the asset ids cannot be retrieved (404 - not found) after the load completes.

After pushing your transactions, did you give enough time (few seconds) to the system to validate them?

This is a bug we need to fix. We can easily write a test case for that.

**Comment by manolodewiner** [comment]
What is the status of this?

**Comment by ttmc** [comment]
The way that one sets up a multi-node cluster is quite different in BigchainDB 2.0+ so I'm closing this issue.
