### ISSUE TITLE
docker problem when setting `statsd` settings

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#207]
Following https://bigchaindb.readthedocs.org/en/latest/installing-server.html#run-bigchaindb-with-docker may fail with the following error

``` bash
rethinkdb_1      | Recursively removing directory /data/rethinkdb_data/tmp
rethinkdb_1      | Initializing directory /data/rethinkdb_data
rethinkdb_1      | Running rethinkdb 2.2.3+1~0jessie (GCC 4.9.2)...
rethinkdb_1      | Running on Linux 3.16.0-67-generic x86_64
rethinkdb_1      | Loading data from directory /data/rethinkdb_data
rethinkdb_1      | Listening for intracluster connections on port 29015
rethinkdb_1      | Listening for client driver connections on port 28015
rethinkdb_1      | Listening for administrative HTTP connections on port 8080
rethinkdb_1      | Listening on addresses: 127.0.0.1, 172.17.0.3, ::1, fe80::42:acff:fe11:3%119
rethinkdb_1      | Server ready, "b323d5afd6c8_bor" 69804bfe-04d9-4da3-93bb-5ffed2275ba7
rethinkdb_1      | A newer version of the RethinkDB server is available: 2.2.6. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/bin/bigchaindb", line 9, in <module>
bigchaindb_1     |     load_entry_point('BigchainDB==0.1.5', 'console_scripts', 'bigchaindb')()
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
bigchaindb_1     |     return get_distribution(dist).load_entry_point(group, name)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
bigchaindb_1     |     return ep.load()
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
bigchaindb_1     |     return self.resolve()
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
bigchaindb_1     |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/__init__.py", line 39, in <module>
bigchaindb_1     |     from bigchaindb.core import Bigchain  # noqa
bigchaindb_1     |   File "/usr/src/app/bigchaindb/core.py", line 14, in <module>
bigchaindb_1     |     monitor = Monitor()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/monitor.py", line 30, in __init__
bigchaindb_1     |     super().__init__(*args, **kwargs)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/statsd/client.py", line 139, in __init__
bigchaindb_1     |     host, port, fam, socket.SOCK_DGRAM)[0]
bigchaindb_1     |   File "/usr/local/lib/python3.5/socket.py", line 732, in getaddrinfo
bigchaindb_1     |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
bigchaindb_1     | socket.gaierror: [Errno -2] Name or service not known
```

This happens if we set the statsd host to `statsd`. Python seems not to be able to resolve the hostname and trows an exception. Leaving statsd host to the default `localhost` does not produce this problem.

This seems to be happening in only some setups and we need to investigate what is causing this. Different versions of `docker` or `docker-compose`? Misuse of `docker network`?

**Comment by r-marques** [comment]
@sbellem for some reason I am not able to reproduce this on my machine. Everything works fine

**Comment by r-marques** [comment]
@sbellem Not sure what we need to do here. The docker setup changed a lot since this issue was created. Maybe we can close this.

**Comment by sohkai** [comment]
Closing, since we aren't really using any monitoring code anymore. A new issue about cleaning up some of the outdated monitoring code has been opened: #989.
