### ISSUE TITLE
Tendermint branch error while testing

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#2142]
* BigchainDB version: Tendermint branch
* Operating System: Ubuntu
* Deployment Type: `Docker`
* BigchainDB driver: `yes` 
  * If using a driver please specify, driver type `[python|js|java]`
  and version.

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### Steps to Reproduce

Running the test of this JS driver branch:
https://github.com/bigchaindb/js-bigchaindb-driver/pull/159

### What I Did

I get this exception in the bigchaindb logs:

```
[2018-03-21 12:17:12,304] ERROR in app: Exception on /api/v1/transactions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f66c62a72b0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tendermint', port=46657): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f66c62a72b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

```

**Comment by muawiakh** [comment]
@manolodewiner How did you deploy your environment? Can you try with latest `master`? Also send me the link you followed OR steps to reproduce. Also the payload you are trying to send.

Can you add a description?

**Comment by muawiakh** [comment]
@manolodewiner is this still occuring or can I close this?

**Comment by manolodewiner** [comment]
I'll take that pleasure :)
