### ISSUE TITLE
When numerous inputs to a TRANSFER txn, BDB crashes (v2.0.0a1)

### ISSUE THREAD

**Issue by harlantwood** [bigchaindb/bigchaindb#2182]
### What computer are you on (hardware)?

MBP 2.5 GHz Intel Core i7

### What operating system are you using, including version. e.g. Ubuntu 14.04? Fedora 23?

OSX 10.12.6 (Sierra)

### What version of BigchainDB software were you using?

I am seeing this error on Bigchain 2.0alpha1 ([v2.0.0a1](https://github.com/bigchaindb/bigchaindb/tree/v2.0.0a1)), and the current master branch (4 commits later: 8c1ee8329ecbff28f52b4540b5ad5f26c50b421e).

My docker versions:

```
$ docker -v
Docker version 18.03.0-ce, build 0520e24
$ docker-compose -v
docker-compose version 1.20.1, build 5d8c71b
```

### What, exactly, did you do to get to the point where you got stuck? Describe all the steps so we can get there too. 

I'm starting the BDB server from the source dir with:

```
docker container rm --force --volumes $(docker container ls --quiet --all)  
docker-compose build bigchaindb
docker-compose run -d bdb
```

Using the JS BDB driver `v4.0.0`, I am: 
- creating an asset pool with 10^18 tokens
- transferring tokens to (demo) users
- transferring tokens between users
- every time I transfer, I collect all UTXOs for that user into the inputs of the transaction
- **this works fine when the user has one or maybe a few UTXOs, but consistently fails when we are gathering 5+ UTXOs into a single transaction's inputs**

### Show what actually happened.

Here are the 5 UTXs in one case -- in the format `[ [ tx1, output_index ], [ tx2, output_index ] ... ]`:

```json

    [
        [
            {
                "inputs": [
                    {
                        "owners_before": [
                            "Bk2BioQgWTp77M7YD5fqy5R5AFYmqMCDpoTxqiJfcJzZ"
                        ],
                        "fulfills": {
                            "transaction_id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d",
                            "output_index": 0
                        },
                        "fulfillment": "pGSAIJ-aLwqjNjfRk8S2WzMqXZs7icj1NADyjAU_ccTQh-MmgUBnEnqgh4fzwEPfU3iJdD8qSvGAftKyVXgqaZkeFi_e9dj1y-43hN4uEMGbrtyI_hAFviwVFtoe-eaxpfXGTAEO"
                    }
                ],
                "outputs": [
                    {
                        "public_keys": [
                            "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                            },
                            "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "1000000"
                    },
                    {
                        "public_keys": [
                            "Bk2BioQgWTp77M7YD5fqy5R5AFYmqMCDpoTxqiJfcJzZ"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "Bk2BioQgWTp77M7YD5fqy5R5AFYmqMCDpoTxqiJfcJzZ"
                            },
                            "uri": "ni:///sha-256;ns6Kpex7Z9MpALWkaDI6aVBx5ty6Qc8LY7Q1iDW9YXg?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "999999999999000000"
                    }
                ],
                "operation": "TRANSFER",
                "metadata": {
                    "token": "ZPWA3"
                },
                "asset": {
                    "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
                },
                "version": "2.0",
                "id": "9c3665af349891861701a095d815c9c58e65beea77d5b4f824629fab8cafb16a"
            },
            0
        ],
        [
            {
                "inputs": [
                    {
                        "owners_before": [
                            "619SJWs16VE49JjJnQvXoY8JccoHKxdkdUgmjUyKMyYQ"
                        ],
                        "fulfills": {
                            "transaction_id": "7fd55d16bf4d7653f69fd3a0936f337a0ce318206fae2ec5aa69c73ef37d4e71",
                            "output_index": 0
                        },
                        "fulfillment": "pGSAIEpT-TiZ8emsNwwKuCKVq_rK0ElTIbQUJwaxlPNNDXf9gUBNfuZg68I8TBe6vxiysgLmaZJe-6veFZRHJYoVTb6ChdiScCS3w9rbiej72JEEDdwGaIEq6MbNoflL7ouxFbUM"
                    }
                ],
                "outputs": [
                    {
                        "public_keys": [
                            "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                            },
                            "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "50"
                    },
                    {
                        "public_keys": [
                            "619SJWs16VE49JjJnQvXoY8JccoHKxdkdUgmjUyKMyYQ"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "619SJWs16VE49JjJnQvXoY8JccoHKxdkdUgmjUyKMyYQ"
                            },
                            "uri": "ni:///sha-256;HS5KO5j16sbCBqbOP9rTOfClmiBO5_DLmnx37tWasek?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "25"
                    }
                ],
                "operation": "TRANSFER",
                "metadata": {
                    "token": "ZPWA3"
                },
                "asset": {
                    "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
                },
                "version": "2.0",
                "id": "879d23682b8658517b5a3a1126dd9226ffd77dcc78e239a43d210ce6b5cc2200"
            },
            0
        ],
        [
            {
                "inputs": [
                    {
                        "owners_before": [
                            "DadQTQsEqzje9q9r8WrW8PhmrcAg6q9AschN3JXS9Mui"
                        ],
                        "fulfills": {
                            "transaction_id": "9248e1b856d0d9f2314ee1be28e1452f368021782dec6cbf113c61f3f6aec463",
                            "output_index": 1
                        },
                        "fulfillment": "pGSAILrpkokn9vmaW8zIllS51EWHODaIDXqAs3DTD4wA2YORgUD4woG5pIEMGFiWSMB3_NTQ_J6Ejtr2-Sd0PM2ImcCSDPBHSNqPiWdyzk_CXPfv8nMGvAV5W7EX4HQ4d50zJXEM"
                    }
                ],
                "outputs": [
                    {
                        "public_keys": [
                            "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                            },
                            "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "10"
                    },
                    {
                        "public_keys": [
                            "DadQTQsEqzje9q9r8WrW8PhmrcAg6q9AschN3JXS9Mui"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "DadQTQsEqzje9q9r8WrW8PhmrcAg6q9AschN3JXS9Mui"
                            },
                            "uri": "ni:///sha-256;4NZbp4IQDZ-qw77dXDbhqtd14qqfn8EGf8tkHdh6inc?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "77"
                    }
                ],
                "operation": "TRANSFER",
                "metadata": {
                    "token": "ZPWA3"
                },
                "asset": {
                    "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
                },
                "version": "2.0",
                "id": "ec1899f2ccb8fee34e712c713de7bf10047e4ed51764e4112aa3d1a3e11c885f"
            },
            0
        ],
        [
            {
                "inputs": [
                    {
                        "owners_before": [
                            "FN2rF7founsXmbhowj4JHP7jFAfPukWskTUatXURpGGt"
                        ],
                        "fulfills": {
                            "transaction_id": "e82db8662a160e4f615f2805ca43598576996b11ebe234d9e70e038dab5da615",
                            "output_index": 1
                        },
                        "fulfillment": "pGSAINVm55eaRf2XuHO_vW4F6TlMbl4sF1KE-9CyKoKHuQltgUDCLznarfMWk87voA0xdOeD923fmjwF1ZOARnsw2whNrRjKb_ep_EcXQenPHgjsCokdV8gD6hCpMhE4XRqvasMI"
                    }
                ],
                "outputs": [
                    {
                        "public_keys": [
                            "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                            },
                            "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "10"
                    },
                    {
                        "public_keys": [
                            "FN2rF7founsXmbhowj4JHP7jFAfPukWskTUatXURpGGt"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "FN2rF7founsXmbhowj4JHP7jFAfPukWskTUatXURpGGt"
                            },
                            "uri": "ni:///sha-256;_Opd6GQC62pVXxYeFr9CgC9E49iy9IxOwZciX0B_Omo?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "36"
                    }
                ],
                "operation": "TRANSFER",
                "metadata": {
                    "token": "ZPWA3"
                },
                "asset": {
                    "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
                },
                "version": "2.0",
                "id": "cdeff8a6e329c5bd6e48d5855861b866961ea5cc21b632b8b04493de28758b9a"
            },
            0
        ],
        [
            {
                "inputs": [
                    {
                        "owners_before": [
                            "41eYz8YN6dFeEGmg2HJoGeHXXerD8jaHh1mA6M52Anez"
                        ],
                        "fulfills": {
                            "transaction_id": "fe2d1d7683d63825abf4aea5f598550892e93a9098fd7b0365572496196cb62d",
                            "output_index": 0
                        },
                        "fulfillment": "pGSAICy9hTYVJihkG6pLLr4dNSm8b_SkpAPOWLDaYFRUwHlngUC-2DWkDdtlDK_ieoWC_bjmuyKRKvytoXyiWSdZDLpdsp0lkNXBbGSdoGkCJnrXeJo1Zl30aqd47GkBkCG0w3oC"
                    }
                ],
                "outputs": [
                    {
                        "public_keys": [
                            "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                            },
                            "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "27"
                    },
                    {
                        "public_keys": [
                            "41eYz8YN6dFeEGmg2HJoGeHXXerD8jaHh1mA6M52Anez"
                        ],
                        "condition": {
                            "details": {
                                "type": "ed25519-sha-256",
                                "public_key": "41eYz8YN6dFeEGmg2HJoGeHXXerD8jaHh1mA6M52Anez"
                            },
                            "uri": "ni:///sha-256;FYr6AiBntYFQPP1LXY39PmitvzeXJSdizmKYKkpT_7E?fpt=ed25519-sha-256&cost=131072"
                        },
                        "amount": "37"
                    }
                ],
                "operation": "TRANSFER",
                "metadata": {
                    "token": "ZPWA3"
                },
                "asset": {
                    "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
                },
                "version": "2.0",
                "id": "05092e4fe85627019da69e50c3dd7eee1544d4341b0da9847cc800e0c329681c"
            },
            0
        ]
    ]
```

We do a little transforming and then call `makeTransferTransaction(...)`:

```js
    const inputs = unspent_transactions.map(([tx, output_index]) => {
      return { tx, output_index }
    })
    // ...
    const txTransfer = driver.Transaction.makeTransferTransaction(inputs, outputs, metadata)
```

which returns the unsigned transaction:

```json
{
    "id": null,
    "operation": "TRANSFER",
    "outputs": [
        {
            "condition": {
                "details": {
                    "type": "ed25519-sha-256",
                    "public_key": "D5u6FxVjCxgDyFMGTQ5M8BAvYWpnBW7thz31Y4BtKXtX"
                },
                "uri": "ni:///sha-256;fNL4G2pILtD4YmFKUP5XJGT_Dg0cRfOnaWh0QSotM3E?fpt=ed25519-sha-256&cost=131072"
            },
            "amount": "36",
            "public_keys": [
                "D5u6FxVjCxgDyFMGTQ5M8BAvYWpnBW7thz31Y4BtKXtX"
            ]
        },
        {
            "condition": {
                "details": {
                    "type": "ed25519-sha-256",
                    "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                },
                "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
            },
            "amount": "1000061",
            "public_keys": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        }
    ],
    "inputs": [
        {
            "fulfillment": null,
            "fulfills": {
                "output_index": 0,
                "transaction_id": "9c3665af349891861701a095d815c9c58e65beea77d5b4f824629fab8cafb16a"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": null,
            "fulfills": {
                "output_index": 0,
                "transaction_id": "879d23682b8658517b5a3a1126dd9226ffd77dcc78e239a43d210ce6b5cc2200"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": null,
            "fulfills": {
                "output_index": 0,
                "transaction_id": "ec1899f2ccb8fee34e712c713de7bf10047e4ed51764e4112aa3d1a3e11c885f"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": null,
            "fulfills": {
                "output_index": 0,
                "transaction_id": "cdeff8a6e329c5bd6e48d5855861b866961ea5cc21b632b8b04493de28758b9a"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": null,
            "fulfills": {
                "output_index": 0,
                "transaction_id": "05092e4fe85627019da69e50c3dd7eee1544d4341b0da9847cc800e0c329681c"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        }
    ],
    "metadata": {
        "token": "ZPWA3"
    },
    "asset": {
        "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
    },
    "version": "2.0"
}
```

Then we sign with the private key, in this case `H6YxYVQZUW67dQxdZJGY7VzdW5fUFfHtkzK7iQqJiHD7` (random key from demo user).

```js
    const private_keys = Array(inputs.length).fill(private_key)
    let txSigned = driver.Transaction.signTransaction(txTransfer, ...private_keys)
```

...and get back a signed transaction:

```json
{
    "id": "725e3ad7fcdf603e3720f94d09939b8eb0f45789423231ce3907d1f064946309",
    "operation": "TRANSFER",
    "outputs": [
        {
            "condition": {
                "details": {
                    "type": "ed25519-sha-256",
                    "public_key": "D5u6FxVjCxgDyFMGTQ5M8BAvYWpnBW7thz31Y4BtKXtX"
                },
                "uri": "ni:///sha-256;fNL4G2pILtD4YmFKUP5XJGT_Dg0cRfOnaWh0QSotM3E?fpt=ed25519-sha-256&cost=131072"
            },
            "amount": "36",
            "public_keys": [
                "D5u6FxVjCxgDyFMGTQ5M8BAvYWpnBW7thz31Y4BtKXtX"
            ]
        },
        {
            "condition": {
                "details": {
                    "type": "ed25519-sha-256",
                    "public_key": "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
                },
                "uri": "ni:///sha-256;jMWj1B1UtcqNzwLBis7hVV22kaXqzhwribK-uFCfQ8I?fpt=ed25519-sha-256&cost=131072"
            },
            "amount": "1000061",
            "public_keys": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        }
    ],
    "inputs": [
        {
            "fulfillment": "pGSAINbm6mW3crm5Ae7486D0pkO7UmjcLV-BoyvtN0BWaBENgUCpn2R1wiBa9IC0oXqEU3M7-jP-RwakZAp3dZchcVLkvGiggbzkFIWDXrHtYXr_4mjAwpKOgMWJV7MEBVHHMrsG",
            "fulfills": {
                "output_index": 0,
                "transaction_id": "9c3665af349891861701a095d815c9c58e65beea77d5b4f824629fab8cafb16a"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": "pGSAINbm6mW3crm5Ae7486D0pkO7UmjcLV-BoyvtN0BWaBENgUA2zxIrnynGNVur2bS4ZNJt1QZJKAp0PaA2p1POSSNjM_O-1hhbIG7bw9ZrOkHUx2E5XXMZmxO1bZ29kXQaIuYP",
            "fulfills": {
                "output_index": 0,
                "transaction_id": "879d23682b8658517b5a3a1126dd9226ffd77dcc78e239a43d210ce6b5cc2200"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": "pGSAINbm6mW3crm5Ae7486D0pkO7UmjcLV-BoyvtN0BWaBENgUA-VJYVxeC8R4yIJ_YZSDu8X8LuoSS1x9k2k64fdrx4v0Rki8ZerfRrohYR2ERXNUCLfVDbkLXAf3YrMpDXeSIG",
            "fulfills": {
                "output_index": 0,
                "transaction_id": "ec1899f2ccb8fee34e712c713de7bf10047e4ed51764e4112aa3d1a3e11c885f"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": "pGSAINbm6mW3crm5Ae7486D0pkO7UmjcLV-BoyvtN0BWaBENgUAA1IMyNkOFmvkuAFBA2mJxMaEHcY3HpE88PpUM35MiA7K3cBkjaFL_wSiwOCRKPJksnRWIPYNOl9GJV3Y6lPEB",
            "fulfills": {
                "output_index": 0,
                "transaction_id": "cdeff8a6e329c5bd6e48d5855861b866961ea5cc21b632b8b04493de28758b9a"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        },
        {
            "fulfillment": "pGSAINbm6mW3crm5Ae7486D0pkO7UmjcLV-BoyvtN0BWaBENgUDNV1rvklvXUvzxf5ReJfeibSle9LOnGQGi2Qm0vzYbUB0Z-hBniPFaVcdZFZ4d3-KPgiTP-Cc0SAr3lEMQmP0L",
            "fulfills": {
                "output_index": 0,
                "transaction_id": "05092e4fe85627019da69e50c3dd7eee1544d4341b0da9847cc800e0c329681c"
            },
            "owners_before": [
                "FTtUGxa79FeveRoK3MHP7Hy5JxrAPqLmF6xxtgVewcH2"
            ]
        }
    ],
    "metadata": {
        "token": "ZPWA3"
    },
    "asset": {
        "id": "4e26752bbf1064ef62cc80d6ce298986a3406bfb8e3671ba5fec519940e5470d"
    },
    "version": "2.0"
}
```

we ship this off to BDB server with:

```js
    return conn.postTransactionCommit(txSigned)
    .then(retrievedTx => {
      console.log({retrievedTx})
    })
```

...but no response from the server.  After some seconds, the docker compose logs say:

```
bigchaindb_1   | [2018-04-06 05:56:53] [CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:19) (webapi     - pid: 13)
bigchaindb_1   | [2018-04-06 05:56:53] [INFO] (gunicorn.error) Worker exiting (pid: 19) (webapi     - pid: 19)
mongodb_1      | 2018-04-06T05:56:53.641+0000 I -        [conn5] end connection 172.19.0.4:38840 (4 connections now open)
mongodb_1      | 2018-04-06T05:56:53.641+0000 I -        [conn6] end connection 172.19.0.4:38842 (4 connections now open)
bigchaindb_1   | [2018-04-06 05:56:53] [INFO] (gunicorn.error) Booting worker with pid: 744 (webapi     - pid: 744)
```

Some more seconds later, our NodeJS layer says:

```
{ FetchError: request to http://127.0.0.1:9984/api/v1/transactions?mode=commit failed, reason: socket hang up
    at ClientRequest.<anonymous> (/[...snip...]/node_modules/fetch-ponyfill/node_modules/node-fetch/lib/index.js:1393:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketOnEnd (_http_client.js:421:9)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'request to http://127.0.0.1:9984/api/v1/transactions?mode=commit failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```

At this point, BDB is unresponsive; I restart the docker containers from scratch to get it back.

I have tested this repeatedly with consistent results.  I can do hundreds of transfers as fast as I can create them with the same code, as long as just one or a few UTXOs are used as inputs.  But at 5+ UTXOs, I get this behavior every time.

### Provide details to convince us that it matters to you.

We are evaluating BDB for my financial services client; solving this is critical to us moving forward with BDB.

**Comment by kansi** [comment]
@harlantwood This seem like a very crucial issue. We will try to reproduce and fix this asap. It would be great if you could share the js script that produces this issue? that way we can directly move to fixing the issue.

**Comment by harlantwood** [comment]
Sure, I will get you a repro script later today.

**Comment by harlantwood** [comment]
Repro:

```
git clone git@github.com:9bea877e5b308ac61ab9d22e23f1f1db.git repro
cd repro
```

if needed, change BDB server URL in `repro.js`

```
yarn && yarn repro
```

All keypairs are of course random and not used anywhere else.

This is certainly not the simplest dataset (`repro.json`) that could repro the bug, but it works -- at least on my server.  LMK how it goes for you.

**Comment by kansi** [comment]
@harlantwood Thanks for the effort! really appreciate it.

**Comment by kansi** [comment]
@harlantwood I was able to reproduce the bug you described (thanks to your scripts). From initial debugging it seems that the bug is on Tendermint's side. We are planing to fix the same soon in the upcoming releases.

**Comment by harlantwood** [comment]
Thanks @kansi.  Will you be upgrading to a newer tendermint?  

Would be good for this script or something simpler that reproduces the same bug to make it into the test suite for BDB. For that matter, not just 5 inputs, but... some large number.  And if TM can handle only limited inputs (hopefully not), we should enforce that on the BDB server side.

**Comment by kansi** [comment]
@harlantwood Yes, that is our highest priority. But we wish to ensure that migration is well tested before we make a release.

> Would be good for this script or something simpler that reproduces the same bug to make it into the test suite for BDB. 

Yup, I have created an issue regarding the same #2197

**Comment by kansi** [comment]
@harlantwood This issue has been fixed in `master` now. Will be available in Alpha-3 release.

**Comment by ttmc** [comment]
Note: The fix includes some changes made to an external package (`py-abci`) and those changes _haven't_ yet been merged into the master branch or current release of `py-abci`.
