### ISSUE TITLE
BigchainDB master branch not working

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#2211]
Running BigchainDB latest master branch by doing `make start` and trying to insert some transaction I get this error:

```
{ message: 'HTTP Error: Requested page not reachable',
  status: '500 INTERNAL SERVER ERROR',
  requestURI: 'http://localhost:9984/api/v1/transactions' }

```

The logs of bigchaindb are:

```
bigchaindb_1   | [2018-04-16 13:31:13] [DEBUG] (urllib3.connectionpool) Starting new HTTP connection (1): tendermint (webapi     - pid: 20)
bigchaindb_1   | [2018-04-16 13:31:13] [DEBUG] (urllib3.connectionpool) http://tendermint:46657 "POST / HTTP/1.1" 200 190 (webapi     - pid: 20)
bigchaindb_1   | [2018-04-16 13:31:13] [DEBUG] (bigchaindb.tendermint.core) check_tx: b'{"inputs": [{"owners_before": ["GEkKQDKFf5qzi7WwY2VzwBd3VyLhCu1aSaWjSAU7dCpo"], "fulfills": null, "fulfillment": "pGSAIOJk1VhJDuZGIQAy759uSMZ-XV-kMmb8El0ekMjZDVYAgUAnYFdjXAQyuHzzzA4I3Xn7gSGsx_qnDZ55Zd8kxzrEOa0iCPEjrDzDeOsBhh2bnZKYvv-jSJ9v2c5ITsoMdDMI"}], "outputs": [{"public_keys": ["GEkKQDKFf5qzi7WwY2VzwBd3VyLhCu1aSaWjSAU7dCpo"], "condition": {"details": {"type": "ed25519-sha-256", "public_key": "GEkKQDKFf5qzi7WwY2VzwBd3VyLhCu1aSaWjSAU7dCpo"}, "uri": "ni:///sha-256;0Xhj94Y2r5a-TRmM5NlIR6HDsC62TAYl-RSpJt1WJ7M?fpt=ed25519-sha-256&cost=131072"}, "amount": "1"}], "operation": "CREATE", "metadata": {"metadata": "sdfs"}, "asset": {"data": {"timeStamp": "\\"2018-04-16T13:31:13.053Z\\"", "example": "simpleAsseet"}}, "version": "2.0", "id": "6005977fed8595715e9b28ea27fe4e81acd29c9d5c9684e10757f64580d9ce2c"}' (MainProcess - pid: 6)
bigchaindb_1   | [2018-04-16 13:31:13,178] ERROR in app: Exception on /api/v1/transactions [POST]
bigchaindb_1   | Traceback (most recent call last):
bigchaindb_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
bigchaindb_1   |     rv = self.dispatch_request()
bigchaindb_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
bigchaindb_1   |     return self.view_functions[rule.endpoint](**req.view_args)
bigchaindb_1   |   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
bigchaindb_1   |     resp = resource(*args, **kwargs)
bigchaindb_1   |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
bigchaindb_1   |     return self.dispatch_request(*args, **kwargs)
bigchaindb_1   |   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
bigchaindb_1   |     resp = meth(*args, **kwargs)
bigchaindb_1   |   File "/usr/src/app/bigchaindb/web/views/transactions.py", line 93, in post
bigchaindb_1   |     status_code, message = bigchain.write_transaction(tx_obj, mode)
bigchaindb_1   |   File "/usr/src/app/bigchaindb/tendermint/lib.py", line 61, in write_transaction
bigchaindb_1   |     return self._process_post_response(response, mode)
bigchaindb_1   |   File "/usr/src/app/bigchaindb/tendermint/lib.py", line 64, in _process_post_response
bigchaindb_1   |     result = response['result']
bigchaindb_1   | TypeError: 'Response' object is not subscriptable
bigchaindb_1   | [2018-04-16 13:31:13] [DEBUG] (gunicorn.error) POST /api/v1/transactions (webapi     - pid: 20)
bigchaindb_1   | [2018-04-16 13:31:13] [DEBUG] (bigchaindb.tendermint.core) check_tx: VALID (MainProcess - pid: 6)

```

I can also see in the logs

**Comment by manolodewiner** [comment]
After some commits pushed yesterday, the issue seems solved. I'll close it, if I face it again, we could reopen it

**Comment by amankakar** [comment]
Object {message: "HTTP Error: Requested page not reachable", status: "500 INTERNAL SERVER ERROR", requestURI: "http://localhost:9984/api/v1/transactions?mode=com…"}
face same error with follwoing bigchaindb and javascript driver versions:
bigchaindb version 2 
bigchaindb-driver 4.0.0

**Comment by koakh** [comment]
same error follow tutorial

bigchaindb 2.0.0b9
bigchaindb-driver": "^4.1.0,

```
{ message: 'HTTP Error: Requested page not reachable',
  status: '500 INTERNAL SERVER ERROR',
  requestURI: 'https://cloud.koakh.com/api/v1/transactions?mode=commit' }
```

```
*                                                                          *
*   Listening to client connections on: localhost:9984                     *
*                                                                          *
****************************************************************************
 (MainProcess - pid: 866)
[2019-07-31 22:46:34] [INFO] (abci.app)  ABCIServer started on port: 26658 (MainProcess - pid: 866)
[2019-07-31 22:46:37] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:42308 ... (MainProcess - pid: 866)
[2019-07-31 22:46:37] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:42310 ... (MainProcess - pid: 866)
[2019-07-31 22:46:37] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:42312 ... (MainProcess - pid: 866)
[2019-07-31 22:46:37] [INFO] (bigchaindb.core) Tendermint version: 0.22.8-40d6dc2e (MainProcess - pid: 866)
[2019-07-31 22:47:36] [ERROR] (bigchaindb.web.server) Exception on /api/v1/transactions [POST] (bigchaindb_webapi - pid: 1143)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

```
  "dependencies": {
    "bigchaindb-driver": "^4.1.0",
    "bip39": "^2.5.0",
  },
```

thanks

**Comment by amankakar** [comment]
i have resolved this error by installing monit and then execute follwoing commands.
`sudo apt install monit
bigchaindb-monit-config
monit -d 1
bigchaindb -y configure mongodb
 bigchaindb start`
i don't know why this error occur but bigchaindb document say that install Monit, a small open-source utility for managing and monitoring Unix processes. BigchainDB and Tendermint are managed together, because if BigchainDB is stopped (or crashes) and is restarted, Tendermint won’t try reconnecting to it. (That’s not a bug. It’s just how Tendermint works.)

**Comment by mohit-deepgrid** [comment]
Even for this to work I had to reset Tendermint with **tendermint unsafe_reset_all** but eventually my first test case worked. Thanks @amankakar !
