### ISSUE TITLE
Problem: 'result'  and 'check_tx' Keyerror when POST'ing transactions to BigchainDB test network

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#2217]
- What computer are you on (hardware)?
  - N/A, [BigchainDB test network](https://test.bigchaindb.com/).
- What operating system are you using, including version. e.g. Ubuntu 14.04? Fedora 23?
  - N/A
- What version of BigchainDB software were you using? Is that the latest version?
  - master

## Description
BigchainDB container on a test network node crashes when somebody POSTs a transaction and we get the following traceback in the logs:

```
[2018-04-17 09:54:54] [DEBUG] (urllib3.connectionpool) http://tm-instance-1:46657 "POST / HTTP/1.1" 200 270 (webapi     - pid: 25)
[2018-04-17 09:54:54] [DEBUG] (bigchaindb.tendermint.lib) {'jsonrpc': '2.0', 'id': 'd5c5a2dc-451b-446e-9f62-b56f23bc90b8', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'Error broadcasting transaction: read tcp 10.244.1.16:54116->10.244.2.50:46658: read: connection reset by peer'}} (webapi     - pid: 25)
[2018-04-17 09:54:54,149] ERROR in app: Exception on /api/v1/transactions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/web/views/transactions.py", line 93, in post
    status_code, message = bigchain.write_transaction(tx_obj, mode)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 61, in write_transaction
    return self._process_post_response(response.json(), mode)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 65, in _process_post_response
    result = response['result']
KeyError: 'result'
[2018-04-17 09:54:57] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 25)
[2018-04-17 09:54:59] [DEBUG] (gunicorn.error) POST /api/v1/transactions (webapi     - pid: 25)
[2018-04-17 09:55:29] [CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:25) (webapi     - pid: 14)
[2018-04-17 09:55:29] [INFO] (gunicorn.error) Worker exiting (pid: 25) (webapi     - pid: 25)
[2018-04-17 09:55:29] [INFO] (gunicorn.error) Booting worker with pid: 28 (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 28)
[2018-04-17 09:55:29] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:32] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:35] [DEBUG] (gunicorn.error) POST /api/v1/transactions/ (webapi     - pid: 28)
[2018-04-17 09:55:35] [DEBUG] (bigchaindb.config_utils) System already configured, skipping autoconfiguration (webapi     - pid: 28)
[2018-04-17 09:55:35] [DEBUG] (bigchaindb.backend.connection) Connection: <class 'bigchaindb.backend.localmongodb.connection.LocalMongoDBConnection'> (webapi     - pid: 28)
[2018-04-17 09:55:35] [INFO] (bigchaindb.backend.mongodb.connection) Connecting to MongoDB over TLS/SSL... (webapi     - pid: 28)
[2018-04-17 09:55:35] [DEBUG] (urllib3.connectionpool) Starting new HTTP connection (1): tm-instance-1 (webapi     - pid: 28)
[2018-04-17 09:55:35] [DEBUG] (urllib3.connectionpool) http://tm-instance-1:46657 "POST / HTTP/1.1" 200 190 (webapi     - pid: 28)
[2018-04-17 09:55:35] [DEBUG] (bigchaindb.tendermint.lib) {'jsonrpc': '2.0', 'id': 'fd8ae52b-49e5-4b41-9190-e41c545c4f3d', 'result': {'code': 0, 'data': '', 'log': '', 'hash': '1FB834209D22F31D0EAC9FD4B5519318131455C2'}} (webapi     - pid: 28)
[2018-04-17 09:55:37] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:47] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:47] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 28)
[2018-04-17 09:55:47] [DEBUG] (gunicorn.error) POST /api/v1/transactions (webapi     - pid: 28)
[2018-04-17 09:55:47] [DEBUG] (urllib3.connectionpool) Starting new HTTP connection (1): tm-instance-1 (webapi     - pid: 28)
[2018-04-17 09:55:47] [DEBUG] (urllib3.connectionpool) http://tm-instance-1:46657 "POST / HTTP/1.1" 200 221 (webapi     - pid: 28)
[2018-04-17 09:55:47] [DEBUG] (bigchaindb.tendermint.lib) {'jsonrpc': '2.0', 'id': '56c49000-07f2-4891-a785-49e3cb729e82', 'result': {'code': 3, 'data': '', 'log': 'Duplicate transaction (ignored)', 'hash': '1FB834209D22F31D0EAC9FD4B5519318131455C2'}} (webapi     - pid: 28)
[2018-04-17 09:55:47,690] ERROR in app: Exception on /api/v1/transactions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/web/views/transactions.py", line 93, in post
    status_code, message = bigchain.write_transaction(tx_obj, mode)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 61, in write_transaction
    return self._process_post_response(response.json(), mode)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 67, in _process_post_response
    status_code = result['check_tx']['code']
KeyError: 'check_tx'
[2018-04-17 09:55:52] [DEBUG] (gunicorn.error) POST /api/v1/transactions/ (webapi     - pid: 28)
[2018-04-17 09:56:22] [CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:28) (webapi     - pid: 14)
[2018-04-17 09:56:22] [INFO] (gunicorn.error) Worker exiting (pid: 28) (webapi     - pid: 28)
[2018-04-17 09:56:22] [INFO] (gunicorn.error) Booting worker with pid: 31 (webapi     - pid: 31)
[2018-04-17 09:56:22] [DEBUG] (gunicorn.error) GET /api/v1/transactions/2ca4412f42940ea4c9a07a4b875749a00427b706e39856dedbfec736059dcdad (webapi     - pid: 31)
[2018-04-17 09:56:22] [DEBUG] (bigchaindb.config_utils) System already configured, skipping autoconfiguration (webapi     - pid: 31)
[2018-04-17 09:56:22] [DEBUG] (bigchaindb.backend.connection) Connection: <class 'bigchaindb.backend.localmongodb.connection.LocalMongoDBConnection'> (webapi     - pid: 31)
[2018-04-17 09:56:22] [INFO] (bigchaindb.backend.mongodb.connection) Connecting to MongoDB over TLS/SSL... (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET /api/v1/transactions/2ca4412f42940ea4c9a07a4b875749a00427b706e39856dedbfec736059dcdad (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET /api/v1/assets (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) POST /api/v1/transactions/ (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (urllib3.connectionpool) Starting new HTTP connection (1): tm-instance-1 (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (urllib3.connectionpool) http://tm-instance-1:46657 "POST / HTTP/1.1" 200 270 (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (bigchaindb.tendermint.lib) {'jsonrpc': '2.0', 'id': '863a45d5-b663-40c2-871b-797008bea2b8', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'Error broadcasting transaction: read tcp 10.244.1.16:54116->10.244.2.50:46658: read: connection reset by peer'}} (webapi     - pid: 31)
[2018-04-17 09:56:23,481] ERROR in app: Exception on /api/v1/transactions/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/web/views/transactions.py", line 93, in post
    status_code, message = bigchain.write_transaction(tx_obj, mode)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 61, in write_transaction
    return self._process_post_response(response.json(), mode)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 65, in _process_post_response
    result = response['result']
KeyError: 'result'
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) Ignoring EPIPE (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 31)
[2018-04-17 09:56:23] [DEBUG] (gunicorn.error) GET /api/v1/transactions (webapi     - pid: 31)
```

The transactions are stored in the system,  but the BigchainDB server crashes and we need to restart both Tendermint and BigchainDB to get into a running state again. The stored transaction can be retrieved after the restart.

Script I am using to POST the transactions: 
`bigchaindb-driver`: `master`

```
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
from time import sleep
from sys import exit

auth_headers = {'app_id': 'my-app-id', 'app_key': 'my-app-key'}
bdb = BigchainDB('https://test.bigchaindb.com', headers=auth_headers)

alice, bob = generate_keypair(), generate_keypair()

bicycle_asset = {
    'data': {
        'bicycle': {
            'serial_number': 'abcd1234',
            'manufacturer': 'bkfab'
        },
    },
}

bicycle_asset_metadata = {
    'planet': 'earth'
}

prepared_creation_tx = bdb.transactions.prepare(
    operation='CREATE',
    signers=alice.public_key,
    asset=bicycle_asset,
    metadata=bicycle_asset_metadata
)

fulfilled_creation_tx = bdb.transactions.fulfill(
    prepared_creation_tx,
    private_keys=alice.private_key
)

sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
import json
print(json.dumps(fulfilled_creation_tx))
sleep(10)
txid = fulfilled_creation_tx['id']
print(txid)
asset_id = txid

transfer_asset = {
    'id': asset_id
}

output_index = 0
output = fulfilled_creation_tx['outputs'][output_index]

transfer_input = {
    'fulfillment': output['condition']['details'],
    'fulfills': {
        'output_index': output_index,
        'transaction_id': fulfilled_creation_tx['id']
    },
    'owners_before': output['public_keys']
}

prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=bob.public_key,
)

fulfilled_transfer_tx = bdb.transactions.fulfill(
    prepared_transfer_tx,
    private_keys=alice.private_key,
)

print(json.dumps(fulfilled_transfer_tx))
sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)

print("Is Bob the owner?",
    sent_transfer_tx['outputs'][0]['public_keys'][0] == bob.public_key)

print("Was Alice the previous owner?",
    fulfilled_transfer_tx['inputs'][0]['owners_before'][0] == alice.public_key)
```

**Note**: `WORKER_TIMEOUT` implies a crash.

**Comment by vrde** [comment]
Might be related to #2198.

**Comment by manolodewiner** [comment]
Is same issue I was getting https://github.com/bigchaindb/bigchaindb/issues/2211. I am facing it again

**Comment by vrde** [comment]
I see two different errors here.

# Connection error
```
[2018-04-17 09:54:54] [DEBUG] (bigchaindb.tendermint.lib) {'jsonrpc': '2.0', 'id': 'd5c5a2dc-451b-446e-9f62-b56f23bc90b8', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'Error broadcasting transaction: read tcp 10.244.1.16:54116->10.244.2.50:46658: read: connection reset by peer'}} (webapi     - pid: 25)
[2018-04-17 09:54:54,149] ERROR in app: Exception on /api/v1/transactions [POST]
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 65, in _process_post_response
    result = response['result']
KeyError: 'result'
```

Pretty print the error:
```json
{
  "jsonrpc": "2.0",
  "id": "d5c5a2dc-451b-446e-9f62-b56f23bc90b8",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Error broadcasting transaction: read tcp 10.244.1.16:54116->10.244.2.50:46658: read: connection reset by peer"
  }
}
```

I don't know how the network setup is, and I don't know if Tendermint can recover from that. We might be lucky :8ball:  updating to Tendermint `0.19`.

# Double spend error
```
[2018-04-17 09:55:47] [DEBUG] (bigchaindb.tendermint.lib) {'jsonrpc': '2.0', 'id': '56c49000-07f2-4891-a785-49e3cb729e82', 'result': {'code': 3, 'data': '', 'log': 'Duplicate transaction (ignored)', 'hash': '1FB834209D22F31D0EAC9FD4B5519318131455C2'}} (webapi     - pid: 28)
[2018-04-17 09:55:47,690] ERROR in app: Exception on /api/v1/transactions [POST]
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/tendermint/lib.py", line 67, in _process_post_response
    status_code = result['check_tx']['code']
KeyError: 'check_tx'
```

Pretty print the json:
```json
{
  "jsonrpc": "2.0",
  "id": "56c49000-07f2-4891-a785-49e3cb729e82",
  "result": {
    "code": 3,
    "data": "",
    "log": "Duplicate transaction (ignored)",
    "hash": "1FB834209D22F31D0EAC9FD4B5519318131455C2"
  }
}
```

This is something we can easily manage ourself.

**Comment by vrde** [comment]
The return codes are described in [`tendermint/mempool.go`](https://github.com/tendermint/tendermint/blob/v0.12.1/rpc/core/mempool.go).

**Comment by vrde** [comment]
Since we still have the problem `"Error broadcasting transaction"`, I've reopened this issue.

**Comment by manolodewiner** [comment]
After doing some testing again, this problem seems solved for me :)
