### ISSUE TITLE
Not able to run BigchainDB using docker-compose up from master branch

### ISSUE THREAD

**Issue by gautamdhameja** [bigchaindb/bigchaindb#2236]
Steps:

1. clone repository
2. cd in the repository root directory
3. docker-compose up

After a few minutes, the build process ends with the following error.

```
Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytest-runner/: [Errno 107] Transport endpoint is not connected -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gesz0xln/cryptoconditions/setup.py", line 84, in <module>
        'docs': docs_require,
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gesz0xln/cryptoconditions/
ERROR: Service 'bigchaindb' failed to build: The command '/bin/sh -c pip install --no-cache-dir -e .[dev]' returned a non-zero code: 1
```

**Comment by vrde** [comment]
Hey Gautam, seems like the connection dropped while downloading a package:
```
Download error on https://pypi.python.org/simple/pytest-runner/:
    [Errno 107] Transport endpoint is not connected -- Some packages may not be found!
```

Restarting the building process should work. On a side-note, instead of using `docker-compose` directly I suggest you to use [`make run`](https://github.com/bigchaindb/bigchaindb#run-and-test-bigchaindb-from-the-master-branch).
