### ISSUE TITLE
Simple create asset fails, BDB log says worker timeout

### ISSUE THREAD

**Issue by agwego** [bigchaindb/bigchaindb#2273]
I've attached a simple test program, see the log output and execution results below.

Hardware AMD Athlon(tm) II X4 640 Processor, 16 GB RAM
Running Fedora release 17 (Beefy Miracle)
Virtual machine (VBOX 5.1) running Ubuntu 16.04.3 LTS with 3 GB RAM, vm resides on a 10k velociraptor
Bigchaindb: alpha-3
Python Driver: bigchaindb_driver-0.5.0a4

Execution output:
```
$ python3 bdb2_test.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bdb2_test.py", line 59, in <module>
    sent_creation_tx = bdb.transactions.send( transactionSigned )
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/driver.py", line 332, in send
    headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/connection.py", line 48, in request
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Log output from BDB:

```
bigchaindb_1   | [2018-05-08 20:04:29] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 2272)
bigchaindb_1   | [2018-05-08 20:04:35] [DEBUG] (gunicorn.error) POST /api/v1/transactions/ (webapi     - pid: 2272)
bigchaindb_1   | [2018-05-08 20:04:35] [DEBUG] (bigchaindb.config_utils) System already configured, skipping autoconfiguration (webapi     - pid: 2272)
bigchaindb_1   | [2018-05-08 20:04:35] [DEBUG] (bigchaindb.backend.connection) Connection: <class 'bigchaindb.backend.localmongodb.connection.LocalMongoDBConnection'> (webapi     - pid: 2272)
bigchaindb_1   | [2018-05-08 20:04:36] [DEBUG] (urllib3.connectionpool) Starting new HTTP connection (1): tendermint (webapi     - pid: 2272)
bigchaindb_1   | [2018-05-08 20:05:06] [CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:2272) (webapi     - pid: 21)
bigchaindb_1   | [2018-05-08 20:05:06] [INFO] (gunicorn.error) Worker exiting (pid: 2272) (webapi     - pid: 2272)
bigchaindb_1   | [2018-05-08 20:05:06] [INFO] (gunicorn.error) Booting worker with pid: 2325 (webapi     - pid: 2325)
bigchaindb_1   | [2018-05-08 20:05:06] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 2325)
bigchaindb_1   | [2018-05-08 20:05:06] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 2325)
bigchaindb_1   | [2018-05-08 20:05:06] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 2325)
bigchaindb_1   | [2018-05-08 20:05:06] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 2325)
bigchaindb_1   | [2018-05-08 20:05:09] [DEBUG] (gunicorn.error) GET / (webapi     - pid: 2325)
```

[bdb2_test.py.txt](https://github.com/bigchaindb/bigchaindb/files/1985493/bdb2_test.py.txt)

**Comment by vrde** [comment]
Hi @agwego, thanks for submitting your script! I was able to run it successfully.

My first guess for the error you are experiencing is that the service `tendermint` is not running. Did you start BigchainDB as a single container with `docker`, or did you use `docker-compose` to start `bigchaindb` with `tendermint` and `mongodb`? _(we are working on simplifying this)_

Another test you can do is to [run BigchainDB from the master branch](https://github.com/bigchaindb/bigchaindb/#run-and-test-bigchaindb-from-the-master-branch):
```
git clone https://github.com/bigchaindb/bigchaindb.git
cd bigchaindb
make run
```

As a side note, after doing `sent_creation_tx = bdb.transactions.send( transactionSigned )` you don't need to check if the transaction has been accepted by the network, because `send` will return only on success, or raise an exception otherwise.

**Comment by agwego** [comment]
I started bigchaindb using `make run`

**Comment by vrde** [comment]
The first thing to check is if Tendermint is running, you can check this by doing:
```
$ docker-compose ps
```
And check Tendermint logs by running:
```
$ docker-compose logs tendermint
```

If you see something weird please post it here.

One other thing you can try to restart everything (this should not be needed)
```
$ make reset
$ make start
```

You can also sign up to our test network here https://testnet.bigchaindb.com/ and try to push your transaction to it.

**Comment by agwego** [comment]
Here are my results
```
 docker-compose ps
         Name                        Command                       State                                            Ports                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------
bigchaindb_bigchaindb_1   .ci/entrypoint.sh                Up (health: starting)   0.0.0.0:32777->46658/tcp, 0.0.0.0:9984->9984/tcp, 0.0.0.0:9985->9985/tcp
bigchaindb_mongodb_1      docker-entrypoint.sh mongod      Up                      0.0.0.0:32768->27017/tcp                                                
bigchaindb_tendermint_1   sh -c tendermint init && t ...   Up                      0.0.0.0:32776->46656/tcp, 0.0.0.0:32775->46657/tcp                      
```

Tendermint, as if anyone is supposed find something amiss in MBs of output from the end
```
tendermint_1   | I[05-11|13:47:02.262] enterCommit(943/0). Current: 943/0/RoundStepPrecommit module=consensus 
tendermint_1   | I[05-11|13:47:02.267] Finalizing commit of block with 0 txs        module=consensus height=943 hash=C881F03939ECD5C6F16E9E6BCC84ECB260F9C390 root=37626165356463393161373536393462316638346562623437383238336664333538626366363266326466323866663433323064386336326466666632343365
tendermint_1   | I[05-11|13:47:02.269] Block{
tendermint_1   |   Header{
tendermint_1   |     ChainID:        test-chain-Ivckod
tendermint_1   |     Height:         943
tendermint_1   |     Time:           2018-05-11 13:47:02.213827471 +0000 UTC
tendermint_1   |     NumTxs:         0
tendermint_1   |     TotalTxs:       4
tendermint_1   |     LastBlockID:    9722FC4B4B37C52649646E713B606371F03B44EC:1:D3525F2A090B
tendermint_1   |     LastCommit:     EDB6731E44B087ACB39B65B1761E8F889F11F077
tendermint_1   |     Data:           
tendermint_1   |     Validators:     95D378481895D3E6DFFBD30CB2F910C6FF05D82E
tendermint_1   |     App:            37626165356463393161373536393462316638346562623437383238336664333538626366363266326466323866663433323064386336326466666632343365
tendermint_1   |     Consensus:       F66EF1DF8BA6DAC7A1ECCE40CC84E54A1CEBC6A5
tendermint_1   |     Results:        
tendermint_1   |     Evidence:       
tendermint_1   |   }#C881F03939ECD5C6F16E9E6BCC84ECB260F9C390
tendermint_1   |   Data{
tendermint_1   |     
tendermint_1   |   }#
tendermint_1   |   Data{
tendermint_1   |     
tendermint_1   |   }#
tendermint_1   |   Commit{
tendermint_1   |     BlockID:    9722FC4B4B37C52649646E713B606371F03B44EC:1:D3525F2A090B
tendermint_1   |     Precommits: Vote{0:2F3748109C61 942/00/2(Precommit) 9722FC4B4B37 /75038C98F17D.../ @ 2018-05-11T13:47:01.178Z}
tendermint_1   |   }#EDB6731E44B087ACB39B65B1761E8F889F11F077
tendermint_1   | }#C881F03939ECD5C6F16E9E6BCC84ECB260F9C390 module=consensus 
tendermint_1   | I[05-11|13:47:02.351] Executed block                               module=state height=943 validTxs=0 invalidTxs=0
tendermint_1   | I[05-11|13:47:02.395] Committed state                              module=state height=943 txs=0 appHash=37626165356463393161373536393462316638346562623437383238336664333538626366363266326466323866663433323064386336326466666632343365
tendermint_1   | I[05-11|13:47:02.395] Recheck txs                                  module=mempool numtxs=0 height=943
root@u138:~/bigchaindb# 

```
Seems to be working now, but the status call has now been removed from the driver version 0.5.0a4

**Comment by agwego** [comment]
After the first success subsequent requests failed.

**Comment by agwego** [comment]
Upgraded to master, things are working now.

**Comment by agwego** [comment]
The DB is also less busy than a3.

**Comment by kansi** [comment]
> Upgraded to master, things are working now.
