### ISSUE TITLE
Problem: Keyerror while checking bigchaindb show-config

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#2303]
With BigchainDB 2.0.0a6, when I run BigchainDB and try to see the running config, I get the following error:

BigchainDB started using the following env variables:
```
export BIGCHAINDB_DATABASE_BACKEND=localmongodb
export BIGCHAINDB_DATABASE_HOST=127.0.0.1
export BIGCHAINDB_DATABASE_PORT=27017
export BIGCHAINDB_SERVER_BIND=0.0.0.0:9984
export BIGCHAINDB_WSSERVER_HOST=0.0.0.0
export BIGCHAINDB_WSSERVER_PORT=9985
export BIGCHAINDB_TENDERMINT_HOST=127.0.0.1
export BIGCHAINDB_TENDERMINT_PORT=46657
```

```
$bigchaindb show-config
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 7, in <module>
    from bigchaindb.commands.bigchaindb import main
  File "/usr/local/lib/python3.6/site-packages/bigchaindb/__init__.py", line 77, in <module>
    os.environ.get('BIGCHAINDB_DATABASE_BACKEND', 'rethinkdb')
KeyError: 'localmongodb'
```

**Comment by muawiakh** [comment]
Invalid issue. Wrong version of BigchainDB installed. Closing.
