### ISSUE TITLE
After enabling Mongodb auth, bigchaindb not working

### ISSUE THREAD

**Issue by harishdrish123** [bigchaindb/bigchaindb#2329]
Hello All,

I enabled mongodb simple authentication with username and password  and after that bigchaindb not working. Please help me to sort this problem!!
Below is the error:
```
bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/bigchain/.bigchaindb`
[2018-06-01 17:54:38] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 2.0.0a5 (MainProcess - pid: 22589)
[2018-06-01 17:54:39] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 22589)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==2.0.0a5', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 247, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 160, in start
    return func(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 45, in configure
    command(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 72, in start_logging
    command(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 178, in run_start
    _run_init()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 120, in _run_init
    schema.init_database(connection=bdb.connection)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/schema.py", line 106, in init_database
    create_database(connection, dbname)
  File "/usr/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/schema.py", line 19, in create_database
    if dbname in conn.conn.database_names():
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1496, in list_database_names
    for doc in self.list_databases(session, nameOnly=True)]
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1476, in list_databases
    "admin").command(cmd, session=session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 532, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 439, in _command
    client=self.__client)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on admin to execute command { listDatabases: 1, nameOnly: true, lsid: { id: UUID("61d6745d-2e93-4e19-815e-3ac4347fffc6") }, $readPreference: { mode: "secondaryPreferred" }, $db: "admin" }
```

**Comment by ttmc** [comment]
I think the problem might be that you didn't tell your local MongoDB database to enable auth for a particular user (with a particular login username and password) before you ran BigchainDB with `bigchaindb start`. To do that, see the MongoDB docs. For example, see:

https://docs.mongodb.com/manual/tutorial/enable-authentication/

**Comment by muawiakh** [comment]
+1 @ttmc , BigchainDB will be a client hence it needs to me added as a user with the correct permissions. Something like this: https://github.com/bigchaindb/bigchaindb/blob/master/k8s/mongodb/container/configure_mdb_users.template.js

**Comment by manishverma01** [comment]
@ttmc first I have enabled the authentication with particular username and password and then I am running the bigchainDB and getting this error

**Comment by manishverma01** [comment]
@muawiakh  Here is the command I have used to create user in mongoDB database:
db.createUser({user:"useradmin", pwd:"mypassword",roles:[{role:"userAdminAnyDatabase", db:"bigchain"}]})

**Comment by manishverma01** [comment]
Here is the error:
INFO:bigchaindb.config_utils:Configuration loaded from `/home/bigchain/.bigchaindb`
[2018-06-02 11:55:00] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 2.0.0a5 (MainProcess - pid: 5623)
[2018-06-02 11:55:00] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 5623)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==2.0.0a5', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 247, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 160, in start
    return func(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 45, in configure
    command(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 72, in start_logging
    command(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 178, in run_start
    _run_init()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 120, in _run_init
    schema.init_database(connection=bdb.connection)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/schema.py", line 106, in init_database
    create_database(connection, dbname)
  File "/usr/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/schema.py", line 19, in create_database
    if dbname in conn.conn.database_names():
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1496, in list_database_names
    for doc in self.list_databases(session, nameOnly=True)]
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1476, in list_databases
    "admin").command(cmd, session=session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 532, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 439, in _command
    client=self.__client)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on admin to execute command { listDatabases: 1, nameOnly: true, lsid: { id: UUID("392eea49-f542-4150-8336-da3b8156bfa2") }, $readPreference: { mode: "secondaryPreferred" }, $db: "admin" }

**Comment by manishverma01** [comment]
@ttmc I solved this problem, just providing the root role permission to mongodb user and it works. Please  if possible for you can you please let me know does it support other roles as well??

**Comment by joaopaulo164** [comment]
> @ttmc I solved this problem, just providing the root role permission to mongodb user and it works. Please if possible for you can you please let me know does it support other roles as well??

@manishverma01 How did you give root permission to bigchain schema? I just found this option for admin schema!

**Comment by ttmc** [comment]
@joaopaulo164 Sorry, I don't know the answer to your question and I'm no longer working on BigchainDB, nor do I provide support for it.

**Comment by joaopaulo164** [comment]
@ttmc Thanks for your answer Mr. McConaghy!
We were trying to change configurations like MongoDB's password after Tendermint's installation, just need to install it after all configurations were done.
