### ISSUE TITLE
Mongo text index not created: pymongo.errors.OperationFailure: text index required for $text query

### ISSUE THREAD

**Issue by shekhar-shubhendu** [bigchaindb/bigchaindb#2448]
### Request URI: 
'http://localhost:9984/api/v1/assets?search="id:appid:a0ccc27d-4404-4db9-b2e2-f4ffab3fc997"'
### Error Encountered:
pymongo.errors.OperationFailure: text index required for $text query
### Resolved by:
Removing the bigchaindb setup(i.e. all the docker containers) and starting again.

### Log Snippet:
```text
[36mbigchaindb_1         |[0m [2018-08-06 14:13:42 +0000] [32] [DEBUG] GET /api/v1/assets
[36mbigchaindb_1         |[0m [2018-08-06 14:13:42] [ERROR] (flask.app) Exception on /api/v1/assets [GET] (bigchaindb_webapi - pid: 32)
[36mbigchaindb_1         |[0m Traceback (most recent call last):
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[36mbigchaindb_1         |[0m     rv = self.dispatch_request()
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[36mbigchaindb_1         |[0m     return self.view_functions[rule.endpoint](**req.view_args)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
[36mbigchaindb_1         |[0m     resp = resource(*args, **kwargs)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
[36mbigchaindb_1         |[0m     return self.dispatch_request(*args, **kwargs)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
[36mbigchaindb_1         |[0m     resp = meth(*args, **kwargs)
[36mbigchaindb_1         |[0m   File "/usr/src/app/bigchaindb/web/views/assets.py", line 45, in get
[36mbigchaindb_1         |[0m     return list(assets)
[36mbigchaindb_1         |[0m   File "/usr/src/app/bigchaindb/lib.py", line 430, in text_search
[36mbigchaindb_1         |[0m     for obj in objects:
[36mbigchaindb_1         |[0m   File "/usr/src/app/bigchaindb/backend/localmongodb/query.py", line 172, in <genexpr>
[36mbigchaindb_1         |[0m     return (_remove_text_score(obj) for obj in cursor)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
[36mbigchaindb_1         |[0m     if len(self.__data) or self._refresh():
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1104, in _refresh
[36mbigchaindb_1         |[0m     self.__send_message(q)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 982, in __send_message
[36mbigchaindb_1         |[0m     helpers._check_command_response(first)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
[36mbigchaindb_1         |[0m     raise OperationFailure(msg % errmsg, code, response)
[36mbigchaindb_1         |[0m pymongo.errors.OperationFailure: text index required for $text query
[36mbigchaindb_1         |[0m [2018-08-06 14:13:42] [DEBUG] (bigchaindb.core) check_tx: VALID (MainProcess - pid: 8)
[36mbigchaindb_1         |[0m [2018-08-06 14:13:42] [BENCHMARK] (bigchaindb.core) CHECK_TX_END, tx_id:ef810a83efd464a1143474bace353a40a506b6d011990dd9d3154efb1e5a3962 (MainProcess - pid: 8)
[36mbigchaindb_1         |[0m [2018-08-06 14:13:42] [ERROR] (flask.app) Exception on /api/v1/assets [GET] (bigchaindb_webapi - pid: 37)
[36mbigchaindb_1         |[0m Traceback (most recent call last):
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
[36mbigchaindb_1         |[0m     rv = self.dispatch_request()
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
[36mbigchaindb_1         |[0m     return self.view_functions[rule.endpoint](**req.view_args)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
[36mbigchaindb_1         |[0m     resp = resource(*args, **kwargs)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
[36mbigchaindb_1         |[0m     return self.dispatch_request(*args, **kwargs)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
[36mbigchaindb_1         |[0m     resp = meth(*args, **kwargs)
[36mbigchaindb_1         |[0m   File "/usr/src/app/bigchaindb/web/views/assets.py", line 45, in get
[36mbigchaindb_1         |[0m     return list(assets)
[36mbigchaindb_1         |[0m   File "/usr/src/app/bigchaindb/lib.py", line 430, in text_search
[36mbigchaindb_1         |[0m     for obj in objects:
[36mbigchaindb_1         |[0m   File "/usr/src/app/bigchaindb/backend/localmongodb/query.py", line 172, in <genexpr>
[36mbigchaindb_1         |[0m     return (_remove_text_score(obj) for obj in cursor)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
[36mbigchaindb_1         |[0m     if len(self.__data) or self._refresh():
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1104, in _refresh
[36mbigchaindb_1         |[0m     self.__send_message(q)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 982, in __send_message
[36mbigchaindb_1         |[0m     helpers._check_command_response(first)
[36mbigchaindb_1         |[0m   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
[36mbigchaindb_1         |[0m     raise OperationFailure(msg % errmsg, code, response)
[36mbigchaindb_1         |[0m pymongo.errors.OperationFailure: text index required for $text query
```

**Comment by ttmc** [comment]
@shekhar-shubhendu It seems you somehow got your BigchainDB node into a weird state, but you resolved it by cleaning house and restarting. I'm not sure that this is an issue we can resolve until we know how you got into the weird state.

**Comment by shekhar-shubhendu** [comment]
@ttmc This issue was faced by one of our clients during application testing. I'll try to get a more detailed log report from them(if they have) and provide it to you.
