### ISSUE TITLE
Officially support MongoDB Dates

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2484]
MongoDB has a BSON [Date](https://docs.mongodb.com/manual/reference/bson-types/#document-bson-type-date) type. That is, you can store dates using that type, then they can be indexed and queried easily. It would be nice if BigchainDB users could store and query such dates _as MongoDB Dates_.

When writing the blog post [Using MongoDB to Query BigchainDB Data](https://blog.bigchaindb.com/using-mongodb-to-query-bigchaindb-data-3fc651e0861b), I thought it might already be possible to store dates in MongoDB as BSON Dates. I tried, using Python code like the following:

```python
import json
import pytz
import random
import datetime

from faker import Faker
from bson import json_util  # Install using: pip install pymongo

fake = Faker()

# ...

    # Make sure the datetime_created is in the UTC time zone.
    datetime_created = fake.date_time_between(start_date='-30y',
                                              end_date='-3y',
                                              tzinfo=pytz.UTC)
    serialized_datetime_created = json.dumps(datetime_created,
                                             default=json_util.default)

    # Generate a random datetime for the sale.
    # Generate a random time delta from 0 to 2 years (730 days)
    # and add that to datetime_created
    # Remember to serialize the result.
    time_to_sale = datetime.timedelta(days=random.randint(1, 730))
    sale_datetime = datetime_created + time_to_sale
    serialized_sale_datetime = json.dumps(sale_datetime,
                                          default=json_util.default)

    transfer_tx_metadata = {
        'transfer_time': serialized_sale_datetime,
    }

    # ...

    prepared_create_tx = bdb.transactions.prepare(
        operation='CREATE',
        signers=sergio.public_key,
        asset=car_dict,
        metadata=create_tx_metadata
    )
```

As I recall, it seemed to work. The resulting transaction was valid and got stored in MongoDB, but the stored dates didn't have the Date type. You couldn't query the stored `metadata.transfer_time` as MongoDB Dates.

Maybe there was something wrong with my Python code? Maybe we have to add some more code to BigchainDB Server to make sure that Dates get stored in MongoDB properly? Once we get those questions answered, we should document _how_ to generate proper dates using Python, JavaScript and Java (i.e. our supported drivers). We should also link to the MongoDB docs about indexing and querying dates.

**Comment by siddharths2710** [comment]
As per the BSON lib documentation, mapping does exist between Python's `datetime.datetime` and BSON `date` type. However, on preparing an asset containing a datetime object, the traceback comes as follows:

```
Traceback (most recent call last):
  File "issue_2484.py", line 51, in <module>
    fulfilled_create_tx = bdb.transactions.fulfill(
  File ".//venv/lib/python3.8/site-packages/bigchaindb_driver-0.6.2-py3.8.egg/bigchaindb_driver/driver.py", line 276, in fulfill
    return fulfill_transaction(transaction, private_keys=private_keys)
  File ".//venv/lib/python3.8/site-packages/bigchaindb_driver-0.6.2-py3.8.egg/bigchaindb_driver/offchain.py", line 350, in fulfill_transaction
    signed_transaction = transaction_obj.sign(private_keys)
  File ".//venv/lib/python3.8/site-packages/bigchaindb_driver-0.6.2-py3.8.egg/bigchaindb_driver/common/transaction.py", line 831, in sign
    tx_serialized = Transaction._to_str(tx_dict)
  File ".//venv/lib/python3.8/site-packages/bigchaindb_driver-0.6.2-py3.8.egg/bigchaindb_driver/common/transaction.py", line 1107, in _to_str
    return serialize(value)
  File ".//venv/lib/python3.8/site-packages/bigchaindb_driver-0.6.2-py3.8.egg/bigchaindb_driver/common/utils.py", line 52, in serialize
    return rapidjson.dumps(data, skipkeys=False, ensure_ascii=False,
TypeError: datetime.datetime(2007, 1, 27, 2, 25, 3, tzinfo=<UTC>) is not JSON serializable
```

This seems to be an issue with the bigchaindb driver.
