### ISSUE TITLE
nodejs, syntaxerror

### ISSUE THREAD

**Issue by vitya3** [bigchaindb/bigchaindb#2536]
How to fix it?

 nodejs ./bigchaindb/helloworld.js
/root/node_modules/query-string/index.js:148
         let [key, value] = param.replace(/\+/g, ' ').split('=');
             ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/node_modules/bigchaindb-driver/dist/node/stringify_as_query_param.js:21:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Regards

**Comment by vrde** [comment]
Use a recent version of [Node JS](https://nodejs.org/). If you still have issues, please use the [BigchainDB JavaScript Driver](https://github.com/bigchaindb/js-bigchaindb-driver/) repository.
