### ISSUE TITLE
BigchainDB cluster no longer connects with Tendermint (Failed with OperationError)

### ISSUE THREAD

**Issue by charlespetchsy** [bigchaindb/bigchaindb#2569]
## Bug Report

- What computer are you on (hardware)?
A cluster of 4 nodes
- What operating system are you using, including version. e.g. Ubuntu 14.04? Fedora 23?
Ubuntu 16.04 LTS
- What version of BigchainDB software were you using? Is that the latest version?
v2.0.0b5

I am running 4 instances of BigchainDB with MongoDB `3.6` and Tendermint `0.22.8`. It is a stock version of bigchaindb which has been installed using pip3.

For the record, the cluster currently possess ~180k assets (about 5.5 GB of data stored on MongoDB) before the crash. Initially, 161k assets loaded flawlessly with each payload being a size of 4 KB each. I had another dataset that I wanted to load which consisted of ~38k assets of which each payload is 197 KB in size.

There were many hiccups trying to load the dataset as Tendermint kept on crashing with the following error: `ERROR: Failed to create node: Error starting proxy app connections: Error on replay: Commit failed for application: EOF`

When this error happens, I usually restart the cluster and re-run the loading script and we're back to business, but this time BigchainDB no longer connects with Tendermint.

BigchainDB log (`bigchaindb.log`):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 610, in receive_message
    self.max_message_size)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/network.py", line 173, in receive_message
    _receive_data_on_socket(sock, 16))
  File "/usr/local/lib/python3.6/dist-packages/pymongo/network.py", line 232, in _receive_data_on_socket
    chunk_length = sock.recv_into(mv[bytes_read:])
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/connection.py", line 61, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/utils.py", line 166, in run
    last = last(*item[0], **item[1])
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 753, in insert_many
    blk.execute(write_concern, session=session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 513, in execute
    return self.execute_command(generator, write_concern, session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 338, in execute_command
    self.is_retryable, retryable_bulk, s, self)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1196, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 333, in retryable_bulk
    retryable, full_result)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 288, in _execute_command
    result = bwc.write_command(request_id, msg, to_send)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/message.py", line 920, in write_command
    reply = self.sock_info.write_command(request_id, msg)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 651, in write_command
    reply = self.receive_message(request_id)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 612, in receive_message
    self._raise_connection_failure(error)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 743, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/pool.py", line 273, in _raise_connection_failure
    raise NetworkTimeout(msg)
pymongo.errors.NetworkTimeout: localhost:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/connection.py", line 65, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/utils.py", line 166, in run
    last = last(*item[0], **item[1])
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 753, in insert_many
    blk.execute(write_concern, session=session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 513, in execute
    return self.execute_command(generator, write_concern, session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 341, in execute_command
    _raise_bulk_write_error(full_result)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/bulk.py", line 140, in _raise_bulk_write_error
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.6/dist-packages/abci/server.py", line 171, in __handle_connection
    response = self.protocol.process(req_type, message)
  File "/usr/local/lib/python3.6/dist-packages/abci/server.py", line 50, in process
    return handler(req)
  File "/usr/local/lib/python3.6/dist-packages/abci/server.py", line 87, in commit
    result = self.app.commit()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/core.py", line 154, in commit
    self.bigchaindb.store_bulk_transactions(self.block_transactions)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/lib.py", line 165, in store_bulk_transactions
    backend.query.store_metadatas(self.connection, txn_metadatas)
  File "/usr/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/query.py", line 54, in store_metadatas
    .insert_many(metadata, ordered=False))
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/backend/localmongodb/connection.py", line 72, in run
    raise OperationError from exc
bigchaindb.backend.exceptions.OperationError
2018-09-23T19:07:33Z <Greenlet "Greenlet-0" at 0x7f8ffd4a7d48: _handle_and_close_when_done(<bound method ABCIServer.__handle_connection of <a, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with OperationError
```

Tendermint log:
```
I[09-23|19:07:08.580] Starting multiAppConn                        module=proxy impl=multiAppConn
I[09-23|19:07:08.580] Starting socketClient                        module=abci-client connection=query impl=socketClient
I[09-23|19:07:08.582] Starting socketClient                        module=abci-client connection=mempool impl=socketClient
I[09-23|19:07:08.582] Starting socketClient                        module=abci-client connection=consensus impl=socketClient
I[09-23|19:07:08.608] ABCI Handshake                               module=consensus appHeight=198739 appHash=34386365616339333238396564666238376536326365353733373066323337363837623137663838626639303530373433373165396431326164323464323539
I[09-23|19:07:08.608] ABCI Replay Blocks                           module=consensus appHeight=198739 storeHeight=198741 stateHeight=198740
I[09-23|19:07:08.608] Applying block                               module=consensus height=198740
I[09-23|19:07:08.659] Executed block                               module=consensus height=198740 validTxs=0 invalidTxs=0
I[09-23|19:07:08.926] Executed block                               module=consensus height=198741 validTxs=15 invalidTxs=0
E[09-23|19:07:33.843] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
I[09-23|19:07:33.843] Stopping socketClient                        module=abci-client connection=consensus impl=socketClient
E[09-23|19:07:33.843] Client error during proxyAppConn.CommitSync  module=consensus err=EOF
ERROR: Failed to create node: Error starting proxy app connections: Error on replay: Commit failed for application: EOF
```

No matter the number of times I try to restart the cluster, the following errors are produced.

**Comment by ldmberman** [comment]
@charlespetchsy thank you for reporting the issue!

For some reason, BigchainDB fails to put the block it receives into MongoDB. We are currently missing the MongoDB testimony for the case. Could you, please, post some MongoDB logs? You may find them in `/var/log/mongodb/mongodb.log`.

**Comment by charlespetchsy** [comment]
@ldmberman From the `mongodb.log` file:
```
2018-09-24T10:50:33.817-0400 I STORAGE  [initandlisten]
2018-09-24T10:50:33.817-0400 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2018-09-24T10:50:33.817-0400 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2018-09-24T10:50:33.823-0400 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3479M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-09-24T10:50:34.729-0400 I STORAGE  [initandlisten] WiredTiger message [1537800634:729940][22154:0x7f11e3b1fa00], txn-recover: Main recovery loop: starting at 102/6153856
2018-09-24T10:50:34.902-0400 I STORAGE  [initandlisten] WiredTiger message [1537800634:902374][22154:0x7f11e3b1fa00], txn-recover: Recovering log 102 through 103
2018-09-24T10:50:34.972-0400 I STORAGE  [initandlisten] WiredTiger message [1537800634:972449][22154:0x7f11e3b1fa00], txn-recover: Recovering log 103 through 103
2018-09-24T10:50:35.034-0400 I STORAGE  [initandlisten] WiredTiger message [1537800635:34701][22154:0x7f11e3b1fa00], txn-recover: Set global recovery timestamp: 0
2018-09-24T10:50:35.136-0400 I CONTROL  [initandlisten]
2018-09-24T10:50:35.136-0400 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-09-24T10:50:35.136-0400 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-09-24T10:50:35.136-0400 I CONTROL  [initandlisten]
2018-09-24T10:50:35.137-0400 I CONTROL  [initandlisten]
2018-09-24T10:50:35.137-0400 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-09-24T10:50:35.137-0400 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-09-24T10:50:35.137-0400 I CONTROL  [initandlisten]
2018-09-24T10:50:35.208-0400 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/var/lib/mongodb/diagnostic.data'
2018-09-24T10:50:35.209-0400 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-09-24T10:50:41.096-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42138 #1 (1 connection now open)
2018-09-24T10:50:41.096-0400 I NETWORK  [conn1] received client metadata from 127.0.0.1:42138 conn1: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:50:41.097-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42140 #2 (2 connections now open)
2018-09-24T10:50:41.098-0400 I NETWORK  [conn2] received client metadata from 127.0.0.1:42140 conn2: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:51:01.127-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42164 #3 (3 connections now open)
2018-09-24T10:51:01.136-0400 I NETWORK  [conn3] received client metadata from 127.0.0.1:42164 conn3: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:51:21.587-0400 I NETWORK  [conn1] end connection 127.0.0.1:42138 (2 connections now open)
2018-09-24T10:51:44.090-0400 I WRITE    [conn2] remove bigchain.assets command: { q: { id: { $in: [ "5bc2829ed77bae8ccadbdc54cf784bdcaa9bff01c032f43e88386836cff6ff0e", "a7dee4e5ef3415235eab5b714e84da1dd650c22ae24dac5403ab9dfbac1b81df", "33c54558c95d08b103f8fa0249501e67e6321cb342df7c69d2a870e4ef293bf4", "d13039ebff89e89085ad55f7002dd32bc4d679ea9e979a97b7f7b147956535e8", "8724a6173ebc0be823989e11d78d063d76feda38301a2e79e1f224a35ddf4147", "5680c843fea4bc67a60ee78d25ed4dc9f9c3cb273d27e158c671b22048be398b", "0c71d741ea24fd9f8d4c75bd5423a7683085055209f01d0c8ba6880abdc23812", "3ae04fc08108a244ae58da906829e68ee6ab61834b03e54407117b6f49b436e1", "318898673ba0e2868d005d717b3ad5b4642844553d1724ae981b4de2aeb31d01", "04829ce5d3c8ba3824966efdcaf4f32b4021a969e2b16e1b657775d9c849b41d", "ae5d565e78cd51827e08c43f024225694e12bc0dad85c2e9c54370e0f020a7e9", "9bed40bc198bf28b3f6e963ea1fd0e923ed2602f6f28ea9f49d0981bc7e201fe", "455f528d1e036d93d8c0620dfc01073854392df6d384e231a3785c383d507122", "5706702f05a4737f8bb40c54b2ef63b4aa23f6cee3dad6f1faee99a5b45666be", "a2477c945e27a42fae59810dccc9ed0e282e76f1a1d232286bc489fd1fff3f24" ] } }, limit: 0 } planSummary: IXSCAN { id: 1 } keysExamined:30 docsExamined:15 ndeleted:15 keysDeleted:73330 numYields:15 locks:{ Global: { acquireCount: { r: 18, w: 16 } }, Database: { acquireCount: { r: 1, w: 16 } }, Collection: { acquireCount: { r: 1, w: 16 } } } 62985ms
2018-09-24T10:51:44.091-0400 I NETWORK  [conn3] end connection 127.0.0.1:42164 (1 connection now open)
2018-09-24T10:51:44.091-0400 I COMMAND  [conn2] command bigchain.$cmd command: delete { delete: "assets", ordered: true, lsid: { id: UUID("254a6996-a630-4433-afa9-d8ea1f592e04") }, $db: "bigchain", $readPreference: { mode: "primary" } } numYields:0 reslen:29 locks:{ Global: { acquireCount: { r: 18, w: 16 } }, Database: { acquireCount: { r: 1, w: 16 } }, Collection: { acquireCount: { r: 1, w: 16 } } } protocol:op_msg 62985ms
2018-09-24T10:51:44.091-0400 I NETWORK  [conn2] end connection 127.0.0.1:42140 (0 connections now open)
2018-09-24T10:52:20.182-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42248 #4 (1 connection now open)
2018-09-24T10:52:20.183-0400 I NETWORK  [conn4] received client metadata from 127.0.0.1:42248 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.6.6" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }
2018-09-24T10:52:21.589-0400 I NETWORK  [conn4] end connection 127.0.0.1:42248 (0 connections now open)
2018-09-24T10:52:46.398-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42278 #5 (1 connection now open)
2018-09-24T10:52:46.398-0400 I NETWORK  [conn5] received client metadata from 127.0.0.1:42278 conn5: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:52:46.399-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42280 #6 (2 connections now open)
2018-09-24T10:52:46.399-0400 I NETWORK  [conn6] received client metadata from 127.0.0.1:42280 conn6: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:53:06.493-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42302 #7 (3 connections now open)
2018-09-24T10:53:06.493-0400 I NETWORK  [conn7] received client metadata from 127.0.0.1:42302 conn7: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:53:26.818-0400 I NETWORK  [conn5] end connection 127.0.0.1:42278 (2 connections now open)
2018-09-24T10:53:38.007-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42334 #8 (3 connections now open)
2018-09-24T10:53:38.019-0400 I NETWORK  [conn8] received client metadata from 127.0.0.1:42334 conn8: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:53:38.021-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42336 #9 (4 connections now open)
2018-09-24T10:53:38.040-0400 I NETWORK  [conn9] received client metadata from 127.0.0.1:42336 conn9: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:53:54.801-0400 I WRITE    [conn6] remove bigchain.metadata command: { q: { id: { $in: [ "5bc2829ed77bae8ccadbdc54cf784bdcaa9bff01c032f43e88386836cff6ff0e", "a7dee4e5ef3415235eab5b714e84da1dd650c22ae24dac5403ab9dfbac1b81df", "33c54558c95d08b103f8fa0249501e67e6321cb342df7c69d2a870e4ef293bf4", "d13039ebff89e89085ad55f7002dd32bc4d679ea9e979a97b7f7b147956535e8", "8724a6173ebc0be823989e11d78d063d76feda38301a2e79e1f224a35ddf4147", "5680c843fea4bc67a60ee78d25ed4dc9f9c3cb273d27e158c671b22048be398b", "0c71d741ea24fd9f8d4c75bd5423a7683085055209f01d0c8ba6880abdc23812", "3ae04fc08108a244ae58da906829e68ee6ab61834b03e54407117b6f49b436e1", "318898673ba0e2868d005d717b3ad5b4642844553d1724ae981b4de2aeb31d01", "04829ce5d3c8ba3824966efdcaf4f32b4021a969e2b16e1b657775d9c849b41d", "ae5d565e78cd51827e08c43f024225694e12bc0dad85c2e9c54370e0f020a7e9", "9bed40bc198bf28b3f6e963ea1fd0e923ed2602f6f28ea9f49d0981bc7e201fe", "455f528d1e036d93d8c0620dfc01073854392df6d384e231a3785c383d507122", "5706702f05a4737f8bb40c54b2ef63b4aa23f6cee3dad6f1faee99a5b45666be", "a2477c945e27a42fae59810dccc9ed0e282e76f1a1d232286bc489fd1fff3f24" ] } }, limit: 0 } planSummary: IXSCAN { id: 1 } keysExamined:30 docsExamined:15 ndeleted:15 keysDeleted:73830 numYields:15 locks:{ Global: { acquireCount: { r: 16, w: 16 } }, Database: { acquireCount: { w: 16 } }, Collection: { acquireCount: { w: 16 } } } 68398ms
2018-09-24T10:53:54.802-0400 I NETWORK  [conn7] end connection 127.0.0.1:42302 (3 connections now open)
2018-09-24T10:53:54.802-0400 I COMMAND  [conn6] command bigchain.$cmd command: delete { delete: "metadata", ordered: true, lsid: { id: UUID("c246f743-daae-4ffb-9876-4bebe23bf078") }, $db: "bigchain", $readPreference: { mode: "primary" } } numYields:0 reslen:29 locks:{ Global: { acquireCount: { r: 16, w: 16 } }, Database: { acquireCount: { w: 16 } }, Collection: { acquireCount: { w: 16 } } } protocol:op_msg 68399ms
2018-09-24T10:53:54.802-0400 I NETWORK  [conn6] end connection 127.0.0.1:42280 (2 connections now open)
2018-09-24T10:53:54.807-0400 I WRITE    [conn9] remove bigchain.metadata command: { q: { id: { $in: [ "5bc2829ed77bae8ccadbdc54cf784bdcaa9bff01c032f43e88386836cff6ff0e", "a7dee4e5ef3415235eab5b714e84da1dd650c22ae24dac5403ab9dfbac1b81df", "33c54558c95d08b103f8fa0249501e67e6321cb342df7c69d2a870e4ef293bf4", "d13039ebff89e89085ad55f7002dd32bc4d679ea9e979a97b7f7b147956535e8", "8724a6173ebc0be823989e11d78d063d76feda38301a2e79e1f224a35ddf4147", "5680c843fea4bc67a60ee78d25ed4dc9f9c3cb273d27e158c671b22048be398b", "0c71d741ea24fd9f8d4c75bd5423a7683085055209f01d0c8ba6880abdc23812", "3ae04fc08108a244ae58da906829e68ee6ab61834b03e54407117b6f49b436e1", "318898673ba0e2868d005d717b3ad5b4642844553d1724ae981b4de2aeb31d01", "04829ce5d3c8ba3824966efdcaf4f32b4021a969e2b16e1b657775d9c849b41d", "ae5d565e78cd51827e08c43f024225694e12bc0dad85c2e9c54370e0f020a7e9", "9bed40bc198bf28b3f6e963ea1fd0e923ed2602f6f28ea9f49d0981bc7e201fe", "455f528d1e036d93d8c0620dfc01073854392df6d384e231a3785c383d507122", "5706702f05a4737f8bb40c54b2ef63b4aa23f6cee3dad6f1faee99a5b45666be", "a2477c945e27a42fae59810dccc9ed0e282e76f1a1d232286bc489fd1fff3f24" ] } }, limit: 0 } planSummary: IXSCAN { id: 1 } keysExamined:21 docsExamined:6 ndeleted:0 writeConflicts:1097 numYields:1097 locks:{ Global: { acquireCount: { r: 1098, w: 1098 } }, Database: { acquireCount: { w: 1098 } }, Collection: { acquireCount: { w: 1098 } } } 16739ms
2018-09-24T10:53:54.807-0400 I COMMAND  [conn9] command bigchain.$cmd command: delete { delete: "metadata", ordered: true, lsid: { id: UUID("9c018794-fbc8-47b7-b26a-d8edc8d5b247") }, $db: "bigchain", $readPreference: { mode: "primary" } } numYields:0 reslen:29 locks:{ Global: { acquireCount: { r: 1098, w: 1098 } }, Database: { acquireCount: { w: 1098 } }, Collection: { acquireCount: { w: 1098 } } } protocol:op_msg 16739ms
2018-09-24T10:53:54.829-0400 I NETWORK  [conn8] end connection 127.0.0.1:42334 (1 connection now open)
2018-09-24T10:53:54.829-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42356 #10 (2 connections now open)
2018-09-24T10:53:54.829-0400 I NETWORK  [conn9] end connection 127.0.0.1:42336 (1 connection now open)
2018-09-24T10:53:54.829-0400 I NETWORK  [conn10] received client metadata from 127.0.0.1:42356 conn10: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:53:54.830-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42358 #11 (2 connections now open)
2018-09-24T10:53:54.830-0400 I NETWORK  [conn11] received client metadata from 127.0.0.1:42358 conn11: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:53:54.831-0400 I NETWORK  [conn10] end connection 127.0.0.1:42356 (1 connection now open)
2018-09-24T10:53:54.831-0400 I NETWORK  [conn11] end connection 127.0.0.1:42358 (0 connections now open)
2018-09-24T10:54:32.492-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42426 #12 (1 connection now open)
2018-09-24T10:54:32.493-0400 I NETWORK  [conn12] received client metadata from 127.0.0.1:42426 conn12: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:54:32.501-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42428 #13 (2 connections now open)
2018-09-24T10:54:32.501-0400 I NETWORK  [conn13] received client metadata from 127.0.0.1:42428 conn13: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:54:52.920-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:42462 #14 (3 connections now open)
2018-09-24T10:54:52.926-0400 I NETWORK  [conn14] received client metadata from 127.0.0.1:42462 conn14: { driver: { name: "PyMongo", version: "3.7.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.4.0-130-generic" }, platform: "CPython 3.6.5.final.0" }
2018-09-24T10:54:53.173-0400 I COMMAND  [conn13] command bigchain.metadata command: insert { insert: "metadata", ordered: false, lsid: { id: UUID("ff947c11-4a8e-4a98-954f-4ed5ffb7fbdf") }, $db: "bigchain" } ninserted:15 keysInserted:73830 numYields:0 reslen:29 locks:{ Global: { acquireCount: { r: 5, w: 5 } }, Database: { acquireCount: { w: 5 } }, Collection: { acquireCount: { w: 5 } } } protocol:op_msg 20279ms
2018-09-24T10:54:53.185-0400 I NETWORK  [conn13] end connection 127.0.0.1:42428 (2 connections now open)
```

**Comment by ldmberman** [comment]
@charlespetchsy the timestamps do not seem to match.

BigchainDB logs are from `2018-09-23T19:07:33Z`, Tendermint logs are from `[09-23|19:07:33.843]` while the earliest MongoDB entry says `2018-09-24T10:50:33`. So I would like to double-check - did you reproduce the bug around `2018-09-24T10:50:33` as well?

**Comment by charlespetchsy** [comment]
@ldmberman Yes, I reproduced the bug at a later time. My apologies I should've mentioned this earlier! I'd watched the Mongo logs update as I start up BigchainDB and Tendermint. However, the logs produced by BCDB and Tendermint are identical aside from the timestamp.
