### ISSUE TITLE
ConnectionError when following Notes on Running a Local Dev Node as Processes

### ISSUE THREAD

**Issue by NanPhi** [bigchaindb/bigchaindb#2577]
OS: Ubuntu 18.04
Mongodb Version: 3.6.1
Tendermint Version: 0.22.8

I followed instruction on http://docs.bigchaindb.com/projects/contributing/en/latest/dev-setup-coding-and-contribution-process/run-node-as-processes.html
in order to set up a local bigchaindb network with one node on my machine. I installed Mongodb and started it successfully

`2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] MongoDB starting : pid=23168 port=27017 dbpath=/data/db 64-bit host=0306ea539f22
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] db version v3.6.3
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] modules: none
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] build environment:
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-08T08:30:03.953+0000 I CONTROL  [initandlisten] options: {}
2018-10-08T08:30:03.954+0000 I STORAGE  [initandlisten] exception in initAndListen: NonExistentPath: Data directory /data/db not found., terminating
2018-10-08T08:30:03.954+0000 I CONTROL  [initandlisten] now exiting
2018-10-08T08:30:03.954+0000 I CONTROL  [initandlisten] shutting down with code:100
root@0306ea539f22:/# mkdir -p /data/db
root@0306ea539f22:/# mongod
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] MongoDB starting : pid=23172 port=27017 dbpath=/data/db 64-bit host=0306ea539f22
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] db version v3.6.3
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] modules: none
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] build environment:
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-08T08:30:29.678+0000 I CONTROL  [initandlisten] options: {}
2018-10-08T08:30:29.679+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] 
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] 
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-08T08:30:30.147+0000 I CONTROL  [initandlisten] 
2018-10-08T08:30:30.147+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: bb50a103-ca6c-4261-9cd8-eef6e1ae2953
2018-10-08T08:30:30.153+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
2018-10-08T08:30:30.156+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 45dc5e41-d0f1-4e07-ab30-8c3d5b8eebce
2018-10-08T08:30:30.162+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-08T08:30:30.163+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-08T08:35:30.164+0000 I STORAGE  [thread1] createCollection: config.system.sessions with generated UUID: 5ceb72a8-2f08-41ab-9615-db6aa76151dc
2018-10-08T08:35:30.186+0000 I INDEX    [thread1] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
2018-10-08T08:35:30.186+0000 I INDEX    [thread1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2018-10-08T08:35:30.188+0000 I INDEX    [thread1] build index done.  scanned 0 total records. 0 secs`

After that I installed Tendermint.0.22.8 and ran the commands
`tendermint init
  tendermint node --consensus.create_empty_blocks=false`

it output connection error as following
`I[10-08|08:40:25.108] Starting multiAppConn                        module=proxy impl=multiAppConn
I[10-08|08:40:25.108] Starting socketClient                        module=abci-client connection=query impl=socketClient
E[10-08|08:40:25.109] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:29.099] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:32.066] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:35.068] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:38.071] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:41.074] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:44.076] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:47.078] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:50.080] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[10-08|08:40:53.082] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query`

I wondered do I have to change some configurations in config.toml?

**Comment by ttmc** [comment]
Those instructions are for developers who want to contribute to BigchainDB Server code etc. Maybe try the instructions in the page http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html instead --- they also work for a single-node "network."

**Comment by NanPhi** [comment]
I followed http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html step by step and seemed not to run into any problems. But when I tried to run a basic example https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html on the network, a time-out error came out
<img width="1418" alt="bdb" src="https://user-images.githubusercontent.com/15139145/46644847-a6ee7f80-cbb4-11e8-85db-12dfb5593b8e.png">

**Comment by karimsoomro** [comment]
I am also having similar issue @NanPhi 
My stack trace looks like this,

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='0.0.0.0', port=9984): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 411, in send_commit
    headers=headers)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 82, in forward_request
    backoff_cap=backoff_cap,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 91, in request
    **kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 120, in _request
    response = self.session.request(**kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='0.0.0.0', port=9984): Read timed out. (read timeout=20)

Any resolution to this? or am i doing something wrong???

**Comment by ttmc** [comment]
It doesn't make sense to try and connect to a BigchainDB node with IP address 0.0.0.0

Someone else reported trying to do that as well and I wonder where that idea came from. If someone could point me to some specific docs, that would be very helpful.

Note: Setting `server.bind` to `0.0.0.0:9984` just means to accept incoming connections from _any_ IP address. It doesn't mean that that node has an IP address of 0.0.0.0. If you deployed the node in a cloud provider such as AWS or Azure, it should tell you the public IP address in the information about the VM.

**Comment by karimsoomro** [comment]
@ttmc I am using bdb_root_url = '0.0.0.0:9984' b/c i am executing on localhost.

Furthermore i have also tried below as bdb_root_url parameters,

1. bdb_root_url = '35.176.23.99:9984'
2. bdb_root_url = 'http://localhost:9984'

BigChainDB is hosted on Aws & the address is 35.176.23.99:9984 (i am able to access this url using browser)

Here is the screen-cast of complete process: [Here is the screen-cast of complete process: https://drive.google.com/file/d/1otbm4UEbEmrYxEeNpJzA5Ik1sDc0K_6-/view?usp=sharing](https://drive.google.com/file/d/1otbm4UEbEmrYxEeNpJzA5Ik1sDc0K_6-/view?usp=sharing)

But still having same issues, any suggestion?

**Comment by ttmc** [comment]
0.0.0.0 is not the IP address of localhost. On Linux machines, you can just write `localhost` in place of the IP address. The IP address of localhost is usually something like 127.0.0.1 but it can vary.

I'm not able to access 35.176.23.99:9984 from my browser. Did you shut it down?

In AWS, your VM should have a security group and you'll have to tell it to allow incoming traffic of certain kinds on certain ports (e.g. TCP on port 9984).

The master-branch-docs for the Simple Deployment Template might be easier to follow, and they include NGINX setup. Maybe try those instructions. They are at:

http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/index.html

**Comment by karimsoomro** [comment]
@ttmc  Thanks it certainly changed the status at-least 🥇
I have changes the script to `bdb_root_url = '127.0.0.1'  # Use YOUR BigchainDB Root URL here`

But now i have i am receiving"Internal Server Error". stack trace is below.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 411, in send_commit
    headers=headers)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 82, in forward_request
    backoff_cap=backoff_cap,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 91, in request
    **kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 128, in _request
    raise exc_cls(response.status_code, text, json, kwargs['url'])
bigchaindb_driver.exceptions.TransportError: (500, '{"message": "Internal Server Error"}\n', {'message': 'Internal Server Error'}, 'http://127.0.0.1:9984/api/v1/transactions/')
`  

Here is the python script i am using to commit transaction.
`from bigchaindb_driver import BigchainDB
bdb_root_url = '127.0.0.1'  # Use YOUR BigchainDB Root URL here
bdb = BigchainDB(bdb_root_url)
bicycle = { 'data': { 'bicycle': { 'serial_number': 'abcd1234', 'manufacturer': 'bkfab', }, }, }
metadata = {'planet': 'earth'}
from bigchaindb_driver.crypto import generate_keypair
alice, bob = generate_keypair(), generate_keypair()
prepared_creation_tx = bdb.transactions.prepare( operation='CREATE', signers=alice.public_key, asset=bicycle, metadata=metadata,)
prepared_creation_tx
fulfilled_creation_tx = bdb.transactions.fulfill( prepared_creation_tx, private_keys=alice.private_key)
fulfilled_creation_tx
sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx)`

Last line is producing the error.

@ttmc  Your response is very much appreciated.

**Comment by imvvk11** [comment]
Did anyone solve this problem.

**Comment by lana-shanghai** [comment]
The current best installation options are:

- a docker-all-in-one solution (installs Mongo, Tendermint, python, BigchainDB)
- an ansible script that runs nodes either on one machine, or several, and connects them into a network
- the manual step-by-step installation
All are available in the "Installation" section of the re-organized documentation http://docs.bigchaindb.com/en/latest/installation/index.html
The "Drivers" section describes the connectors used to send transactions to BigchainDB.

**Comment by Yehezkiel-simbuang** [comment]
> That means BigchainDB Server isn't working properly.
> 
> What happens when you go to the URL `http://127.0.0.1:9984` in your web browser? You should see something like the output shown in this section of the docs:
> 
> http://docs.bigchaindb.com/projects/server/en/master/http-client-server-api.html#bigchaindb-root-url

I already try it, but it gives like on docs. its normal. When i try to get http response its normal too. But when i try commited block, its give an error 500. I dont know whats the problem. Have you solve it? 
@ttmc
