### ISSUE TITLE
Error: bdb.transactions.send_commit(fulfilled_creation_tx)

### ISSUE THREAD

**Issue by karimsoomro** [bigchaindb/bigchaindb#2581]
# What Should Go in a Bug Report

- What computer are you on (hardware)? AWS x64
- What operating system are you using? Canonical, Ubuntu, 18.04 LTS
- What version of BigchainDB software were you using? 2.0.0b3

I have followed the directions & successfully able to setup the network & see the api end-points exposed.
![image](https://user-images.githubusercontent.com/23157639/47048190-1bc44980-d1b3-11e8-8e84-513565bac629.png)

But when i am posting transaction from python on local host machine then i am getting error, see the details below.

Code snippet - bdb.transactions.send_commit is throwing error.
`from bigchaindb_driver import BigchainDB
bdb_root_url = '0.0.0.0:9984'  # Use YOUR BigchainDB Root URL here
bdb = BigchainDB(bdb_root_url)
bicycle = { 'data': { 'bicycle': { 'serial_number': 'abcd1234', 'manufacturer': 'bkfab', }, }, }
metadata = {'planet': 'earth'}
from bigchaindb_driver.crypto import generate_keypair
alice, bob = generate_keypair(), generate_keypair()
prepared_creation_tx = bdb.transactions.prepare( operation='CREATE', signers=alice.public_key, asset=bicycle, metadata=metadata,)
prepared_creation_tx
fulfilled_creation_tx = bdb.transactions.fulfill( prepared_creation_tx, private_keys=alice.private_key)
fulfilled_creation_tx
sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx)`

Error stack trace looks like this,
`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='0.0.0.0', port=9984): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 411, in send_commit
    headers=headers)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 82, in forward_request
    backoff_cap=backoff_cap,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 91, in request
    **kwargs,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 120, in _request
    response = self.session.request(**kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='0.0.0.0', port=9984): Read timed out. (read timeout=20)`

Any resolution to this? or am i doing something wrong???

**Comment by ttmc** [comment]
`bdb_root_url = '0.0.0.0:9984'` is not going to work. You need to use a valid IP address or hostname rather than `0.0.0.0` --- the IP address or hostname of one of the nodes in your BigchainDB network.

Note: The latest version of BigchainDB Server is 2.0.0b7 so you might want to upgrade to that.

`pip install --upgrade bigchaindb==2.0.0b7`

**Comment by karimsoomro** [comment]
@ttmc  i am using `bdb_root_url = '0.0.0.0:9984'` b/c i am executing on localhost.

Furthermore i have also tried below as `bdb_root_url ` parameters,
1. bdb_root_url = '35.176.23.99:9984'
2. bdb_root_url = 'http://localhost:9984'

But still having same issues, any suggestion?

**Comment by ttmc** [comment]
@karimsoomro Are you running BigchainDB Server on your local machine (e.g. your local desktop or laptop)? Or are you running it in some cloud provider such as AWS or Azure?

See also: https://docs.bigchaindb.com/projects/server/en/latest/http-client-server-api.html#determining-the-api-root-url

**Comment by karimsoomro** [comment]
@ttmc  BigChainDB is hosted on aws & the address is 35.176.23.99:9984 (i am able to access this url using browser)

I have also tried this but having the same issue.

Here is the screen-cast of complete process: [https://drive.google.com/file/d/1otbm4UEbEmrYxEeNpJzA5Ik1sDc0K_6-/view?usp=sharing](https://drive.google.com/file/d/1otbm4UEbEmrYxEeNpJzA5Ik1sDc0K_6-/view?usp=sharing)

**Comment by authwork** [comment]
Same issue here.
I can open the web page via the bdb_root_url.
But when executing bdb.transactions.send_commit, it will show this error. (SSL, https:\\localhost:9984)
If I use http:\\localhost:9984, it will show 500 server error.

**Comment by authwork** [comment]
Update @ 21/01/2019 : 13:25 PM

@ttmc 
The error info at the server side is changed to the following:
INFO      ... connection from Tendermint: 10.1.2.12:55934 ...
[2019-01-21 05:12:12] [INFO] (abci.app)  ... connection from Tendermint: 10.1.2.12:55934 ... (MainProcess - pid: 28846)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File ".local/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File ".local/lib/python3.6/site-packages/abci/server.py", line 169, in __handle_connection
    for message in messages:
  File ".local/lib/python3.6/site-packages/abci/encoding.py", line 59, in read_messages
    m.ParseFromString(data)
google.protobuf.message.DecodeError: Error parsing message
2019-01-21T05:12:12Z <Greenlet at 0x7f2ba8972c48: _handle_and_close_when_done(<bound method ABCIServer.__handle_connection of <a, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with DecodeError

It will lead to :
[2019-01-21 05:12:12,028] ERROR in app: Exception on /api/v1/transactions/ [POST]
Traceback (most recent call last):
  File ".local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File ".local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File ".local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

@karimsoomro 
I guess the pervious error is that we do not launch Tendermint and the proxy is not accessible.
You can try 
1. 
> bigchaindb start
> tendermint node
or
2.
> tendermint start all

**Comment by authwork** [comment]
Update @ 21/01/2019 : 14:04 PM

@ttmc 
I got it work.
I just call back that I change the bigchaindb configuration: 
```
Tendermint host? (default `10.1.2.12`)
Tendermint port? (default `26658`)26657
```
I am now changing it back to 26657 and it works.
sample code 
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair

bdb_root_url = 'http://localhost:9984'
bdb = BigchainDB(bdb_root_url)

msg = 'test bigchaindb'

alice = generate_keypair()
tx = bdb.transactions.prepare(
    operation='CREATE',
    signers=alice.public_key,
    asset={'data': {'message': msg}})
signed_tx = bdb.transactions.fulfill(
    tx,
    private_keys=alice.private_key)
bdb.transactions.send_commit(signed_tx)

**Comment by shubhamc15** [comment]
I have install lates version of both bigchaindb and its python driver but and have configured the bigchaindb and mongodb and when i run http://localhost:9984 on browser i get following output:

{"api":{"v1":{"assets":"/api/v1/assets/","blocks":"/api/v1/blocks/","docs":"https://docs.bigchaindb.com/projects/server/en/v2.0.0b9/http-client-server-api.html","metadata":"/api/v1/metadata/","outputs":"/api/v1/outputs/","streams":"ws://localhost:9985/api/v1/streams/valid_transactions","transactions":"/api/v1/transactions/","validators":"/api/v1/validators"}},"docs":"https://docs.bigchaindb.com/projects/server/en/v2.0.0b9/","software":"BigchainDB","version":"2.0.0b9"}
 But after runnning the Alice example i get following error at time of send_commit transaction code.

bigchaindb_driver.exceptions.TransportError: (500, '{"message": "Internal Server Error"}\n', {'message': 'Internal Server Error'}, 'http://localhost:9984/api/v1/transactions/')

**Comment by authwork** [comment]
> is Tendermint needed??

Yes, I think it is needed, if you see the logs at the server side, you can see it can not connect to the proxy.
Just have a try.

**Comment by shubhamc15** [comment]
So what confiurations have to be changed?
i have installed tendermint and its config file has proxy_app = "tcp://127.0.0.1:26657" 
and in bigchaindb conf file i have added 
"tendermint": {
        "host": "tcp://127.0.0.1",
        "port": 26657
    },
but getting error 
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tcp', port=80): Max retries exceeded with url: //127.0.0.1:26657/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff87669f668>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by authwork** [comment]
Do you excute tendermint at the backend?
I mean the suggestion I give at [here](https://github.com/bigchaindb/bigchaindb/issues/2581#issuecomment-455952861).

**Comment by shubhamc15** [comment]
tendermint node gives error 
E[01-21|06:58:39.907] abci.socketClient failed to connect to 127.0.0.1:26657.  Retrying... module=abci-client connection=query

**Comment by authwork** [comment]
Pay attantion to the order.
First blockchain, later tendermint.

**Comment by shubhamc15** [comment]
Is this configuration correct 
bigchaindb conf
"tendermint": {
        "host": "127.0.0.1",
        "port": 27017
    },
tendermint conf:
proxy_app = "127.0.0.1:26657"

**Comment by shubhamc15** [comment]
blockchain has started successfully

**Comment by authwork** [comment]
If the bigchaindb connect to tendermint.
[2019-01-21 07:01:12 +0000] [30089] [INFO] Booting worker with pid: 30089
[2019-01-21 07:01:12 +0000] [30090] [INFO] Booting worker with pid: 30090
[2019-01-21 07:01:12 +0000] [30091] [INFO] Booting worker with pid: 30091
[2019-01-21 07:01:12 +0000] [30092] [INFO] Booting worker with pid: 30092
[2019-01-21 07:01:12 +0000] [30093] [INFO] Booting worker with pid: 30093
[2019-01-21 07:01:13 +0000] [30094] [INFO] Booting worker with pid: 30094
[2019-01-21 07:01:13 +0000] [30094] [INFO] Booting worker with pid: 30094
INFO      ... connection from Tendermint: localhost:56116 ...
[2019-01-21 07:01:14] [INFO] (abci.app)  ... connection from Tendermint: localhost:56116 ... (MainProcess - pid: 30041)
[2019-01-21 07:01:14] [INFO] (bigchaindb.core) Tendermint version: 0.22.8-40d6dc2e (MainProcess - pid: 30041)
INFO      ... connection from Tendermint: 10.1.2.12:56118 ...
[2019-01-21 07:01:14] [INFO] (abci.app)  ... connection from Tendermint: localhost:56118 ... (MainProcess - pid: 30041)
INFO      ... connection from Tendermint: 10.1.2.12:56120 ...
[2019-01-21 07:01:14] [INFO] (abci.app)  ... connection from Tendermint: localhost:56120 ... (MainProcess - pid: 30041)
[2019-01-21 07:01:17 +0000] [30053] [INFO] Handling signal: winch

**Comment by shubhamc15** [comment]
For me it show only 
 (MainProcess - pid: 21133)
[2019-01-21 12:34:34 +0530] [21145] [INFO] Starting gunicorn 19.9.0
[2019-01-21 12:34:34 +0530] [21145] [INFO] Listening at: http://127.0.0.1:9984 (21145)
[2019-01-21 12:34:34 +0530] [21145] [INFO] Using worker: sync
[2019-01-21 12:34:34 +0530] [21146] [INFO] Booting worker with pid: 21146
[2019-01-21 12:34:34 +0530] [21147] [INFO] Booting worker with pid: 21147
[2019-01-21 12:34:34 +0530] [21148] [INFO] Booting worker with pid: 21148
[2019-01-21 12:34:34 +0530] [21149] [INFO] Booting worker with pid: 21149
[2019-01-21 12:34:34 +0530] [21150] [INFO] Booting worker with pid: 21150
[2019-01-21 12:34:34 +0530] [21151] [INFO] Booting worker with pid: 21151
[2019-01-21 12:34:34 +0530] [21152] [INFO] Booting worker with pid: 21152
[2019-01-21 12:34:34 +0530] [21153] [INFO] Booting worker with pid: 21153
[2019-01-21 12:34:34 +0530] [21154] [INFO] Booting worker with pid: 21154
INFO      ABCIServer started on port: 26658
[2019-01-21 12:34:35] [INFO] (abci.app)  ABCIServer started on port: 26658 (MainProcess - pid: 21133)
======== Running on http://localhost:9985 ========
(Press CTRL+C to quit)

**Comment by shubhamc15** [comment]
and all ip i have set to localhost

**Comment by shubhamc15** [comment]
can you share me your Bigchaindb conf and  tendermint conf file? plz

**Comment by authwork** [comment]
bigchaindb conf
"tendermint": {
"host": "localhost",
"port": 26657
},

tendermint conf:
proxy_app = "tcp://localhost:26658"

**Comment by shubhamc15** [comment]
No luck bro : ( 
error:
 (MainProcess - pid: 21785)
[2019-01-21 12:46:58 +0530] [21797] [INFO] Starting gunicorn 19.9.0
[2019-01-21 12:46:58 +0530] [21797] [ERROR] Connection in use: ('localhost', 9984)
[2019-01-21 12:46:58 +0530] [21797] [ERROR] Retrying in 1 second.
[2019-01-21 12:46:59 +0530] [21797] [ERROR] Connection in use: ('localhost', 9984)
[2019-01-21 12:46:59 +0530] [21797] [ERROR] Retrying in 1 second.
INFO      ABCIServer started on port: 26658
[2019-01-21 12:46:59] [INFO] (abci.app)  ABCIServer started on port: 26658 (MainProcess - pid: 21785)
======== Running on http://localhost:9985 ========
(Press CTRL+C to quit)
[2019-01-21 12:47:00 +0530] [21797] [ERROR] Connection in use: ('localhost', 9984)
[2019-01-21 12:47:00 +0530] [21797] [ERROR] Retrying in 1 second.

**Comment by authwork** [comment]
How about change all localhost to a IP address~(127.0.0.1 or the ip address of ifconfig)

**Comment by shubhamc15** [comment]
@authwork  thanks bro I will try this on 18.04  and check
currently i am using 16.0 ubuntu

**Comment by shubhamc15** [comment]
what is a1a161c990c4114c8e8ed5155086801f99296197 in persistent_peers??

**Comment by CruzzRazor** [comment]
@authwork  how did u solved this issue u mensioned above at: https://github.com/bigchaindb/bigchaindb/issues/2581#issuecomment-455927050

I am also facing the same issue: please refer this issue i have raised:
https://github.com/bigchaindb/bigchaindb-driver/issues/499

**Comment by imvvk11** [comment]
> I will test it with localhost, wait for a few minutes, I will update here.
> 
> Update on 21/01/2019 15:31 PM.
> 
> ```
> INFO:bigchaindb.config_utils:Cannot find config file `/home/ta/.bigchaindb`.
> Generating default configuration for backend localmongodb
> API Server bind? (default `localhost:9984`):
> WebSocket Server scheme? (default `ws`):
> WebSocket Server host? (default `localhost`):
> WebSocket Server port? (default `9985`):
> Database host? (default `localhost`):
> Database port? (default `27017`):
> Database name? (default `bigchain`):
> Tendermint host? (default `localhost`)
> Tendermint port? (default `26657`)
> Configuration written to /home/ta/.bigchaindb
> Ready to go!
> ```
> 
> In $HOME/.tendermint/config/genesis.json
> 
> ```
> "validators": [
>     {
>       "pub_key": {
>         "type": "tendermint/PubKeyEd25519",
>         "value": "ZhhN5w9KWp3A65n/+HZMUUTwLjBg01zWj+zSha600Qw="
>       },
>       "power": "10",
>       "name": "student80"
>     }
> ```
> 
> In $HOME/.tendermint/config/config.toml
> 
> ```
> proxy_app = "tcp://127.0.0.1:26658"
> 
> # A custom human readable name for this node
> moniker = "student80"
> ...
> persistent_peers = "a1a161c990c4114c8e8ed5155086801f99296197@127.0.0.1:26656"
> ```
> 
> ![image](https://user-images.githubusercontent.com/29809742/51459322-1b7bb180-1d93-11e9-84b5-240776c63e08.png)
> @shubhamc15
> I have rebuilt it on a new machine with Ubuntu 18.04, and it works fine with localhost

What should be the key in persistent_peers, public or private?

**Comment by ttmc** [comment]
> What should be the key in persistent_peers, public or private?

Neither. `persistent_peers` must have the form:

```toml
persistent_peers = "<Member 1 node id>@<Member 1 hostname>:26656,\
<Member 2 node id>@<Member 2 hostname>:26656,\
<Member N node id>@<Member N hostname>:26656,"
```

You can get your own node's Tendermint node id using the Tendermint command

`tendermint show_node_id`

All if this is explained in the docs page http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html

**Comment by imvvk11** [comment]
> > What should be the key in persistent_peers, public or private?
> 
> Neither. `persistent_peers` must have the form:
> 
> ```
> persistent_peers = "<Member 1 node id>@<Member 1 hostname>:26656,\
> <Member 2 node id>@<Member 2 hostname>:26656,\
> <Member N node id>@<Member N hostname>:26656,"
> ```
> 
> You can get your own node's Tendermint node id using the Tendermint command
> 
> `tendermint show_node_id`
> 
> All if this is explained in the docs page http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html

Thankyou @ttmc 
I am able to do the transaction.

**Comment by imvvk11** [comment]
@ttmc Hi Troy,

How can I get or retrieve the timestamp on which the transaction is created?

Thanks.

**Comment by ttmc** [comment]
@imvvk11 BigchainDB transactions don't normally contain a timestamp (i.e. by default) because timestamps are notoriously tricky things. It's very difficult to trust them.

That said, if you are creating transactions, then you can stuff a timestamp into them, either into the asset.data (of a CREATE transaction) or the metadata of any transaction. See for example https://github.com/bigchaindb/BEPs/tree/master/13#transaction-components-metadata

**Comment by imvvk11** [comment]
> @imvvk11 BigchainDB transactions don't normally contain a timestamp (i.e. by default) because timestamps are notoriously tricky things. It's very difficult to trust them.
> 
> That said, if you are creating transactions, then you can stuff a timestamp into them, either into the asset.data (of a CREATE transaction) or the metadata of any transaction. See for example https://github.com/bigchaindb/BEPs/tree/master/13#transaction-components-metadata

@ttmc Thank you fot your help.

**Comment by imvvk11** [comment]
@ttmc Hi troy,

**Comment by ttmc** [comment]
@imvvk11 Transferring to yourself is the same as transferring to others: you just put your own public key as the recipient (new owner).

**Comment by imvvk11** [comment]
@ttmc Hi Troy,

**Comment by imvvk11** [comment]
> @imvvk11 Transferring to yourself is the same as transferring to others: you just put your own public key as the recipient (new owner).

@ttmc Hi Troy,

**Comment by ttmc** [comment]
@imvvk11 A common error is trying to transfer the same output a second time. That won't work.

When you first create an asset, there will be an output on the CREATE transaction. You would identify that output by its transaction id (== asset id) and its output index (0 for the first one).

[CREATE tx] --(output 0)

To transfer that output, you refer to the CREATE transaction id (== asset id) and the output index (0). That happens in a new TRANSFER transaction, which has its own, _new transaction id._

[CREATE tx] --(output 0)-- [TRANSFER tx] --(output 0)

To spend/transfer the output on that TRANSFER transaction, **you must find the transaction id of that TRANSFER transaction**. It will not be the same as the asset id or the transaction id of the CREATE transaction.

Every new TRANSFER transaction can contain new data in the "metadata" part of the transaction.

**Comment by imvvk11** [comment]
> @imvvk11 A common error is trying to transfer the same output a second time. That won't work.
> 
> When you first create an asset, there will be an output on the CREATE transaction. You would identify that output by its transaction id (== asset id) and its output index (0 for the first one).
> 
> [CREATE tx] --(output 0)
> 
> To transfer that output, you refer to the CREATE transaction id (== asset id) and the output index (0). That happens in a new TRANSFER transaction, which has its own, _new transaction id._
> 
> [CREATE tx] --(output 0)-- [TRANSFER tx] --(output 0)
> 
> To spend/transfer the output on that TRANSFER transaction, **you must find the transaction id of that TRANSFER transaction**. It will not be the same as the asset id or the transaction id of the CREATE transaction.
> 
> Every new TRANSFER transaction can contain new data in the "metadata" part of the transaction.



> @imvvk11 A common error is trying to transfer the same output a second time. That won't work.
> 
> When you first create an asset, there will be an output on the CREATE transaction. You would identify that output by its transaction id (== asset id) and its output index (0 for the first one).
> 
> [CREATE tx] --(output 0)
> 
> To transfer that output, you refer to the CREATE transaction id (== asset id) and the output index (0). That happens in a new TRANSFER transaction, which has its own, _new transaction id._
> 
> [CREATE tx] --(output 0)-- [TRANSFER tx] --(output 0)
> 
> To spend/transfer the output on that TRANSFER transaction, **you must find the transaction id of that TRANSFER transaction**. It will not be the same as the asset id or the transaction id of the CREATE transaction.
> 
> Every new TRANSFER transaction can contain new data in the "metadata" part of the transaction.

@ttmc  Thankyou.

**Comment by Yehezkiel-simbuang** [comment]
Hello, have you solve it? this issue Error: bdb.transactions.send_commit(fulfilled_creation_tx)
?, If you have solve it, tell me how you do it? i cant understand. i already get the HTTP response and it show 200 code which is success. But when i try commit a block, its get code 500: Server Internal Error. I already connected the validator and 3 sentry node using tendermint too
