### ISSUE TITLE
bigchaindb is not working after installation on rethinkdb and windows subsystem for linux

### ISSUE THREAD

**Issue by robelkebede44** [bigchaindb/bigchaindb#2618]
INFO:bigchaindb.config_utils:Configuration loaded from `/root/.bigchaindb`
[2019-01-07 22:23:25] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.3.0 (MainProcess - pid: 355)
[2019-01-07 22:23:25] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 355)
[2019-01-07 22:23:25] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process with public key 3qUoU8mZAcXfyHyjtWD2KPjtHMmByF99iHH9GUdCkQJR (MainProcess - pid: 355)
[2019-01-07 22:23:25] [INFO] (bigchaindb.processes) Initializing BigchainDB... (MainProcess - pid: 355)
[2019-01-07 22:23:25] [INFO] (bigchaindb.processes) Starting block (MainProcess - pid: 355)
[2019-01-07 22:23:26] [INFO] (bigchaindb.processes) Starting voter (MainProcess - pid: 355)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/rethinkdb/query.py", line 233, in get_last_voted_block_id
    .max(r.row['vote']['timestamp']))['vote']['timestamp']
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/rethinkdb/connection.py", line 27, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/ast.py", line 123, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 625, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 471, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlNonExistenceError: Cannot take the max of an empty stream.  (If you passed `max` a field name, it may be that no elements of the stream had that field.) in:
r.table('votes', read_mode='majority').filter(lambda var_1: (r.row['node_pubkey'] == r.expr('3qUoU8mZAcXfyHyjtWD2KPjtHMmByF99iHH9GUdCkQJR'))).max(lambda var_2: r.row['vote']['timestamp'])

**Comment by robelkebede44** [comment]
when i drop and initialize bigchaindb it worked
