### ISSUE TITLE
Python driver failing when trying to create multiple assets - ASAP

### ISSUE THREAD

**Issue by yajatvishwak** [bigchaindb/bigchaindb#2620]
`
from bigchaindb_driver import BigchainDB
import time

from bigchaindb_driver.crypto import generate_keypair

bdb = BigchainDB('http://35.200.186.173:9984/')
alice = generate_keypair()
for i in range(10):
   
    tx = bdb.transactions.prepare(
    operation='CREATE',
    signers=alice.public_key,
    asset={'data': {'message': f'J{i}'}})
    signed_tx = bdb.transactions.fulfill(
        tx,
        private_keys=alice.private_key
    )
    bdb.transactions.send_commit(signed_tx)
    print(f'Sending {i}')
    time.sleep(5)

`

We are trying to send multiple CREATE transaction signed by one user.
When we send it to the test net, it connects  properly and sends multiple assets.
But when we use, bigchaindb on GCP it fails after sending only a few transaction.

Execution:

s:/Untitled-1.py
Sending 0
Sending 1
Sending 2
Sending 3
Sending 4
Traceback (most recent call last):
  File "s:/Untitled-1.py", line 18, in <module>
    bdb.transactions.send_commit(signed_tx)
  File "C:\Users\Yajat Vishwakk\AppData\Local\Programs\Python\Python36\lib\site-packages\bigchaindb_driver\driver.py", line 375, in send_commit
    headers=headers)
  File "C:\Users\Yajat Vishwakk\AppData\Local\Programs\Python\Python36\lib\site-packages\bigchaindb_driver\transport.py", line 82, in forward_request
    backoff_cap=backoff_cap,
  File "C:\Users\Yajat Vishwakk\AppData\Local\Programs\Python\Python36\lib\site-packages\bigchaindb_driver\connection.py", line 91, in request
    **kwargs,
  File "C:\Users\Yajat Vishwakk\AppData\Local\Programs\Python\Python36\lib\site-packages\bigchaindb_driver\connection.py", line 128, in _request
    raise exc_cls(response.status_code, text, json, kwargs['url'])
bigchaindb_driver.exceptions.TransportError: (500, '{"message": "Internal Server Error"}\n', {'message': 'Internal Server Error'}, 'http://35.200.186.173:9984//api/v1/transactions/')

Let me know if more information is required.

**Comment by ttmc** [comment]
I guess you didn't get BigchainDB running on GCP properly. See the "Simple Deployment Template" at http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/index.html 

You can get more details about what's going wrong by looking in the logs. See http://docs.bigchaindb.com/projects/server/en/latest/appendices/log-rotation.html
