### ISSUE TITLE
message: 'HTTP Error: Requested page not reachable',   status: '500 INTERNAL SERVER ERROR',   requestURI: 'http://localhost:9984/api/v1/transactions?mode=commit'

### ISSUE THREAD

**Issue by amankakar** [bigchaindb/bigchaindb#2654]
# Testing local bigchaindb node gives Error
I am following bigchaindb Basic usage example from bigchaindb docs.
[https://docs.bigchaindb.com/projects/js-driver/en/latest/usage.html](https://docs.bigchaindb.com/projects/js-driver/en/latest/usage.html)
I am using following versions :
bigchaindb : 2.0
bigchaindb-driver: 4.0.0

 
# But I face following problem
In node console : 
`{ message: 'HTTP Error: Requested page not reachable',
  status: '500 INTERNAL SERVER ERROR',
  requestURI: 'http://localhost:9984/api/v1/transactions?mode=commit' }`

From bigchaindb server console : 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/web/views/transactions.py", line 98, in post
    status_code, message = bigchain.write_transaction(tx_obj, mode)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/lib.py", line 95, in write_transaction
    response = self.post_transaction(transaction, mode)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/lib.py", line 90, in post_transaction
    return requests.post(self.endpoint, json=payload)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=26657): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21900ae4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by mahmudinashar** [comment]
i'm facing also this problem. is someone have a solution ?
