### ISSUE TITLE
Can't start bigchaindb | module 'gevent' has no attribute 'signal'

### ISSUE THREAD

**Issue by lucaspojo** [bigchaindb/bigchaindb#2705]
Hi !

**Describe the bug**
Can't start mongodb due to python error.
Thx !
**Logs or terminal output**
```
[2020-07-24 11:35:48 +0200] [2701] [INFO] Booting worker with pid: 2701
[2020-07-24 11:35:49 +0200] [2702] [INFO] Booting worker with pid: 2702
======== Running on http://0.0.0.0:9985 ========
(Press CTRL+C to quit)INFO      ABCIServer started on port: 26658

[2020-07-24 11:35:49] [INFO] (abci.app)  ABCIServer started on port: 26658 (MainProcess - pid: 2673)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 397, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 137, in start
    return func(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/utils.py", line 48, in configure
    command(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/commands/bigchaindb.py", line 291, in run_start
    start(args)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/start.py", line 74, in start
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/abci/server.py", line 139, in run
    gevent.signal(signal.SIGQUIT, evt.set)
AttributeError: module 'gevent' has no attribute 'signal'
[2020-07-24 11:35:49 +0200] [2685] [INFO] Handling signal: term
[2020-07-24 11:35:49 +0200] [2686] [INFO] Worker exiting (pid: 2686)
[2020-07-24 11:35:49 +0200] [2687] [INFO] Worker exiting (pid: 2687)

```
**Desktop:**
 - Distribution: Ubuntu 18.04 
 - Bigchaindb version: 2.0.0
 - Tendermint version: 0.31.5-d2eab536
 - Mongodb version:  v3.6.3
- Python full version: Python 3.6.6

**Comment by lucaspojo** [comment]
**How to fix ?** _( but probably not best solution )_ : 

Edit : `/usr/local/lib/python3.6/dist-packages/abci/server.py`

and comment all `gevent.signal`   lines : ( 139 , 140, 141 )

**Comment by zzappie** [comment]
Hello @lucaspojo sorry about that! This issue is caused by gevent api change and fixed in latest  bigchaindb and bigcahaindb-abci release. I wouldn't recommend  arbitrarily commenting out code in system directories ;).
