### ISSUE TITLE
Adding validator ERORR :  "panic: Error initializing DB: resource temporarily unavailable"

### ISSUE THREAD

**Issue by Davsen39** [bigchaindb/bigchaindb#2713]
Goodmorning, 

I ran BigchainDB with all-in-one docker on two VM Ubuntu 18.04 connected each other via NatNetwork (following [this tutorial](http://docs.bigchaindb.com/en/latest/installation/node-setup/all-in-one-bigchaindb.html)). 
So here everything works fine. If i put on cmd line "docker exec -it bigchaindb bash" i can see everything working on the two VMs (i used [this python tutorial](https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html) on both and i can see on mongodb the blocks, assets and metadata etc etc.

My problem is that i want to try to connect that 2 nodes, so i have to do it throught tendermint, right?
I did it on this way:
I added the informations about NODE1(10.0.2.30) on the genesys.json file in NODE2(10.0.2.31):

> {
  "genesis_time": "2020-10-01T08:38:34.612309418Z",
  "chain_id": "test-chain-NlpHnU",
  "consensus_params": {
    "block_size_params": {
      "max_bytes": "22020096",
      "max_txs": "10000",
      "max_gas": "-1"
    },
    "tx_size_params": {
      "max_bytes": "10240",
      "max_gas": "-1"
    },
    "block_gossip_params": {
      "block_part_size_bytes": "65536"
    },
    "evidence_params": {
      "max_age": "100000"
    }
  },
  "validators": [
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "WiIWiaXOBYASioq4gOVl4gF1jv0F19Z7r2gj+lM6tGA="
      },
      "power": "10",
      "name": ""
    },
    **{
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "EplWeh+tFMVOFpz8MBd48Aet1YMcxnxsW0SF3MVjnnA="
      },
      "power": "10",
      "name": ""
    }**
  ],
  "app_hash": ""
}

So then i tried to do it:

>tendermint node --p2p.persistent_peers "EplWeh+tFMVOFpz8MBd48Aet1YMcxnxsW0SF3MVjnnA=@10.0.2.30:26656,WiIWiaXOBYASioq4gOVl4gF1jv0F19Z7r2gj+lM6tGA=@10.0.2.31:26656" 

But it says :

> panic: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/tendermint/tendermint/libs/db.NewDB(0xdb8776, 0xa, 0xc420037e40, 0x7, 0xc4207abae0, 0x10, 0xc420116820, 0x1a)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/libs/db/db.go:33 +0x157
github.com/tendermint/tendermint/node.DefaultDBProvider(0xc4207c6680, 0xc4207c6680, 0x7f60e8290001, 0x401783, 0xc42009cdf8)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/node/node.go:60 +0xd2
github.com/tendermint/tendermint/node.NewNode(0xc4201abd40, 0xf8d9e0, 0xc420144d80, 0xf80da0, 0xc42079bb90, 0xc4207c4d70, 0xf15c88, 0xf15c90, 0xf8c460, 0xc4207c6280, ...)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/node/node.go:149 +0xcb
github.com/tendermint/tendermint/node.DefaultNewNode(0xc4201abd40, 0xf8c460, 0xc4207c6280, 0x0, 0xc42009db20, 0x5887f0)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/node/node.go:83 +0x1cf
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc4200b2d80, 0xc4201d5180, 0x0, 0x2, 0x0, 0x0)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:53 +0x5e
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200b2d80, 0xc4201d5140, 0x2, 0x2, 0xc4200b2d80, 0xc4201d5140)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1468800, 0xcc9de0, 0xc42009de01, 0xc4201d50a0)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(0x1468800, 0xc4201d50a0, 0xc42009de98)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1468800, 0xf17be0, 0x2, 0xc4201d7e40)
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/home/jslave/workspace/02.Fetch.Binary@2/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24d

Why i have this problem?
I am doing something wrong?

Thank you so much

**Comment by javaandra** [comment]
Hi @Davsen39,
I am stuck with a very similar error like you, but with the "simple deployment template"  not with docker, with a "single-node network". I've also opened an issue #2719. Did you manage to find a solution in the meanwhile?
Thank you!

Regards,
Andra

**Comment by NaveenReddy198** [comment]
hii @Davsen39  Is that issue solved?bcoz iam having the similar issue
