### ISSUE TITLE
HTTP Server API Endpoint not working

### ISSUE THREAD

**Issue by gekko68** [bigchaindb/bigchaindb#404]
Hi,
I am using docker 0.4.2 tag and with this version the HTTP endpoint is not working. I am still using : curl --include \
     --request POST \
     --header "Content-Type: application/json" \
     --data-binary "{
  \"id\": \"2f7b7768188583faea3868e65c9474a475ce6065402334a7a5844ee64c9e20b0\",
  \"signature\": \"30440220283066391658833bf098de547a339938da6307f5953cfe9df71689017abe224b0220424a83f689d97b3b4a943cb57c2c2427f71eb592c86fe1c50921b178ee84910b\",
  \"transaction\": {
    \"current_owner\": \"cpSayyvd4HH18GYAMwu6KvGKt7GN2cEdahpRA4ivQ1Lw\",
    \"data\": {
      \"hash\": \"efbde2c3aee204a69b7696d4b10ff31137fe78e3946306284f806e2dfc68b805\",
      \"payload\": null
    },
  \"input\": null,
  \"new_owner\": \"cpSayyvd4HH18GYAMwu6KvGKt7GN2cEdahpRA4ivQ1Lw\",
  \"operation\": \"CREATE\",
    \"timestamp\": \"1456847051.247979\"
  }
}" \
'http://localhost:9984/api/v1/transactions/'

for testing purposes and the bigchain log shows an error 

INFO:bigchaindb.commands.bigchain:BigchainDB Version 0.4.2
INFO:bigchaindb.config_utils:Configuration loaded from `/data/.bigchaindb`
INFO:bigchaindb.commands.bigchain:RethinkDB started with PID 8
INFO:bigchaindb.commands.bigchain:Starting BigchainDB main process
INFO:bigchaindb.processes:Initializing BigchainDB...
INFO:bigchaindb.processes:starting bigchain mapper
INFO:bigchaindb.processes:starting backlog mapper
INFO:bigchaindb.processes:starting block
INFO:bigchaindb.processes:starting voter
INFO:bigchaindb.processes:starting election
INFO:bigchaindb.block:bootstraping block module...
INFO:bigchaindb.voter:voter waiting for new blocks
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:new_block arrived to voter
INFO:bigchaindb.voter:new_block arrived to voter
[2016-06-24 18:16:35 +0000] [85] [INFO] Starting gunicorn 19.6.0
[2016-06-24 18:16:35 +0000] [85] [INFO] Listening at: http://0.0.0.0:9984 (85)
[2016-06-24 18:16:35 +0000] [85] [INFO] Using worker: threads
[2016-06-24 18:16:35 +0000] [101] [INFO] Booting worker with pid: 101
INFO:bigchaindb.voter:updating block 49549f62f5bc149868bc11005a8b64e4995520f525479f6359732381f134487e with number 1 and with vote {'vote': {'previous_block': '1124b45729d9153d831ef46ae321567a3dc012dd01292a26e17efcc1161a01ea', 'invalid_reason': None, 'is_block_valid': False, 'voting_for_block': '49549f62f5bc149868bc11005a8b64e4995520f525479f6359732381f134487e', 'timestamp': '1466792196'}, 'node_pubkey': 'BK2E3YfLPhvwzYumZ4msDhT5pxH8PEUu2mSHd6Z4Q51k', 'signature': '2aZGhr9hPjsuZaRadxj3aViqXk5dwgnjK3WRNxeM2Ye7zk77YQAB9bD3VJ5dt87KSnp31TUBVB57v3Ytp63RxvGT'}
[2016-06-24 18:16:35 +0000] [102] [INFO] Booting worker with pid: 102
INFO:bigchaindb.block:finished reading past transactions
INFO:bigchaindb.voter:updating block 0cf03627076e7cb3fa1e61eee815d4c408ec5cbfe9065535c109087a577ceb21 with number 2 and with vote {'vote': {'previous_block': '49549f62f5bc149868bc11005a8b64e4995520f525479f6359732381f134487e', 'invalid_reason': None, 'is_block_valid': False, 'voting_for_block': '0cf03627076e7cb3fa1e61eee815d4c408ec5cbfe9065535c109087a577ceb21', 'timestamp': '1466792196'}, 'node_pubkey': 'BK2E3YfLPhvwzYumZ4msDhT5pxH8PEUu2mSHd6Z4Q51k', 'signature': '4HKdL1WZFAiv2c1zjyNZbcRstYaZ6ud3hcdL38hw8cpMYxQtjZ3sZxcKzRvFMu7495E61uXUG739BrxKEvhNXs6V'}
INFO:bigchaindb.voter:updating block b766a0129d841bdb8ab186cda5429dc0fe0a381c2ef85448a81f051ad120e7bc with number 3 and with vote {'vote': {'previous_block': '0cf03627076e7cb3fa1e61eee815d4c408ec5cbfe9065535c109087a577ceb21', 'invalid_reason': None, 'is_block_valid': False, 'voting_for_block': 'b766a0129d841bdb8ab186cda5429dc0fe0a381c2ef85448a81f051ad120e7bc', 'timestamp': '1466792196'}, 'node_pubkey': 'BK2E3YfLPhvwzYumZ4msDhT5pxH8PEUu2mSHd6Z4Q51k', 'signature': 'KgXPWjcWhmtMy4zUzycjVy12pk9vyvgsavCUeZ77UeuWNtLLJK9RkMF2iXKqiZZLeW7b1nSwqzxAkvd3LHmEqfW'}
INFO:bigchaindb.block:finished bootstraping block module...
INFO:bigchaindb.block:starting block module...
INFO:bigchaindb.processes:
****************************************************************************
*                                                                          *
*   Initialization complete. BigchainDB is ready and waiting for events.   *
*   You can send events through the API documented at:                     *
*    - http://docs.bigchaindb.apiary.io/                                   *
*                                                                          *
*   Listening to client connections on: 0.0.0.0:9984                       *
*                                                                          *
****************************************************************************

[2016-06-24 18:16:35 +0000] [128] [INFO] Booting worker with pid: 128
INFO:bigchaindb.block:exiting block module...
Process validate_transactions:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bigchaindb/block.py", line 74, in validate_transactions
    is_valid_transaction = b.is_valid_transaction(tx)
  File "/usr/src/app/bigchaindb/core.py", line 369, in is_valid_transaction
    self.validate_transaction(transaction)
  File "/usr/src/app/bigchaindb/core.py", line 354, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/src/app/bigchaindb/consensus.py", line 137, in validate_transaction
    if transaction['transaction']['fulfillments'][0]['input']:
KeyError: 'fulfillments'
Process validate_transactions:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bigchaindb/block.py", line 74, in validate_transactions
    is_valid_transaction = b.is_valid_transaction(tx)
  File "/usr/src/app/bigchaindb/core.py", line 369, in is_valid_transaction
    self.validate_transaction(transaction)
  File "/usr/src/app/bigchaindb/core.py", line 354, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/src/app/bigchaindb/consensus.py", line 137, in validate_transaction
    if transaction['transaction']['fulfillments'][0]['input']:
KeyError: 'fulfillments'
[2016-06-24 18:16:35 +0000] [140] [INFO] Booting worker with pid: 140
[2016-06-24 18:16:35 +0000] [141] [INFO] Booting worker with pid: 141
ERROR:bigchaindb.web.server:Exception on /api/v1/transactions/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/bigchaindb/web/views.py", line 89, in create_transaction
    tx = util.transform_create(tx)
  File "/usr/src/app/bigchaindb/util.py", line 611, in transform_create
    new_tx = create_tx(b.me, transaction['fulfillments'][0]['current_owners'], None, 'CREATE', payload=payload)
KeyError: 'fulfillments'

**Comment by r-marques** [comment]
The transaction structure changed significantly in `v0.3.0` https://bigchaindb.readthedocs.io/en/latest/topic-guides/models.html#transaction-concepts.
We added support for multiple inputs and outputs and implemented the crypto-conditions from the interledger spec https://bigchaindb.readthedocs.io/en/latest/topic-guides/models.html#conditions-and-fulfillments.

You can check the temp_client to see how the new transactions look https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-driver-api-examples.html

Your problem is that you are trying to POST a transaction that has a schema that is no longer valid since `v0.3.0`

**Comment by diminator** [comment]
@r-marques is this still open?

**Comment by r-marques** [comment]
This was a problem with a mismatch between different versions of bigchaindb.
