### ISSUE TITLE
BigchainDB container doesn't exit gracefully

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#43]
The docker container works! Thank you!

```python
$ docker-compose up
Creating bigchaindb_rethinkdb-data_1
Creating bigchaindb_rethinkdb_1
Creating bigchaindb_bigchaindb_1
Attaching to bigchaindb_rethinkdb-data_1, bigchaindb_rethinkdb_1, bigchaindb_bigchaindb_1
rethinkdb_1      | Recursively removing directory /data/rethinkdb_data/tmp
rethinkdb_1      | Initializing directory /data/rethinkdb_data
rethinkdb_1      | Running rethinkdb 2.2.4~0jessie (GCC 4.9.2)...
rethinkdb_1      | Running on Linux 3.13.0-68-generic x86_64
rethinkdb_1      | Loading data from directory /data/rethinkdb_data
bigchaindb_rethinkdb-data_1 exited with code 0
rethinkdb_1      | Listening for intracluster connections on port 29015
rethinkdb_1      | Listening for client driver connections on port 28015
rethinkdb_1      | Listening for administrative HTTP connections on port 8080
rethinkdb_1      | Listening on addresses: 127.0.0.1, 172.17.0.3, ::1, fe80::42:acff:fe11:3%1640
rethinkdb_1      | Server ready, "643d16d5c461_92r" 140afe00-9284-40b0-8c35-a6b5c291106f
bigchaindb_1     | INFO:bigchaindb.config_utils:Configuration loaded from `/root/.bigchaindb_docker/config`
bigchaindb_1     | INFO:bigchaindb.db.utils:Create:
bigchaindb_1     | INFO:bigchaindb.db.utils: - database `bigchain`
bigchaindb_1     | INFO:bigchaindb.db.utils: - tables
bigchaindb_1     | INFO:bigchaindb.db.utils: - indexes
bigchaindb_1     | INFO:bigchaindb.db.utils: - genesis block
bigchaindb_1     | INFO:bigchaindb.db.utils:Done, have fun!
bigchaindb_1     | INFO:bigchaindb.commands.bigchain:Start bigchaindb main process
bigchaindb_1     | INFO:bigchaindb.processes:starting bigchain mapper
bigchaindb_1     | INFO:bigchaindb.processes:starting backlog mapper
bigchaindb_1     | INFO:bigchaindb.processes:starting block
bigchaindb_1     | INFO:bigchaindb.processes:starting voter
bigchaindb_1     | INFO:bigchaindb.block:bootstraping block module...
bigchaindb_1     | INFO:bigchaindb.block:finished reading past transactions
bigchaindb_1     | INFO:bigchaindb.voter:voter waiting for new blocks
bigchaindb_1     | INFO:bigchaindb.block:finished bootstraping block module...
bigchaindb_1     | INFO:bigchaindb.block:starting block module...
```

However, the exit can be messy when I kill the container:

```python
^CGracefully stopping... (press Ctrl+C again to force)
Stopping bigchaindb_bigchaindb_1 ... done
Stopping bigchaindb_rethinkdb_1 ... done
rethinkdb_1      | Server got SIGTERM from pid 0, uid 0; shutting down...
rethinkdb_1      | Shutting down client connections...
rethinkdb_1      | All client connections closed.
rethinkdb_1      | Shutting down storage engine... (This may take a while if you had a lot of unflushed data in the writeback cache.)
bigchaindb_1     | Process backlog_mapper:
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
bigchaindb_1     |     self.run()
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
bigchaindb_1     |     self._target(*self._args, **self._kwargs)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/processes.py", line 28, in map_backlog
bigchaindb_1     |     for change in r.table('backlog').changes().run(b.conn):
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 240, in __next__
bigchaindb_1     |     return self._get_next(None)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 251, in _get_next
bigchaindb_1     |     self.conn._read_response(self.query, deadline)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 470, in _read_response
bigchaindb_1     |     = self._socket.recvall(12, deadline)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 369, in recvall
bigchaindb_1     |     raise ReqlDriverError("Connection is closed.")
bigchaindb_1     | rethinkdb.errors.ReqlDriverError: Connection is closed.
bigchaindb_1     | Process bigchain_mapper:
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
bigchaindb_1     |     self.run()
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
bigchaindb_1     |     self._target(*self._args, **self._kwargs)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/processes.py", line 49, in map_bigchain
bigchaindb_1     |     for change in r.table('bigchain').changes().run(b.conn):
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 240, in __next__
bigchaindb_1     |     return self._get_next(None)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 251, in _get_next
bigchaindb_1     |     self.conn._read_response(self.query, deadline)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 470, in _read_response
bigchaindb_1     |     = self._socket.recvall(12, deadline)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 369, in recvall
bigchaindb_1     |     raise ReqlDriverError("Connection is closed.")
bigchaindb_1     | rethinkdb.errors.ReqlDriverError: Connection is closed.
rethinkdb_1      | Storage engine shut down.
bigchaindb_rethinkdb_1 exited with code 0
bigchaindb_bigchaindb_1 exited with code 137
```

and if I try to bring it up again, it fails:

```python
$ docker-compose up
Starting bigchaindb_rethinkdb-data_1
Starting bigchaindb_rethinkdb_1
Starting bigchaindb_bigchaindb_1
Attaching to bigchaindb_rethinkdb-data_1, bigchaindb_rethinkdb_1, bigchaindb_bigchaindb_1
rethinkdb_1      | Running rethinkdb 2.2.4~0jessie (GCC 4.9.2)...
rethinkdb_1      | Running on Linux 3.13.0-68-generic x86_64
rethinkdb_1      | Loading data from directory /data/rethinkdb_data
rethinkdb_1      | Listening for intracluster connections on port 29015
rethinkdb_1      | Listening for client driver connections on port 28015
rethinkdb_1      | Listening for administrative HTTP connections on port 8080
rethinkdb_1      | Listening on addresses: 127.0.0.1, 172.17.0.3, ::1, fe80::42:acff:fe11:3%1646
rethinkdb_1      | Server ready, "643d16d5c461_92r" 140afe00-9284-40b0-8c35-a6b5c291106f
bigchaindb_rethinkdb-data_1 exited with code 0
bigchaindb_1     | INFO:bigchaindb.config_utils:Configuration loaded from `/root/.bigchaindb_docker/config`
bigchaindb_1     | INFO:bigchaindb.commands.bigchain:Start bigchaindb main process
bigchaindb_1     | INFO:bigchaindb.processes:starting bigchain mapper
bigchaindb_1     | INFO:bigchaindb.processes:starting backlog mapper
bigchaindb_1     | INFO:bigchaindb.processes:starting block
bigchaindb_1     | INFO:bigchaindb.processes:starting voter
bigchaindb_1     | INFO:bigchaindb.block:bootstraping block module...
bigchaindb_1     | Process bigchain_mapper:
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
bigchaindb_1     |     self.run()
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
bigchaindb_1     |     self._target(*self._args, **self._kwargs)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/processes.py", line 49, in map_bigchain
bigchaindb_1     |     for change in r.table('bigchain').changes().run(b.conn):
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/ast.py", line 118, in run
bigchaindb_1     |     return c._start(self, **global_optargs)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 595, in _start
bigchaindb_1     |     return self._instance.run_query(q, global_optargs.get('noreply', False))
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 457, in run_query
bigchaindb_1     |     raise res.make_error(query)
bigchaindb_1     | rethinkdb.errors.ReqlOpFailedError: cannot subscribe to table `bigchain.bigchain`: primary replica for shard ["", +inf) not available in:
bigchaindb_1     | r.table('bigchain').changes()
bigchaindb_1     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bigchaindb_1     | Process backlog_mapper:
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
bigchaindb_1     |     self.run()
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
bigchaindb_1     |     self._target(*self._args, **self._kwargs)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/processes.py", line 28, in map_backlog
bigchaindb_1     |     for change in r.table('backlog').changes().run(b.conn):
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/ast.py", line 118, in run
bigchaindb_1     |     return c._start(self, **global_optargs)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 595, in _start
bigchaindb_1     |     return self._instance.run_query(q, global_optargs.get('noreply', False))
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 457, in run_query
bigchaindb_1     |     raise res.make_error(query)
bigchaindb_1     | rethinkdb.errors.ReqlOpFailedError: cannot subscribe to table `bigchain.backlog`: primary replica for shard ["", +inf) not available in:
bigchaindb_1     | r.table('backlog').changes()
bigchaindb_1     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bigchaindb_1     | Process block:
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
bigchaindb_1     |     self.run()
bigchaindb_1     |   File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
bigchaindb_1     |     self._target(*self._args, **self._kwargs)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/block.py", line 180, in start
bigchaindb_1     |     self.q_new_transaction = self.bootstrap()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/block.py", line 166, in bootstrap
bigchaindb_1     |     .run(b.conn)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/ast.py", line 118, in run
bigchaindb_1     |     return c._start(self, **global_optargs)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 595, in _start
bigchaindb_1     |     return self._instance.run_query(q, global_optargs.get('noreply', False))
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 457, in run_query
bigchaindb_1     |     raise res.make_error(query)
bigchaindb_1     | rethinkdb.errors.ReqlOpFailedError: Cannot perform read: primary replica for shard ["", +inf) not available in:
bigchaindb_1     | r.table('backlog').between(['rww8pSM3SDPLZrDoDjhoAWu8nds9FqHcqYJpuUPi3Q3h', r.minval], ['rww8pSM3SDPLZrDoDjhoAWu8nds9FqHcqYJpuUPi3Q3h', r.maxval], index='assignee__transaction_timestamp').order_by(index=r.asc('assignee__transaction_timestamp'))
bigchaindb_1     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bigchaindb_1     | Traceback (most recent call last):
bigchaindb_1     |   File "/usr/local/bin/bigchaindb", line 9, in <module>
bigchaindb_1     |     load_entry_point('BigchainDB==0.1.2', 'console_scripts', 'bigchaindb')()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/commands/bigchain.py", line 123, in main
bigchaindb_1     |     start(parser, globals())
bigchaindb_1     |   File "/usr/src/app/bigchaindb/commands/utils.py", line 41, in start
bigchaindb_1     |     func(args)
bigchaindb_1     |   File "/usr/src/app/bigchaindb/commands/bigchain.py", line 92, in run_start
bigchaindb_1     |     processes.start()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/processes.py", line 82, in start
bigchaindb_1     |     p_voter.start()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/voter.py", line 176, in start
bigchaindb_1     |     self.bootstrap()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/voter.py", line 160, in bootstrap
bigchaindb_1     |     last_voted = b.get_last_voted_block()
bigchaindb_1     |   File "/usr/src/app/bigchaindb/core.py", line 580, in get_last_voted_block
bigchaindb_1     |     .run(self.conn)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/ast.py", line 118, in run
bigchaindb_1     |     return c._start(self, **global_optargs)
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 595, in _start
bigchaindb_1     |     return self._instance.run_query(q, global_optargs.get('noreply', False))
bigchaindb_1     |   File "/usr/local/lib/python3.5/site-packages/rethinkdb/net.py", line 457, in run_query
bigchaindb_1     |     raise res.make_error(query)
bigchaindb_1     | rethinkdb.errors.ReqlOpFailedError: Cannot perform read: primary replica for shard ["", +inf) not available in:
bigchaindb_1     | r.table('bigchain').filter(lambda var_1: r.row['block']['voters'].contains('rww8pSM3SDPLZrDoDjhoAWu8nds9FqHcqYJpuUPi3Q3h')).filter(lambda var_2: var_2['votes'].contains(lambda var_3: (var_3['node_pubkey'] == r.expr('rww8pSM3SDPLZrDoDjhoAWu8nds9FqHcqYJpuUPi3Q3h')))).order_by(r.desc('block_number')).limit(1)
bigchaindb_1     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                          
bigchaindb_bigchaindb_1 exited with code 1
```

**Comment by SohKai** [comment]
I'm just running `bigchain start` from the command line, but the exit is also quite messy:

```python
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
Process block_updater:
Process block_validator:
Process block_voter:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process block_feeder:
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/voter.py", line 120, in vote
    elem = self.q_validated_block.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/voter.py", line 140, in update_block
    elem = self.q_voted_block.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = rTraceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/voter.py", line 46, in get
    return self.unvoted_blocks.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/voter.py", line 74, in feed_blocks
    block = block_stream.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/voter.py", line 48, in get
    return self.new_blocks.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._reTraceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/voter.py", line 92, in validate
    new_block = self.q_blocks_to_validate.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chProcess delete_transactions:
Process validate_transactions:
Process write_blocks:
Process create_blocks:
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 113, in write_blocks
    block = self.q_block.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
Traceback (most recent call last):
KeyboardInterrupt
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
Process filter_transactions:
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 82, in create_blocks
    tx = self.q_tx_validated.get(timeout=5)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 104, in get
    if timeout < 0 or not self._poll(timeout):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/selectors.py", line 367, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
ead(handle, remaining)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 134, in delete_transactions
    tx = self.q_tx_delete.get(timeout=5)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 104, in get
    if timeout < 0 or not self._poll(timeout):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
cv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/selectors.py", line 367, in select
    fd_event_list = self._poll.poll(timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
KeyboardInterrupt
unk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
KeyboardInterrupt
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 35, in filter_by_assignee
    tx = self.q_new_transaction.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 55, in validate_transactions
    tx = self.q_tx_to_validate.get()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Process backlog_mapper:
Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Process bigchain_mapper:
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/processes.py", line 28, in map_backlog
    for change in r.table('backlog').changes().run(b.conn):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 240, in __next__
    return self._get_next(None)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 251, in _get_next
    self.conn._read_response(self.query, deadline)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 479, in _read_response
    raise ex
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 470, in _read_response
    = self._socket.recvall(12, deadline)
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 341, in recvall
    chunk = self._socket.recv(length - len(res))
KeyboardInterrupt
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/processes.py", line 49, in map_bigchain
    for change in r.table('bigchain').changes().run(b.conn):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 240, in __next__
    return self._get_next(None)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 251, in _get_next
    self.conn._read_response(self.query, deadline)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 479, in _read_response
    raise ex
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 470, in _read_response
    = self._socket.recvall(12, deadline)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/rethinkdb/net.py", line 341, in recvall
    chunk = self._socket.recv(length - len(res))
KeyboardInterrupt
Process block:
Traceback (most recent call last):
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 187, in start
    self._start()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/site-packages/bigchaindb/block.py", line 210, in _start
    p_filter.join()
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/Users/Brett/anaconda/envs/bigchain/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

It'd be nice to catch the `SIGINT` and gracefully shut down `bigchain`. I guess `bigchain` isn't meant to be shut down and restarted very often once it's running, but this is still quite scary to see on the first exit.

In comparison, see how rethinkdb shuts down:

```python
^CServer got SIGINT from pid 558, uid 501; shutting down...
Shutting down client connections...
All client connections closed.
Shutting down storage engine... (This may take a while if you had a lot of unflushed data in the writeback cache.)
Storage engine shut down.
```
