### ISSUE TITLE
bigchaindb drop raises exception if database does not exist

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#437]
If the bigchain database does not exist, running `bigchaindb drop` raises and exception:

``` bash
$ bigchaindb drop
INFO:bigchaindb.config_utils:Configuration loaded from `/home/rodmar/.bigchaindb`
Do you want to drop `bigchain` database? [y/n]: y
INFO:bigchaindb.db.utils:Drop database `bigchain`
Traceback (most recent call last):
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/db/utils.py", line 88, in drop
    r.db_drop(dbname).run(conn)
  File "/home/rodmar/.venvs/bigchaindb/lib/python3.4/site-packages/rethinkdb/ast.py", line 118, in run
    return c._start(self, **global_optargs)
  File "/home/rodmar/.venvs/bigchaindb/lib/python3.4/site-packages/rethinkdb/net.py", line 625, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/home/rodmar/.venvs/bigchaindb/lib/python3.4/site-packages/rethinkdb/net.py", line 468, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlOpFailedError: Database `bigchain` does not exist in:
r.db_drop('bigchain')
^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodmar/.venvs/bigchaindb/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB', 'console_scripts', 'bigchaindb')()
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/commands/bigchain.py", line 306, in main
    utils.start(parser, globals())
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/commands/utils.py", line 95, in start
    func(args)
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/commands/bigchain.py", line 149, in run_drop
    db.drop(assume_yes=args.yes)
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/db/utils.py", line 91, in drop
    raise exceptions.DatabaseDoesNotExist('Database `{}` does not exist'.format(dbname))
bigchaindb.exceptions.DatabaseDoesNotExist: Database `bigchain` does not exist
```

The exception should be catched and a message printed the same way that when running `bigchaindb init` and the database already exists:

``` bash
$ bigchaindb init
INFO:bigchaindb.config_utils:Configuration loaded from `/home/rodmar/.bigchaindb`
The database already exists.
If you wish to re-initialize it, first drop it.
```

**Comment by anujism** [comment]
Please assign this issue to me. Thanks.

**Comment by TimDaub** [comment]
> Please assign this issue to me. Thanks.

Hi @anujism. For some reason @github doesn't allow to assign users that are not part of the organization :rage:.

Here's the plan: I've assigned the ticket to me now and I'll wait and review your PR. [This document](https://github.com/bigchaindb/bigchaindb/blob/master/CONTRIBUTING.md) gives you a better idea on how to further proceed with contributing (NOTE: CLA signing part).

If you have questions, please let me know (tim@bigchaindb.com).

Have fun :)
