### ISSUE TITLE
Changefeed abort when a cluster runs

### ISSUE THREAD

**Issue by zzy131250** [bigchaindb/bigchaindb#512]
Hello there,
I have been meeting a problem, I set up a 6-node cluster, it runs quite well at the beginning, but when up for about 2 days, every bigchaindb node report the error of changefeed abort and I can no longer insert txs into it. How can I solve it?

**Comment by zzy131250** [comment]
The error is like this:

Process backlog_mapper:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/processes.py", line 44, in map_backlog
    for change in r.table('backlog').changes().run(b.conn):
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 245, in __next__
    return self._get_next(None)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 255, in _get_next
    raise self.error
rethinkdb.errors.ReqlOpFailedError: Changefeed aborted (unavailable) in:
r.table('backlog').changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Process bigchain_mapper:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/processes.py", line 65, in map_bigchain
    for change in r.table('bigchain').changes().run(b.conn):
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 245, in __next__
    return self._get_next(None)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 255, in _get_next
    raise self.error
rethinkdb.errors.ReqlOpFailedError: Changefeed aborted (unavailable) in:
r.table('bigchain').changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by r-marques** [comment]
Hi @zzy131250,

We have not encountered this problem before.
I assume that this happens when for some reason the connection to the database goes down.
The way to solve this would be add logic to reconnect if the changefeed connection goes down (maybe a wrapper around the changefeed).

I will mark this as a bug so that we can investigate this further.

**Comment by r-marques** [comment]
Yes,
what happens is that the database is running normally and you can write transactions normally into the backlog, but since the changefeed is down the nodes are not notified of the new transactions, blocks are not created and the transactions are not moved to the bigchain table.
After you restart the bigchaindb processes there is a bootstrap routine that reads past transactions from the backlog and everything starts working normally.

We just need to add the logic so that bigchaindb can automatically recover if the changefeed connection goes down.

**Comment by zzy131250** [comment]
Cool then. Thanks.

**Comment by ttmc** [comment]
@vrde Can this be closed now that PR #623 is merged?
