### ISSUE TITLE
Bigchaindb utf-8 support?

### ISSUE THREAD

**Issue by zzy131250** [bigchaindb/bigchaindb#529]
Hello,
I notice that bigchaindb doesn't support utf-8 encoded payload currently, will it support utf-8 encoded payload in the future?
When I insert utf-8 encoded payload, the error is like this:

``` python
'ascii' codec can't encode characters in position 686-687: ordinal not in range(128)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/spyne/application.py", line 151, in process_request
    ctx.out_object = self.call_wrapper(ctx)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/spyne/application.py", line 235, in call_wrapper
    retval = ctx.descriptor.service_class.call_wrapper(ctx)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/spyne/service.py", line 207, in call_wrapper
    return ctx.function(*args)
  File "/root/new_chain/Blockchain_webservices/django_web/soap_rpc/views.py", line 95, in create_transaction
    return data_wrapper.create_transaction(public_key, who, where, when, thing)
  File "/root/new_chain/Blockchain_webservices/django_web/soap_rpc/wrapper.py", line 76, in create_transaction
    tx_signed = self.b.sign_transaction(tx, self.b.me_private)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/bigchaindb/core.py", line 88, in sign_transaction
    return self.consensus.sign_transaction(transaction, *args, bigchain=self, **kwargs)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/bigchaindb/consensus.py", line 226, in sign_transaction
    return util.sign_tx(transaction, private_key, bigchain=bigchain)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/bigchaindb/util.py", line 344, in sign_tx
    key_pairs)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/bigchaindb/util.py", line 374, in fulfill_simple_signature_fulfillment
    parsed_fulfillment.sign(serialize(fulfillment_message), key_pairs[current_owner])
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/cryptoconditions/types/ed25519.py", line 69, in sign
    self.signature = sk.sign(message, encoding=None)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/cryptoconditions/crypto.py", line 161, in sign
    data = data.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 686-687: ordinal not in range(128)
```

**Comment by r-marques** [comment]
We should support utf-8.
The exception seems to come from cryptoconditions.
I will create an issue in the cryptoconditions repo to get this fixed

**Comment by r-marques** [comment]
Linking here to the cryptoconditions issue https://github.com/bigchaindb/cryptoconditions/issues/19
