### ISSUE TITLE
load example error

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#654]
Problem reported by @nicksavers

```bash
$ docker run --rm -v "$HOME/bigchaindb_docker:/data" --link bigchaindb bigchaindb/bigchaindb load
INFO:bigchaindb.config_utils:Configuration loaded from `/data/.bigchaindb`
INFO:bigchaindb.commands.bigchain:Starting 1 processes
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 271, in __init__
    self._socket = socket.create_connection((self.host, self.port), timeout)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bigchaindb/commands/bigchain.py", line 201, in _run_load
    b.write_transaction(tx)
  File "/usr/src/app/bigchaindb/core.py", line 113, in write_transaction
    .insert(signed_transaction, durability=durability))
  File "/usr/src/app/bigchaindb/db/utils.py", line 47, in run
    self._connect()
  File "/usr/src/app/bigchaindb/db/utils.py", line 62, in _connect
    db=self.db)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 661, in connect
    return conn.reconnect(timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 572, in reconnect
    return self._instance.connect(timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 430, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 337, in __init__
    (self.host, self.port, str(ex)))
rethinkdb.errors.ReqlDriverError: Could not connect to localhost:28015. Error: [Errno 111] Connection refused
```

**Comment by vanipolnedi** [comment]
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.40.20.91', port=9984): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample1.py", line 40, in <module>
    sent_creation_tx = bdb.transactions.send_commit(fulfilled_creation_tx)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/driver.py", line 411, in send_commit
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/transport.py", line 82, in forward_request
    backoff_cap=backoff_cap,
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 91, in request
    **kwargs,
  File "/usr/local/lib/python3.6/site-packages/bigchaindb_driver/connection.py", line 120, in _request
    response = self.session.request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.40.20.91', port=9984): Read timed out. (read timeout=20)

i'm getting error like this...any suggestions please
