### ISSUE TITLE
How many database connecttions can the rethinkdb have？

### ISSUE THREAD

**Issue by lingbage** [bigchaindb/bigchaindb#770]
How many database connections can the bigchaindb have, and is it released immediately after each `run(self.conn)`?

**Comment by lingbage** [comment]
When I use `bigchiandb load -m 20`, after a period of time, bigchaindb will be reported overtime mistakes,Where do I do wrong?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/web/views/transactions.py", line 114, in create_transaction
    val = bigchain.write_transaction(tx)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/core.py", line 144, in write_transaction
    response = r.table('backlog').insert(signed_transaction, durability=durability).run(self.conn)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/core.py", line 74, in conn
    self._conn = self.reconnect()
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/core.py", line 78, in reconnect
    return r.connect(host=self.host, port=self.port, db=self.dbname)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 661, in connect
    return conn.reconnect(timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 572, in reconnect
    return self._instance.connect(timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 430, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 318, in __init__
    char = self.recvall(1, deadline)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 365, in recvall
    raise ReqlTimeoutError(self.host, self.port)
rethinkdb.errors.ReqlTimeoutError: Could not connect to localhost:28015, operation timed out.
ERROR:bigchaindb.web.server:Exception on /api/v1/transactions/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 359, in recvall
    chunk = self._socket.recv(length - len(res))
socket.timeout: timed out
```

**Comment by sohkai** [comment]
@lingbage We recently solved an [issue related to performance with `bigchaindb load`](https://github.com/bigchaindb/bigchaindb/pull/908) that might have caused this issue (queues were unbounded, so your system might have run out of memory on trying to load too many transactions).

If you upgrade BigchainDB to master (or in the new year, to 0.9 when that gets released) and try this again, do you still see the same error message?

**Comment by lingbage** [comment]
I'm sorry to reply so late. 
I upgrade BigchainDB to 0.9, and doesn't see the error again.But I'm not sure if the error is caused by the 'maxsize' of the queue.
