### ISSUE TITLE
Rewriting transactions from invalid block may lead to DoubleSpends

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#774]
From @diminator in https://github.com/bigchaindb/bigchaindb/pull/614#issuecomment-250196840, who needs to update the scripts causing this issue to 0.7.0-compatible code:

reproduce by:

```bash
git clone git@github.com:bigchaindb/hyperchaindb.git
git checkout bug/doublespent-on-owned
cd bigchaindb_workshop
# virtualenv
pip install -e . [dev]
# start bigchaindb
bigchaindb start
# start webserver in terminal 2 (virtualenv & cd bigchaindb_workshop)
python -m backend.server
# run example in terminal 3 (virtualenv & cd bigchaindb_workshop)
python -m exercises.bdb.ex1_tx_create_transfer_solution
```

You will now see the following output:

```
[2016-09-28 17:01:00 +0200] [30802] [INFO] Booting worker with pid: 30802
INFO:bigchaindb.pipelines.block:Write new block 1c21b76bcf9ffa522b54f5589c9ae73b871f419ec80be7807dddc40e9b7911fb with 1 transactions
INFO:bigchaindb.pipelines.block:Write new block 9baf086364c79ef20b84c5a8178d4f3f6317b6299df6ca1aa99a6608bb052488 with 1 transactions
INFO:bigchaindb.pipelines.block:Write new block dd25da2c599451f7dd267291004cc01add98dae38f6060c4a76f581ecc05abae with 1 transactions
INFO:bigchaindb.pipelines.election:Rewriting 1 transactions from invalid block dd25da2c599451f7dd267291004cc01add98dae38f6060c4a76f581ecc05abae
```

Which means that the block was invalid and rewritten...

Running the example again (python -m exercises.bdb.ex1_tx_create_transfer_solution) yields Doublespend mania on get_owned_ids:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dimi/code_ascribe/hyperchaindb/src/github.com/hyperchaindb/bigchaindb_workshop/exercises/bdb/ex1_tx_create_transfer_solution.py", line 28, in <module>
    printd(get_tx_owned(dimi['vk']))
  File "/home/dimi/code_ascribe/hyperchaindb/src/github.com/hyperchaindb/bigchaindb_workshop/exercises/bdb/driver.py", line 35, in get_tx_owned
    return b.get_owned_ids(vk)
  File "/home/dimi/code_ascribe/hyperchaindb/src/github.com/hyperchaindb/bigchaindb_workshop/venv/lib/python3.5/site-packages/bigchaindb/core.py", line 368, in get_owned_ids
    if not self.get_spent(tx_input):
  File "/home/dimi/code_ascribe/hyperchaindb/src/github.com/hyperchaindb/bigchaindb_workshop/venv/lib/python3.5/site-packages/bigchaindb/core.py", line 317, in get_spent
    tx_input['txid']))
bigchaindb.exceptions.DoubleSpend: `74bdebbb947bf9c99d7e1510e8b97ad3ba02ea74f97dfe1042a832f64d6f8984` was spent more then once. There is a problem with the chain
```

**Comment by libscott** [comment]
I have tried to reproduce this here: https://github.com/bigchaindb/bigchaindb/commit/6c78417863ab0ad8a6dab5b7b5ceafa3942023df

The test passes fine. Seeing as this is from October I'll assume that the bug was fixed in the meantime. @sohkai @r-marques @diminator feel free to re-open if appropriate.
