### ISSUE TITLE
Getting Started (Tutorial) - b.get_transaction get None

### ISSUE THREAD

**Issue by dieface** [bigchaindb/bigchaindb#87]
I followed "Getting Started (Tutorial)", and was running "3.3. Read the Creation Transaction from the DB"
try `tx_retrieved` = `b.get_transaction(tx_signed['id'])` but get None. May I miss anything?

![image](https://cloud.githubusercontent.com/assets/2155132/13322673/795c0f6a-dc10-11e5-9b66-c4b2612370b4.png)

**Comment by r-marques** [comment]
Did you have the `bigchaindb` service running with `bigchaindb start`?
If so you need to wait a couple of seconds for the transaction to be included in a block. You should see in the output of `bigchandb start` a new vote being printed when you first write the transaction.

**Comment by dieface** [comment]
After run `rethinkdb`
```rethinkdb
$rethinkdb
Running rethinkdb 2.2.1 (CLANG 7.0.0 (clang-700.1.76))...
Running on Darwin 15.2.0 x86_64
Loading data from directory /Users/brucelee/Documents/MyDocuments/Workspace/db_playground/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "daijuns_MacBook_Pro_3_local_ohs" 9cafeb70-cebc-48dc-a49b-d687b32aa3c7
A newer version of the RethinkDB server is available: 2.2.5. You can read the changelog at <https://github.com/rethinkdb/rethinkdb/releases>.
```

I run `bigchaindb start`
```bigchaindb
$bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/Users/brucelee/.bigchaindb`
INFO:bigchaindb.commands.bigchain:Start bigchaindb main process
INFO:bigchaindb.processes:starting bigchain mapper
INFO:bigchaindb.processes:starting backlog mapper
INFO:bigchaindb.processes:starting block
INFO:bigchaindb.processes:starting voter
INFO:bigchaindb.block:bootstraping block module...
INFO:bigchaindb.block:finished reading past transactions
INFO:bigchaindb.voter:voter waiting for new blocks
Process validate_transactions:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/BigchainDB-0.1.4-py3.5.egg/bigchaindb/block.py", line 60, in validate_transactions
    monitor.gauge('tx_queue_gauge', self.q_tx_to_validate.qsize(), rate=bigchaindb.config['statsd']['rate'])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

Got `NotImplementedError`. Have tried `pip3 install bigchaindb --upgrade` but get the same error.

**Comment by rhsimplex** [comment]
Hey @dieface, are you using Mac OSX? I looked through the implementation of `queues.py` and noticed this:

```python
def qsize(self):
    # Raises NotImplementedError on Mac OSX because of broken sem_getvalue()
    return self._maxsize - self._sem._semlock._get_value()
```

**Comment by r-marques** [comment]
Right now we are focusing on supporting linux.
For other operating systems the the best is to use docker as described in the documentation https://bigchaindb.readthedocs.org/en/develop/installing-server.html#run-bigchaindb-with-docker
