### ISSUE TITLE
Starting bigchain db

### ISSUE THREAD

**Issue by eqinvlab** [bigchaindb/bigchaindb#885]
I have installed thinkDB and bigchainDB in my linux machine (ubuntu). Am trying to run the basic example for sometime now without any luck.

**Error:**

```
INFO:bigchaindb.processes:Starting voter
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 74, in run_forever
    self.run()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 106, in run
    result = self.target(*args)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/pipelines/block.py", line 78, in validate_tx
    tx_validated = self.bigchain.is_valid_transaction(tx)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 182, in is_valid_transaction
    return self.validate_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 163, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/consensus.py", line 14, in validate_transaction
    return transaction.validate(bigchain)
AttributeError: 'NoneType' object has no attribute 'validate'
```

**Error continuation:**

```
**[2016-11-29 18:08:44 +0530] [27266] [INFO] Starting gunicorn 19.6.0
[2016-11-29 18:08:44 +0530] [27266] [ERROR] Connection in use: ('localhost', 9984)
[2016-11-29 18:08:44 +0530] [27266] [ERROR] Retrying in 1 second.
[2016-11-29 18:08:45 +0530] [27266] [ERROR] Connection in use: ('localhost', 9984)
[2016-11-29 18:08:45 +0530] [27266] [ERROR] Retrying in 1 second.
[2016-11-29 18:08:46 +0530] [27266] [ERROR] Connection in use: ('localhost', 9984)
[2016-11-29 18:08:46 +0530] [27266] [ERROR] Retrying in 1 second.
[2016-11-29 18:08:47 +0530] [27266] [ERROR] Connection in use: ('localhost', 9984)
[2016-11-29 18:08:47 +0530] [27266] [ERROR] Retrying in 1 second.
[2016-11-29 18:08:48 +0530] [27266] [ERROR] Connection in use: ('localhost', 9984)
[2016-11-29 18:08:48 +0530] [27266] [ERROR] Retrying in 1 second.
[2016-11-29 18:08:49 +0530] [27266] [ERROR] Can't connect to ('localhost', 9984)
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 74, in run_forever
    self.run()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 106, in run
    result = self.target(*args)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/pipelines/block.py", line 78, in validate_tx
    tx_validated = self.bigchain.is_valid_transaction(tx)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 182, in is_valid_transaction
    return self.validate_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 163, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/consensus.py", line 14, in validate_transaction
    return transaction.validate(bigchain)
AttributeError: 'NoneType' object has no attribute 'validate'
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 74, in run_forever
    self.run()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 106, in run
    result = self.target(*args)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/pipelines/block.py", line 78, in validate_tx
    tx_validated = self.bigchain.is_valid_transaction(tx)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 182, in is_valid_transaction
    return self.validate_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 163, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/consensus.py", line 14, in validate_transaction
    return transaction.validate(bigchain)
AttributeError: 'NoneType' object has no attribute 'validate'
Process Process-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 74, in run_forever
    self.run()
  File "/usr/local/lib/python3.5/site-packages/multipipes/pipeline.py", line 106, in run
    result = self.target(*args)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/pipelines/block.py", line 78, in validate_tx
    tx_validated = self.bigchain.is_valid_transaction(tx)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 182, in is_valid_transaction
    return self.validate_transaction(transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/core.py", line 163, in validate_transaction
    return self.consensus.validate_transaction(self, transaction)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/consensus.py", line 14, in validate_transaction
    return transaction.validate(bigchain)
AttributeError: 'NoneType' object has no attribute 'validate'

**_This continues for Process Process-8 and I have no idea as to what it means._**
```

we are trying a develop a prototype in bigchaindb and this is blocking our progress a lot. Am new to bighchaindb and rethinkDB and if somone can let me know where am going wrong that would be great.

**Note:** I have the latest versions of rethinkDB, bigChainDB and other dependencies. Also am running both on a single linux machine.

**Comment by ttmc** [comment]
What version of Ubuntu are you using? How much RAM does the machine have? Can you walk us through the steps you did to get to the point of getting the above AttributeErrors? Which "basic example" are you referring to?

We just updated BigchainDB Server and the BigchainDB Python Driver this afternoon. Perhaps you could try using those (server 0.8.0 and Python driver 0.1.0). To upgrade them, you can use:
```bash
pip install --upgrade bigchaindb bigchaindb_driver
```

**Comment by eqinvlab** [comment]
@ttmc Thanks for your help.  It solved my problem with starting BigchainDB in Ubuntu.

**Ubuntu version** am using is **16.0.4** which is installed on top of **Windows 10** and my machine has **16 GB RAM.** 

Now am trying run a example program in BigchainDB, am following the steps from this link:
[https://www.sitepoint.com/managing-data-storage-with-blockchain-and-bigchaindb/](url)
 and getting the below error. 

```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from bigchaindb import Bigchain
ImportError: No module named bigchaindb
```
Any inputs on this? If I should create a new issue for this please let me know.

**Comment by ttmc** [comment]
That post by Chris Ward (on Sitepoint) was published in April 2016. He was using an old version of BigchainDB (a current one at the time). A lot has changed since then. That probably explains why you can't repeat what he did.

Using the new versions of BigchainDB (0.8.0) and the BigchainDB Python Driver (0.1.0), you can try the basic usage examples at:

https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html

I'm going to close this issue. If you run into problems, then create a new issue or ask on Gitter:

https://gitter.im/bigchaindb/bigchaindb
