### ISSUE TITLE
Not able to serialize fulfillment

### ISSUE THREAD

**Issue by iamdebu** [bigchaindb/bigchaindb#920]
# Trying to create 1 of 2 threshold condition using the example provided in the "Handcrafting Transaction-Multiple owners", throwing below exception 
#  buffer must be of type bytearray

import json

import sha3
import cryptoconditions

from bigchaindb_driver.crypto import generate_keypair

car_asset = {
    'data': {
        'car': {
            'vin': '5YJRE11B781000196',
        },
    },
    'divisible': False,
     'refillable': False,
     'updatable': False,
     'id': '5YJRE11B781000196',
}

alice, bob = generate_keypair(), generate_keypair()
alice_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=alice.verifying_key)
bob_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=bob.verifying_key)

# Change here to make threshold as 1 (1 of 2 condition)
threshold_sha256 = cryptoconditions.ThresholdSha256Fulfillment(threshold=1)
threshold_sha256.add_subfulfillment(alice_ed25519)
threshold_sha256.add_subfulfillment(bob_ed25519)
unsigned_subfulfillments_dict = threshold_sha256.to_dict()
condition_uri = threshold_sha256.condition.serialize_uri()

condition = {
    'amount': 1,
    'cid': 0,
    'condition': {
        'details': unsigned_subfulfillments_dict,
        'uri': threshold_sha256.condition_uri,
    },
    'owners_after': (alice.verifying_key, bob.verifying_key),
}

fulfillment = {
    'fid': 0,
    'fulfillment': None,
    'input': None,
    'owners_before': (alice.verifying_key,),
}

handcrafted_car_creation_tx = {
    'transaction': {
        'asset': car_asset,
        'metadata': None,
        'operation': 'CREATE',
        'conditions': (condition,),
        'fulfillments': (fulfillment,),
    },
    'version': 1,
}

json_str_tx = json.dumps(
    handcrafted_car_creation_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

car_creation_txid = sha3.sha3_256(json_str_tx.encode()).hexdigest()
handcrafted_car_creation_tx['id'] = car_creation_txid
message = json.dumps(
    handcrafted_car_creation_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

alice_ed25519.sign(message.encode(),
                   cryptoconditions.crypto.Ed25519SigningKey(alice.signing_key))
fulfillment_uri = alice_ed25519.serialize_uri()
handcrafted_car_creation_tx['transaction']['fulfillments'][0]['fulfillment'] = fulfillment_uri
from bigchaindb_driver import BigchainDB

bdb = BigchainDB('http://localhost:9984/api/v1')
returned_car_creation_tx = bdb.transactions.send(handcrafted_car_creation_tx)

# TRANSFER: ***********************************************************************************
carol = generate_keypair()

carol_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=carol.verifying_key)

unsigned_fulfillments_dict = carol_ed25519.to_dict()

condition_uri = carol_ed25519.condition.serialize_uri()

condition = {
    'amount': 1,
    'cid': 0,
    'condition': {
        'details': unsigned_fulfillments_dict,
        'uri': condition_uri,
    },
    'owners_after': (carol.verifying_key,),
}

fulfillment = {
    'fid': 0,
    'fulfillment': None,
    'input': {
        'txid': handcrafted_car_creation_tx['id'],
        'cid': 0,
    },
    'owners_before': (alice.verifying_key, bob.verifying_key),
}

handcrafted_car_transfer_tx = {
    'transaction': {
        'asset': {'id': car_asset['id']},
        'metadata': None,
        'operation': 'TRANSFER',
        'conditions': (condition,),
        'fulfillments': (fulfillment,),
    },
    'version': 1,
}

json_str_tx = json.dumps(
    handcrafted_car_transfer_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

car_transfer_txid = sha3.sha3_256(json_str_tx.encode()).hexdigest()

handcrafted_car_transfer_tx['id'] = car_transfer_txid

message = json.dumps(
    handcrafted_car_transfer_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

alice_sk = cryptoconditions.crypto.Ed25519SigningKey(alice.signing_key)

alice_condition = threshold_sha256.get_subcondition_from_vk(alice.verifying_key)[0]

alice_condition.sign(message.encode(), private_key=alice_sk)

# Issue in this line: *****************************
fulfillment_uri = threshold_sha256.serialize_uri()

handcrafted_car_transfer_tx['transaction']['fulfillments'][0]['fulfillment'] = fulfillment_uri

**Comment by iamdebu** [comment]
# I am able to serialize but below error is showing while sending the transaction:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/BigChainDB/lib/python3.4/site-packages/bigchaindb_driver/driver.py", line 187, in send
    method='POST', path=self.path, json=transaction)
  File "/usr/local/BigChainDB/lib/python3.4/site-packages/bigchaindb_driver/transport.py", line 46, in forward_request
    response = connection.request(method=method, path=path, json=json)
  File "/usr/local/BigChainDB/lib/python3.4/site-packages/bigchaindb_driver/connection.py", line 45, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.TransportError: (400, '{\n  "message": "Invalid transaction", \n  "status": 400\n}\n', {'status': 400, 'message': 'Invalid transaction'})

# The created transaction is as below:

{'version': 1, 'transaction': {'conditions': ({'owners_after': ('3hNxw7rwwAkGPxfigScBU6Zdb4xD1ZgR8bjfxuxu76R1',), 'cid': 0, 'condition': {'details': {'type': 'fulfillment', 'bitmask': 32, 'type_id': 4, 'public_key': '3hNxw7rwwAkGPxfigScBU6Zdb4xD1ZgR8bjfxuxu76R1', 'signature': None}, 'uri': 'cc:4:20:KA9w_5_TQOJm51bNUiN_ozma_SdOygpwKzgnQ1Mq4TQ:96'}, 'amount': 1},), 'fulfillments': ({'fid': 0, 'input': {'cid': 0, 'txid': '016631ccccd702a6c97b7dc5cf403bfc2d0124a1ebbcafa0ae2cf0e4c6fa699b'}, 'owners_before': ('CxrS8thiHCr3dTtbNwXvBGGkdWwePjZjmjpQTGVwKVVB', 'vBbNNsvGJ7TJpSTNzjrSfUjRpzQ4fSPe8JzqhuFCY3u'), 'fulfillment': 'cf:2:AQEBAQEBYwAEYLG_ZSsxjCfQuizh8hkcBAexlwdxhpMj5fIIb12TYL_CxVlEaYIHdtHn56VrLDGYI5TKO0CHpRxyYXLEF-NaxXFMNIVbRdKhgtzRGDxK8NQKFDtge83tQUpy1wBdtxIBCQA'},), 'asset': {'id': '5YJRE11B781000196'}, 'metadata': None, 'operation': 'TRANSFER'}, 'id': '7a3fe9e4f82c399205dade1a786acff8bdc7bedab8e53a5324f4cbeade861655'}

#------------------------------------------------------------------
# I am new to the whole technology stack, please help.
#------------------------------------------------------------------
import json
import sha3
import cryptoconditions
from time import sleep
from cryptoconditions.types.timeout import timestamp
from bigchaindb_driver.crypto import generate_keypair

#Create the asset

car_asset = {
    'data': {
        'car': {
            'vin': '5YJRE11B781000196',
        },
    },
    'divisible': False,
     'refillable': False,
     'updatable': False,
     'id': '5YJRE11B781000196',
}

alice, bob = generate_keypair(), generate_keypair()

#CRYPTO-CONDITIONS: instantiate an Ed25519 crypto-condition for alice
alice_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=alice.verifying_key)

#CRYPTO-CONDITIONS: instantiate an Ed25519 crypto-condition for bob
bob_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=bob.verifying_key)

#CRYPTO-CONDITIONS: instantiate a threshold SHA 256 crypto-condition
# Change here to make threshold as 1 (1 of 2 condition)
threshold_sha256 = cryptoconditions.ThresholdSha256Fulfillment(threshold=1)

#CRYPTO-CONDITIONS: add alice ed25519 to the threshold SHA 256 condition
threshold_sha256.add_subfulfillment(alice_ed25519)

#CRYPTO-CONDITIONS: add bob ed25519 to the threshold SHA 256 condition
threshold_sha256.add_subfulfillment(bob_ed25519)

#CRYPTO-CONDITIONS: get the unsigned fulfillment dictionary (details)
unsigned_subfulfillments_dict = threshold_sha256.to_dict()

#CRYPTO-CONDITIONS: generate the condition uri
condition_uri = threshold_sha256.condition.serialize_uri()

condition = {
    'amount': 1,
    'cid': 0,
    'condition': {
        'details': unsigned_subfulfillments_dict,
        'uri': condition_uri,
    },
    'owners_after': (alice.verifying_key, bob.verifying_key),
}

#The yet to be fulfilled fulfillment:
fulfillment = {
    'fid': 0,
    'fulfillment': None,
    'input': None,
    'owners_before': (alice.verifying_key,),
}

#Craft the payload:
handcrafted_car_creation_tx = {
    'transaction': {
        'asset': car_asset,
        'metadata': None,
        'operation': 'CREATE',
        'conditions': (condition,),
        'fulfillments': (fulfillment,),
    },
    'version': 1,
}

#JSON: serialize the id-less transaction to a json formatted string
#Generate the id, by hashing the encoded json formatted string representation of
#the transaction:
json_str_tx = json.dumps(
    handcrafted_car_creation_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

#SHA3: hash the serialized id-less transaction to generate the id
car_creation_txid = sha3.sha3_256(json_str_tx.encode()).hexdigest()

#add the id
handcrafted_car_creation_tx['id'] = car_creation_txid

#JSON: serialize the transaction-with-id to a json formatted string
message = json.dumps(
    handcrafted_car_creation_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

#CRYPTO-CONDITIONS: sign the serialized transaction-with-id
alice_ed25519.sign(message.encode(),
                   cryptoconditions.crypto.Ed25519SigningKey(alice.signing_key))

#CRYPTO-CONDITIONS: generate the fulfillment uri
fulfillment_uri = alice_ed25519.serialize_uri()

#add the fulfillment uri (signature)
handcrafted_car_creation_tx['transaction']['fulfillments'][0]['fulfillment'] = fulfillment_uri

from bigchaindb_driver import BigchainDB

bdb = BigchainDB('http://localhost:9984/api/v1')
returned_car_creation_tx = bdb.transactions.send(handcrafted_car_creation_tx)



# Transfer the asset
#-----------------------------------------------------------------

carol = generate_keypair()

alice_ed25519_transfer = cryptoconditions.Ed25519Fulfillment(public_key=alice.verifying_key)

bob_ed25519_transfer = cryptoconditions.Ed25519Fulfillment(public_key=bob.verifying_key)

carol_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=carol.verifying_key)

unsigned_fulfillments_dict = carol_ed25519.to_dict()

condition_uri = carol_ed25519.condition.serialize_uri()

condition_transfer = {
    'amount': 1,
    'cid': 0,
    'condition': {
        'details': unsigned_fulfillments_dict,
        'uri': condition_uri,
    },
    'owners_after': (carol.verifying_key,),
}

#The yet to be fulfilled fulfillments:
fulfillment_transfer= {
    'fid': 0,
    'fulfillment': None,
    'input': {
        'txid': handcrafted_car_creation_tx['id'],
        'cid': 0,
    },
    'owners_before': (alice.verifying_key, bob.verifying_key),
}

#Craft the payload:
handcrafted_car_transfer_tx = {
    'transaction': {
        'asset': {'id': car_asset['id']},
        'metadata': None,
        'operation': 'TRANSFER',
        'conditions': (condition_transfer,),
        'fulfillments': (fulfillment_transfer,),
    },
    'version': 1,
}

#Generate the id, by hashing the encoded json formatted string
#representation of the transaction:
json_str_tx_transfer = json.dumps(
    handcrafted_car_transfer_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)

car_transfer_txid = sha3.sha3_256(json_str_tx_transfer.encode()).hexdigest()

handcrafted_car_transfer_tx['id'] = car_transfer_txid

#Sign the transaction:
message_transfer = json.dumps(
    handcrafted_car_transfer_tx,
    sort_keys=True,
    separators=(',', ':'),
    ensure_ascii=False,
)


alice_sk = cryptoconditions.crypto.Ed25519SigningKey(alice.signing_key)

threshold_sha256_transfer = cryptoconditions.ThresholdSha256Fulfillment(threshold=1)
threshold_sha256_transfer.add_subfulfillment(alice_ed25519_transfer)

alice_condition = threshold_sha256_transfer.get_subcondition_from_vk(alice.verifying_key)[0]
alice_condition.sign(message_transfer.encode(), private_key=alice_sk)

fulfillment_uri = threshold_sha256_transfer.serialize_uri()

handcrafted_car_transfer_tx['transaction']['fulfillments'][0]['fulfillment'] = fulfillment_uri

# Issue in this line

returned_car_transfer_tx = bdb.transactions.send(handcrafted_car_transfer_tx)

**Comment by iamdebu** [comment]
# I am able to solve this now. The solution is as below:- 
#------------------------------------------------------------------
import json
import sha3
import cryptoconditions
from time import sleep
from cryptoconditions.types.timeout import timestamp
from bigchaindb_driver.crypto import generate_keypair

#Create the asset

car_asset = {
'data': {
'car': {
'vin': '5YJRE11B781000196',
},
},
'divisible': False,
'refillable': False,
'updatable': False,
'id': '5YJRE11B781000196',
}

alice, bob = generate_keypair(), generate_keypair()

#CRYPTO-CONDITIONS: instantiate an Ed25519 crypto-condition for alice
alice_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=alice.verifying_key)

#CRYPTO-CONDITIONS: instantiate an Ed25519 crypto-condition for bob
bob_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=bob.verifying_key)

#CRYPTO-CONDITIONS: instantiate a threshold SHA 256 crypto-condition

Change here to make threshold as 1 (1 of 2 condition)

threshold_sha256 = cryptoconditions.ThresholdSha256Fulfillment(threshold=1)

#CRYPTO-CONDITIONS: add alice ed25519 to the threshold SHA 256 condition
threshold_sha256.add_subfulfillment(alice_ed25519)

#CRYPTO-CONDITIONS: add bob ed25519 to the threshold SHA 256 condition
threshold_sha256.add_subfulfillment(bob_ed25519)

#CRYPTO-CONDITIONS: get the unsigned fulfillment dictionary (details)
unsigned_subfulfillments_dict = threshold_sha256.to_dict()

#CRYPTO-CONDITIONS: generate the condition uri
condition_uri = threshold_sha256.condition.serialize_uri()

condition = {
'amount': 1,
'cid': 0,
'condition': {
'details': unsigned_subfulfillments_dict,
'uri': condition_uri,
},
'owners_after': (alice.verifying_key, bob.verifying_key),
}

#The yet to be fulfilled fulfillment:
fulfillment = {
'fid': 0,
'fulfillment': None,
'input': None,
'owners_before': (alice.verifying_key,),
}

#Craft the payload:
handcrafted_car_creation_tx = {
'transaction': {
'asset': car_asset,
'metadata': None,
'operation': 'CREATE',
'conditions': (condition,),
'fulfillments': (fulfillment,),
},
'version': 1,
}

#JSON: serialize the id-less transaction to a json formatted string
#Generate the id, by hashing the encoded json formatted string representation of
#the transaction:
json_str_tx = json.dumps(
handcrafted_car_creation_tx,
sort_keys=True,
separators=(',', ':'),
ensure_ascii=False,
)

#SHA3: hash the serialized id-less transaction to generate the id
car_creation_txid = sha3.sha3_256(json_str_tx.encode()).hexdigest()

#add the id
handcrafted_car_creation_tx['id'] = car_creation_txid

#JSON: serialize the transaction-with-id to a json formatted string
message = json.dumps(
handcrafted_car_creation_tx,
sort_keys=True,
separators=(',', ':'),
ensure_ascii=False,
)

#CRYPTO-CONDITIONS: sign the serialized transaction-with-id
alice_ed25519.sign(message.encode(),
cryptoconditions.crypto.Ed25519SigningKey(alice.signing_key))

#CRYPTO-CONDITIONS: generate the fulfillment uri
fulfillment_uri = alice_ed25519.serialize_uri()

#add the fulfillment uri (signature)
handcrafted_car_creation_tx['transaction']['fulfillments'][0]['fulfillment'] = fulfillment_uri

from bigchaindb_driver import BigchainDB

bdb = BigchainDB('http://localhost:9984/api/v1')
returned_car_creation_tx = bdb.transactions.send(handcrafted_car_creation_tx)

# Transfer the asset
#-----------------------------------------------------------------

carol = generate_keypair()
alice_ed25519_transfer = cryptoconditions.Ed25519Fulfillment(public_key=alice.verifying_key)
bob_ed25519_transfer = cryptoconditions.Ed25519Fulfillment(public_key=bob.verifying_key)
carol_ed25519 = cryptoconditions.Ed25519Fulfillment(public_key=carol.verifying_key)
unsigned_fulfillments_dict = carol_ed25519.to_dict()
condition_uri = carol_ed25519.condition.serialize_uri()

condition_transfer = {
'amount': 1,
'cid': 0,
'condition': {
'details': unsigned_fulfillments_dict,
'uri': condition_uri,
},
'owners_after': (carol.verifying_key,),
}

#The yet to be fulfilled fulfillments:
fulfillment_transfer= {
'fid': 0,
'fulfillment': None,
'input': {
'txid': handcrafted_car_creation_tx['id'],
'cid': 0,
},
'owners_before': (alice.verifying_key, bob.verifying_key),
}

#Craft the payload:
handcrafted_car_transfer_tx = {
'transaction': {
'asset': {'id': car_asset['id']},
'metadata': None,
'operation': 'TRANSFER',
'conditions': (condition_transfer,),
'fulfillments': (fulfillment_transfer,),
},
'version': 1,
}

#Generate the id, by hashing the encoded json formatted string
#representation of the transaction:
json_str_tx_transfer = json.dumps(
handcrafted_car_transfer_tx,
sort_keys=True,
separators=(',', ':'),
ensure_ascii=False,
)

car_transfer_txid = sha3.sha3_256(json_str_tx_transfer.encode()).hexdigest()

handcrafted_car_transfer_tx['id'] = car_transfer_txid

#Sign the transaction:
message_transfer = json.dumps(
handcrafted_car_transfer_tx,
sort_keys=True,
separators=(',', ':'),
ensure_ascii=False,
)

alice_sk = cryptoconditions.crypto.Ed25519SigningKey(alice.signing_key)

threshold_fulfillment = cryptoconditions.Fulfillment.from_dict(handcrafted_car_creation_tx['transaction']['conditions'][0]['condition']['details'])
subfulfillment1 = threshold_fulfillment.get_subcondition_from_vk(alice.verifying_key)[0]
subfulfillment2 = threshold_fulfillment.get_subcondition_from_vk(bob.verifying_key)[0]

threshold_fulfillment.subconditions = []
subfulfillment1.sign(message_transfer.encode(), private_key=alice_sk)
threshold_fulfillment.add_subfulfillment(subfulfillment1)
threshold_fulfillment.add_subcondition(subfulfillment2.condition)

fulfillment_uri = threshold_fulfillment.serialize_uri()
handcrafted_car_transfer_tx['transaction']['fulfillments'][0]['fulfillment'] = fulfillment_uri
returned_car_transfer_tx = bdb.transactions.send(handcrafted_car_transfer_tx)
